README.rst
Add the Travis CI button to the repo `README.rst`
=> [docs] add travis ci button to README

docs/source/deploy-rollback.rst, docs/source/deployment.rst, docs/source/faq.rst, docs/source/getting-started.rst, docs/source/index.rst, docs/source/overview.rst
=> docs - change toc order, add to faq, more

docs/source/index.rst
to: @jacknagz 
index.rst - github-link
=> index.rst - github-link

docs/source/conf-schemas.rst, docs/source/rules.rst
to: @jacknagz 
**Changes**
- Add documentation about `req_subkeys`
- Address linter warnings
- Cleanup grammar
**Testing**
- Verified via `make html` and viewing locally in my browser
=> [docs] req_subkeys - add documentation

stream_alert_cli/test.py
size: small
resolves: #57 
**changes**
Files that are unable to be dumped to json will now be skipped in the loop.
Also resolving issues in two places where we would try to continue with operations even if the opening of the file failed.
=> [cli][testing] skipping files that cannot be dumped to json

conf/logs.json, docs/source/deploy-rollback.rst, docs/source/deployment.rst, docs/source/index.rst, docs/source/overview.rst, docs/source/rule-testing.rst, docs/source/rules.rst, rules/helpers/base.py, rules/sample_rules.py, stream_alert_cli/test.py, test/integration/rules/sample_kv_rule_last_hour.json, test/unit/test_rule_helpers.py, variables.json
size: medium
resolves #52 
* Add Integration testing helper functions
* Update rule helpers with `in_network` and `valid_ip`
* Update example configuration and rules
* Update documentation on rule testing
* Fix codeblock style on documentation pages
=> Helper Functions and Docs Update

docs/source/datasources.rst, docs/source/deploy-rollback.rst, docs/source/deployment.rst, docs/source/requirements.rst
size: small
* Updates Deployment documentation per the staging environment consolidation.  
* Rewording in the Datasources page.
=> [docs] Datasources and Deployment Updates

stream_alert/alert_processor/main.py
size: small
* Added an output handler for Phantom.
* REST data collector needs to be configured in Phantom.
* Secret should be structured and encrypted exactly like slack,
* https://PHANTOMURL,YOUR-TOKEN-HERE
* Added request_helper optional args "headers" and "verify" to allow 
* output to ignore server certificate checking. Default is verify=True
* Removed request_helper required arg "endpoint" as it's no longer needed.
* request_helper returns its urllib2 response to allow for outputs to
* chain http requests and better validate successful requests.
=> [lambda][output] request_helper changes and phantom output

docs/source/conf-schemas-examples.rst, docs/source/conf-schemas.rst, docs/source/deployment.rst, docs/source/kinesis-firehose.rst, docs/source/kinesis-streams.rst, docs/source/lambda.rst, docs/source/roadmap.rst, docs/source/rule-testing.rst, docs/source/rules.rst
size: large
* Kinesis and Lambda settings update per the v2 of `variables.json`.
* Overhaul of writing Schemas.  Goes in-depth on every configuration option available to every parser.  Updates examples used for parsers/schemas. 
* Explains `optional_top_level_keys`.
* Explains the usage of the new `@disable` decorator.
* Formatting/wording fixes
=> Docs: @disable, terraform build, optional_top_level_keys, parsing/schemas, and more

docs/source/rules.rst, rules/sample_rules.py
size: small
* Updating current sample rules to reflect the new aws-s3 service identifier used for output declaration.
* Some small doc updates to go with this change.
=> [rules] updating rule outputs to conform to new aws-s3 service identifier

stream_alert/alert_processor/main.py
size: small
* Skipping sns records that are related to alarms
* Adding a logging.info output that will print the number of records being processed when the alert processor is ran
Alarm messages do not have the same 'default' required key needed to process the message. We don't really care about these messages right now anyway, so we can just skip them without logging an error. If there is an alarm message, it comes in with the format:
```
{
"AWSAccountId": “1234567890”,
"AlarmDescription": “This is the alarm description",
"AlarmName": “This is the alarm name",
"NewStateReason": "Threshold Crossed: 1 datapoint (0.5) was greater than the threshold (0.0).",
"NewStateValue": "ALARM",
"OldStateValue": "OK",
"Region": "<region>",
"StateChangeTime": …
```
=> [lambda][output] skip sns messages for alarms

stream_alert/alert_processor/main.py, stream_alert/alert_processor/outputs.py, stream_alert/rule_processor/config.py
size: small
* Some alert processor updates that were made to the internal repo already to resolve some issues
* Alerts were being sent to slack with ugly metadata
* Updating the description for what is needed for lambda during output configuration
* Various other nits
=> [sync] adding some changes that made it into the internal repo first

.travis.yml
size: small
background: https://blog.travis-ci.com/2017-04-17-precise-EOL
=> [testing] add trusty for build env

docs/source/conf-schemas-examples.rst
=> streamalert - quick doc fix

rules/sample_rules/sample_rules.py, stream_alert/rule_processor/main.py
* Adding code to handle nested rule folder importing
=> [rules] adding code to handle nested rule folder importing

stream_alert/alert_processor/outputs.py, stream_alert_cli/package.py
* Making pip changes to be more readable.
=> [package] fixed some nits

stream_alert/rule_processor/rules_engine.py
Addresses https://github.com/airbnb/streamalert/issues/151
=> streamalert - process_rule - LOGGER.exception

stream_alert/alert_processor/outputs.py
to @jacknagz 
* Fixing a bug where the `_load_creds` method could return `None` if there was an error pulling/decrypting credentials. The result was not being validated and we would attempt to load info from a `None` object.
* Also fixing an logging call that was not using our `LOGGER` instance.
* Moving Phantom endpoint urls suffixes to constants on the `PhantomOutput` class.
* Migrating `container_url` to within the `_setup_container` method since it's not used outside of that scope.
=> [lambda][outputs] adding a check for credentials

test/unit/stream_alert_alert_processor/__init__.py, test/unit/stream_alert_alert_processor/test_main.py, test/unit/stream_alert_alert_processor/test_output_base.py, test/unit/stream_alert_alert_processor/test_outputs.py
to @jacknagz 
size: small
* Small tweaks to how config is loaded to go with #169 
* These updates are necessary to keep from breaking tests with changes to the actual config.
=> [tests] additional small tweaks to alert processor testing

stream_alert_cli/terraform_generate.py, terraform/modules/tf_stream_alert/iam.tf
size: small
follow up to #174
see commits for changes
=> JSON Template Bug Fixes

README.rst
* Adding coveralls.io badge to streamalert repo.
=> adding coveralls.io badge to README.rst

docs/source/getting-started.rst, docs/source/index.rst
=> [docs] fix the navi panel kinesis page and getting started

docs/source/conf-schemas.rst
to @jacknagz 
size: small
* Adding updated info about new usage of `optional_top_level_keys` related to changes in #167.
* Adding info related to `log_pattern` updates that were added a while back.
=> [docs] adding updated info after `optional_top_level_keys` bug fix..

.coveragerc, .gitignore, .travis.yml, requirements.txt
to @jacknagz 
* Adding coveralls repo token file to git ignore and adding coveralls to requirements/travis.yml
=> adding coveralls repo token file to git ignore and adding coveralls

docs/source/rule-testing.rst
to @mime-frame  
size: small
* docs now include information on running multiple types of integration tests, and include update output example.
=> [docs] integration test doc updates for testing processors

stream_alert_cli/outputs.py, test/unit/stream_alert_cli/test_outputs.py
to @jacknagz 
size: small
* Adding tests for `stream_alert_cli.outputs` to increase coverage on that file to 100%
* Fixing bug in `outputs.py` found during addition of unit tests.
=> [tests] cli output tests

stream_alert_cli/outputs.py, test/unit/stream_alert_cli/test_outputs.py
to @jacknagz 
* Fixing bug that caused aws output configurations to exit early
=> [cli][outputs] fixing bug for adding aws outputs

CONTRIBUTING.rst, docs/source/account.rst, docs/source/clusters.rst, docs/source/conf-datasources.rst, docs/source/conf-schemas-examples.rst, docs/source/conf-schemas.rst, docs/source/conf.py, docs/source/datatypes.rst, docs/source/deployment.rst, docs/source/index.rst, docs/source/kinesis.rst, docs/source/lambda.rst, docs/source/outputs.rst, docs/source/overview.rst, docs/source/requirements.rst, docs/source/roadmap.rst, docs/source/rule-testing.rst, docs/source/rules.rst
to @jacknagz 
* Adding `json` code highlighting to blocks of json code. Resolving any errors with syntax along the way.
* Resolving some errors found when running `make html` in the docs folder. These were largely related to table formatting, but also fixed a few other bugs along the way.
* Adding `bash` code blocks where applicable.
=> [docs] resolving a handful of sphinx errors and adding json code highlighting

docs/source/lambda.rst
to @jacknagz 
* One last bug fix for a link. Goes along with updates in https://github.com/airbnb/streamalert/pull/212.
=> [docs] fixing link in docs

requirements.txt, test/scripts/autoflake.sh
to @jacknagz 
* Adding `autoflake` to requirements.txt and adding helper script to repo to be used for checking files for unused imports.
* Usage: `test/scripts/autoflake.sh /path/to/folder/or/python.py`
=> [scripts] adding autoflake script to repo

stream_alert/athena_partition_refresh/main.py, test/unit/stream_alert_athena_partition_refresh/test_main.py
to @jacknagz 
size: small
* Fixing bug where nonexistent `logger` object was being used instead of `LOGGER`
* https://github.com/airbnb/streamalert/compare/ryandeivert-athena-logger-bug-fix?expand=1#diff-3159770d8fb42356c5e4163f106792c1R222
* Other autopep8 nits
* Adding test for coverage on line where bug existed
=> [lambda][athena] athena logger bug fix

.gitignore, stream_alert/athena_partition_refresh/main.py, stream_alert_cli/runner.py, stream_alert_cli/terraform_generate.py, stream_alert_cli/test.py, terraform/modules/tf_stream_alert_athena/README.md, terraform/modules/tf_stream_alert_athena/iam.tf, terraform/modules/tf_stream_alert_athena/main.tf, terraform/modules/tf_stream_alert_athena/outputs.tf, terraform/modules/tf_stream_alert_athena/variables.tf, test/unit/stream_alert_athena_partition_refresh/test_main.py
**to**: @chunyong-lin (Terraform, Lambda), @ryandeivert (Lambda, CLI, Tests)
**cc**: @airbnb/streamalert-maintainers 
**size**: large
Currently, the Athena Partition Refresh Lambda function is invoked directly (by s3) when new data is written to a bucket.  If the write volume is low, this isn't an issue, but if it's very high, we have a potential to refresh the same Athena table multiple times a second/minute.  This is unnecessary since the smallest data partition is in one minute intervals. 
To fix this issue, I have added an SQS queue to be the recipient of s3 event notifications.  This also modifies how Lambda is invoked, since it now runs on a CloudWatch event timer of `10 minutes`.  
When the Lambda is now invoked, it fetches up to `50` messages from SQS, and deduplicates the s3 …
=> Athena SQS Support

stream_alert_cli/config.py
to: @jacknagz 
Found missing close angle bracket.
=> [cli] Add a missing angle bracket.

docs/source/athena-deploy.rst, stream_alert_cli/terraform_generate.py, test/unit/stream_alert_cli/test_terraform_generate.py
to @chunyong-lin 
* Add an option to change the Athena Lambda function invocation rate via the StreamAlert CLI config
* Update tests
* Update docs
=> [cli] support athena refresh interval option

stream_alert_cli/config.py, tests/unit/helpers/base.py, tests/unit/stream_alert_cli/test_config.py
size: small
* Adding until tests for cli metric toggling and cli metric alarm creation.
=> [test][cli] adding some cli metric tests to increase coverage

conf/logs.json
Resolves #315 
**Testing**
`python manage.py lambda test --processor all`
& 
`python manage.py validate-schemas`
=> make account of type string

conf/logs.json, conf/types.json, stream_alert/rule_processor/handler.py, stream_alert_cli/helpers.py, stream_alert_cli/terraform/_common.py, stream_alert_cli/terraform/generate.py, stream_alert_cli/test.py, tests/scripts/autopep8.sh
size: medium
Fixes several bugs identified in the Firehose changes, see commits for details
=> Bug Fixes from Firehose

stream_alert_cli/logger.py
fix a regression in firehose log output suppression
=> [cli] suppress new firehose messages

app_integrations/apps/app_base.py, app_integrations/apps/duo.py, tests/unit/app_integrations/test_apps/test_app_base.py
to: @jacknagz 
size: small
resolves N/A
* N/A
* Making a few logger messages info instead of debug since they are not very noisy.
* Also moving a log message that reports if there are more logs to poll to the base class instead of within the duo class.
* Updating unit tests to check for info logger message.
=> [apps] moving logger to base and updating some levels

stream_alert/rule_processor/parsers.py
size: small
When deploying the latest `json_regex_key` feature with the JSON parser, a couple bugs were identified.
* Clearer debug statements
* Symmetric difference for missing keys message: reveals additional fields
* Fixes a bug where False was returned when list was expected
Locally with unit tests
=> [parsers] bug fixes for json regex key

stream_alert/rule_processor/parsers.py, tests/unit/stream_alert_rule_processor/test_parsers.py
cc: @airbnb/streamalert-maintainers @chunyong-lin 
size: medium
Follow up to #380 and #387.  
Deployment of JSON Regex Key matching against a larger set of data introduced more issues with parsing.  The loading of the regex matched string into `json.loads` threw errors since it was improperly caught.
* Catch invalid matched JSON
* Add unit test coverage
* Locally with unit tests
=> [parsers] json regex key bug fixes

stream_alert_cli/test.py
to: @jacknagz 
size: small
resolves N/A
Test events that do not have their source properly defined (or, more concisely, if the log type is missing from the `source.json`) would silently fail test.
* Checking if the source is properly configured before trying to perform schema validation.
* Changed the local `sources.json` to omit a log type and verified the following output occurs (along with failing tests):
`
StreamAlertCLI [ERROR]: (2/2) Failures
`
`
StreamAlertCLI [ERROR]: (1/2) Invalid test event in file '<filename>.json' with description 'Description would be here'. The 'sources.json' file does not include the log type 'cloudtrail' in the list of logs for this service & entitiy ('kinesis:<entity-here>').
`
=> [cli][test] reporting misconfigured source in test event

manage.py, stream_alert/athena_partition_refresh/main.py, stream_alert/rule_processor/parsers.py, stream_alert_cli/runner.py, terraform/modules/tf_stream_alert_monitoring/main.tf, tests/unit/stream_alert_rule_processor/test_parsers.py
size: small
Various bugs identified from development.
See commits
Deployed in testing AWS account
=> Athena Logger, JSON Regex Key Bug Fixes, and More

tests/unit/app_integrations/test_apps/test_onelogin.py
size: small
Previous code coverage was 100% for the new OneLogin app integration but we added support for extracting the remaining number of seconds for a rate limit and that coverage went down to 94%. Unacceptable!
* Bringing up the coverage to 100% by testing the rate limiting extraction feature.
Running `./tests/scripts/pylint.sh` to check the coverage:
```
...
Name                                            Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------
app_integrations.py                                13      0   100%
app_integrations/apps.py                            7      0   100%
app_integrations/apps/app_base.py                 114      0   100% …
```
=> [apps][tests] Adding 100% coverage to onelogin app

docs/source/getting-started.rst
cc: <optional-cc-to-specific-users>
size: small|medium|large
Just a small documentation update
* how to solve psutil installation problems with python-dev
* ...
=>  getting started minor update

app_integrations/__init__.py
to: @javuto 
size: small
resolves N/A
Time for a version bump.
* Bumps version from `0.0.1` --> `1.0.0`
N/A
=> [apps] bumping apps version to 1.0.0

stream_alert_cli/test.py
to: @jacknagz or @javuto 
size: small
resolves N/A (assisting with #437)
With more output options being added, it's become problematic to mock out `requests.get` and `requests.post` calls with static values. Essentially, some output tests would pass and others would fail, depending on what a given rule had designated as outputs.
* Adding a dynamic way to return context depending on what service is being mocked out. This utilizes the mock's `side_effect` function to point to a function that returns the proper data.
* The `jira` support in the is in accordance with the upcoming changes in #437.
* Tested with @armtash's branch from #437 with these changes played over top and a rule that had the following outputs listed:
``` …
```
=> [test] adding dynamic mocking of requests during tests

conf/logs.json, helpers/base.py
size: small
resolves N/A
These rule helper functions are to assist in searching records for arbitrary information.
* Adding helpers from @mime-frame 
Tested against various datasets, etc locally.
=> [helpers] adding some rule helpers crafted by @mime-frame

conf/logs.json
cc: <optional-cc-to-specific-users>
size: small
resolves #447
=> Make requestID optional for issue #447

stream_alert/rule_processor/handler.py, tests/unit/stream_alert_rule_processor/test_handler.py
size: small
resolves #478 
See issue
* Catch `ConnectionError`
* `./tests/scripts/unit_test.sh`
* `./tests/scripts/pylint.sh`
=> [lambda] backoff and catch botocore connectionerror

stream_alert/alert_processor/outputs/phantom.py, tests/unit/stream_alert_alert_processor/test_outputs/test_phantom.py
size: small
Backoff support allows to retry requests when something goes wrong.
* Added support for backoff in phantom output.
* Added new test to keep the 100% code coverage.
```
...
TOTAL                                                    2809    103    96%
Ran 491 tests in 9.066s
OK
... …
```
=> [output] Backoff support in phantom output

tests/unit/stream_alert_alert_processor/test_outputs/test_jira.py
size: small
Just bringing code coverage back to 100%.
* Added new tests so coverage will be again 100% after adding backoff support.
```
...
TOTAL                                                    2803     99    96%
Ran 494 tests in 9.749s
OK
...
```
=> [output] 100% coverage for Jira output

stream_alert_cli/terraform/generate.py, tests/unit/stream_alert_cli/terraform/test_generate.py
size: small
Upgrade the Terraform Provider AWS to a current version
* Create a `dict` constant to store Terraform versions
* Ran `python manage.py terraform init-backend`, and then a `python manage.py terraform build`
=> [tf] upgrade aws provider to current version

app_integrations/apps/gsuite.py, tests/unit/app_integrations/test_apps/test_gsuite.py
to: @javuto 
size: small
resolves #540
Noticed a crash in CloudWatch logs related to an ssl timeout. Stack trace as follows:
```
('_ssl.c:574: The handshake operation timed out',): SSLError
app.gather()
File "/var/task/app_integrations/apps/app_base.py", line 438, in gather
File "/var/task/app_integrations/apps/app_base.py", line 423, in _gather
File "/usr/lib64/python2.7/timeit.py", line 237, in timeit
return Timer(stmt, setup, timer).timeit(number)
File "/usr/lib64/python2.7/timeit.py", line 202, in timeit
timing = self.inner(it, self.timer)
File …
```
=> [apps][gsuite] catching another timeout that can occur with ssl

app_integrations/apps/gsuite.py, tests/unit/app_integrations/test_apps/test_gsuite.py
to: @javuto  
size: small
resolves #551 
See #551. Gist:
Google's oauth2client can raise a handful of errors that should be caught and retried by the client, but it does not do this well.
* Catching the `oauth2client.client.HttpAccessTokenRefreshError` error, along with any other client related errors that may occur.
* Adding test to ensure the error is properly caught.
=> [apps] catching more execptions to include HttpAccessTokenRefreshError

docs/source/roadmap.rst
size: small
Fix out of date Roadmap page in the docs
* `./tests/scripts/test_the_docs.sh`
=> [docs] update roadmap to point to github

conf/logs.json
size: medium
resolves N/A
Updating some outdated schemas and sorting the keys in json logs. The sorting results in what appears to be a lot of changes).
* All rule tests still passing successfully.
=> [logs] cleaning up the logs.json file, along with sorting it

manage.py, stream_alert/__init__.py, stream_alert_cli/__init__.py
to: @jacknagz or @chunyong-lin 
size: small
resolves N/A
* Version bump from `1.5.0` --> `1.6.0`
=> bumping version from 1.5.0 -> 1.6.0

docs/source/account.rst, docs/source/alternatives.rst, docs/source/clusters.rst, docs/source/conf-datasources.rst, docs/source/conf-schemas.rst, docs/source/datasources.rst, docs/source/deploy-rollback.rst, docs/source/deployment.rst, docs/source/firehose.rst, docs/source/getting-started.rst, docs/source/kinesis.rst, docs/source/lambda.rst, docs/source/requirements.rst
to: @ryandeivert @chunyong-lin @mime-frame 
size: medium
Go through the documentation and remove technical debt, fix grammar, and modify style.
Locally via the `test_the_docs.sh` script
=> [docs] 2018 refresh

matchers/matchers.py, rules/community/guardduty/guard_duty_all.py, rules/community/guardduty/guardduty.py, tests/integration/rules/guardduty/guard_duty_all.json, tests/integration/rules/guardduty/guardduty.json
size: small
resolves #503 
Adds a rule for GuardDuty and a test for it
Setup StreamAlert. Enabled GuardDuty. Added this.
=> Add rule and test for GuardDuty

conf/logs.json
size: small
resolves #606 
See #606
Deployed to our own StreamAlert deployment and no errors.
=> Added more values to the CloudTrail schema

conf/outputs.json, docs/source/rules.rst, helpers/base.py, rules/community/cloudtrail/cloudtrail_critical_api_calls.py, rules/community/cloudtrail/cloudtrail_mfa_policy_abuse_attempt.py, rules/community/cloudtrail/cloudtrail_network_acl_ingress_anywhere.py, rules/community/cloudtrail/cloudtrail_put_bucket_acl.py, rules/community/cloudtrail/cloudtrail_put_object_acl_public.py, rules/community/cloudtrail/cloudtrail_root_account_usage.py, rules/community/cloudtrail/cloudtrail_security_group_ingress_anywhere.py, rules/community/duo_administrator/duo_bypass_code_create_non_auto_generated.py, rules/community/duo_administrator/duo_bypass_code_create_non_expiring.py, rules/community/duo_administrator/duo_bypass_code_create_unlimited_use.py, rules/community/duo_authentication/duo_anonymous_ip_failure.py, rules/community/duo_authentication/duo_fraud.py, rules/community/github/github_disable_dismiss_stale_pull_request_approvals.py, rules/community/github/github_disable_protect_this_branch.py, rules/community/github/github_disable_required_pull_request_reviews.py, rules/community/github/github_disable_required_status_checks.py, rules/community/github/github_disable_two_factor_requirement_org.py, rules/community/github/github_disable_two_factor_requirement_user.py, rules/community/github/github_oauth_application_create.py, rules/community/github/github_site_admin_action.py, rules/community/github/github_site_admin_user_promotion.py, rules/community/guardduty/guard_duty_all.py, rules/community/mitre_attack/defense_evasion/multi/obfuscated_files_or_information/right_to_left_character.py, rules/community/onelogin/onelogin_events_assumed_role.py, stream_alert/rule_processor/rules_engine.py, tests/unit/stream_alert_rule_processor/test_rule_helpers.py
size: medium
While writing rules, discovered that `req_subkeys` is not checking that each sub-key is a truthy value, which ends up resulting in KeyErrors.
Wanted to also standardize on a default output for community rules, and also apply `yapf` formatting to them.
* Required Sub-keys bug fix + docs update
* Community rules formatting with `yapf` and update default outputs
* New `safe_json_loads` helper with unit test
* Docs update
Local CI
=> Required Sub-key Bug Fix, Community Rules Update, and More

conf/logs.json, stream_alert/rule_processor/firehose.py, stream_alert/rule_processor/payload.py, stream_alert/rule_processor/threat_intel.py, stream_alert_cli/athena/handler.py, stream_alert_cli/test.py, tests/unit/stream_alert_rule_processor/test_payload.py, tests/unit/stream_alert_rule_processor/test_threat_intel.py
to: @austinbyers or @jacknagz 
size: small
Ran:
* `git checkout master && git pull origin master`
* `git checkout release-2.0.0 && git checkout -b ryandeivert-rebase-into-release-2`
* `git merge origin/master`
* `git commit`
* `git push origin ryandeivert-rebase-into-release-2`
=> merging master into release 2.0.0 branch

docs/source/getting-started.rst, stream_alert/__init__.py
to: @austinbyers or @jacknagz or @javuto 
size: small
* Bumping version from `1.6.0` --> `1.6.1`
* Updating docs to reference tag checkout.
=> cutting release 1.6.1 with various bug fixes

stream_alert_cli/athena/handler.py
size: small
* Fixing key name in config lookup
=> [bug] fix key name in athena create table function

stream_alert_cli/test.py
size: small
Small bug fix in rule test templates
Locally with `rule_tests.sh`
=> [cli] test rule template bug fix

stream_alert/rule_processor/payload.py
cc: @airbnb/streamalert-maintainers, @jbussing 
size: small
resolves #587
See #587
* Explicitly call os.close on the underlying open file descriptor that is created when using `tempfile.mkstemp()`
=> explicitly closing underlying file descriptors for temp files (fixes #587)

manage.py
size: small
* Small fixes to `manage.py` help strings for athena subcommands.
=> fixing help message for athena cli commands

stream_alert_cli/helpers.py, stream_alert_cli/test.py, tests/unit/stream_alert_alert_processor/test_outputs/test_carbonblack.py
cc: @ryandeivert 
size: small
Found errors while trying to test rules with the new Carbon Black Output
* Updated testing code
Tested locally.
=> Sync Carbon Black Output - Test error updates

tests/unit/app_integrations/test_apps/test_app_base.py, tests/unit/stream_alert_rule_processor/test_payload.py
size: small
* Updating a few unit tests that were starting to slow things down.
* Adding a proper test for shredding of temp dir.
That's what this is ;)
=> updating some slow unit tests

rules/community/cloudtrail/cloudtrail_ec2_image_creation.py, tests/integration/rules/cloudtrail/cloudtrail_ec2_image_creation.json
to: @fusionrace @0xdabbad00 
size: medium
Add two rules with tests for catching public AMIs and unencrypted volumes 
Local testing
=> [community rules] ami creation rules for encryption and permissions

.gitignore
size: small 
Add VSCode to Git Ignore
=> Ignore vscode files

stream_alert/shared/lookup_tables.py, tests/unit/stream_alert_shared/test_lookup_tables.py
cc: @airbnb/streamalert-maintainers, @strcrzy, @jbussing 
size: small
As an optimization, gzip compressing the lookup files stored in S3 will have shorter latency and result in less S3 cost over time.
* Adding decompression capability when loading lookup files from S3.
* If the file is not gzip'd, we will load the original raw data into json.
Adding unit test to confirm decompression works as expected.
=> adding optional gzip decompression for lookup file loading from s3

stream_alert/rule_processor/classifier.py, stream_alert_cli/helpers.py, stream_alert_cli/test.py
size: small
Empty values should be allowed during type conversion.
* Allowing for null/NoneType values during type conversion in classification.
N/A
=> allow for null/NoneType values during type conversion

app_integrations/apps/app_base.py, app_integrations/apps/slack.py
size: small
resolves N/A
Increase app default request timeout to 5 seconds.
Deployed in internally, and all Apps are working correctly.
=> [app] increase app default request timeout

.gitignore, README.rst
size: small
* Updating readme to reflect new doc updates
* Removing IDE specific git ignores that should be included in user's global gitignore file, not per-project.
=> updating readme to reflect new doc updates

AUTHORS.rst, docs/source/rule-testing.rst, setup.cfg, stream_alert/__init__.py, tests/scripts/unit_tests.sh
size: small
* Updating authors list
* Small fix to docs
* official bump to v2 🎆
=> bumping version to v2.0.0

stream_alert_cli/helpers.py
cc: @airbnb/streamalert-maintainers, @arrkaye
resolves #825
See #825 
The current method for checking for valid creds only checks for specific environment variables to be set. However, when using the `~/.aws/credentials` or the `~/.aws/config` file's `default` profile, these variables do not have to be set.
* Using boto3 and `sts` to get the identity of the caller instead of checking for environment variables.
=> using STS to identify valid AWS credentials instead of env vars

stream_alert/__init__.py
Bumping version from 2.1.0 to 2.1.1
=> bumping version to 2.1.1

stream_alert/__init__.py
=> bumping version to 2.1.2

stream_alert/__init__.py
=> bumping version to 2.1.5

docs/source/app-configuration.rst, stream_alert/apps/_apps/duo.py, stream_alert_cli/apps/handler.py, stream_alert_cli/apps/helpers.py, stream_alert_cli/config.py
resolves: #876
See #876
* Properly looking up the 'existing' app by name in the config, and using its function name to update the auth info.
* Fixing a type in description used when requesting auth info for Duo (and updating docs to match).
Ran through this a currently deployed app and works as expected.
=> fixing bug related to updating app auth information

docs/source/getting-started.rst
to:
related to:
resolves:
Reason for the change
* Summary of changes
* ...
=> fixed typo "DyanmoDB"

terraform/modules/tf_stream_alert_cloudtrail/main.tf
to: @Ryxias 
I accidentally introduced a terraform bug in #905: 
`Error: data.aws_iam_policy_document.cloudtrail_bucket: resource repeated multiple times`
* Fixing the duplicative iam policy doc.
terraform validate now passing.
=> [bug] fixing duplicate policy bug with cloudtrail bucket

stream_alert/__init__.py
Bumping version from 2.1.5 --> 2.1.6
=> bumping version to 2.1.6

docs/source/publishers.rst, publishers/community/generic.py, stream_alert/alert_processor/outputs/aws.py, stream_alert/alert_processor/outputs/slack.py, stream_alert/rules_engine/rules_engine.py, stream_alert/shared/publisher.py, tests/unit/stream_alert_shared/test_publisher.py
=> [Fixup] Alert Publisher PR Feedback

stream_alert/alert_processor/outputs/pagerduty.py, tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
to: @chunyong-lin @ryandeivert 
related to:
resolves:
We received some requests regarding changes in default behavior of certain pages. This tweaks them back to normal.
CI?
=> Fix some bugs introduced due to "default behavior" in pagerduty integration

stream_alert/alert_processor/outputs/pagerduty.py, tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
related to:
resolves:
This is what I get for not writing tests
=> Fix really dumb bug

manage.py
replace "validate" which is wrong with "classifier" which is right
fix minor annoyance when testing
* replace "validate" which is wrong with "classifier" which is right in the manage.py argparser
* ...
🤞
=> minor argparser fix for manage.py validate

stream_alert/classifier/parsers.py, tests/unit/streamalert/classifier/test_parsers_json.py
resolves: #930 
Yep, this fixes the subtle bug when calling jmespath and adds a test for it
=> [bug] fixes a bug in parsing json objects with jmespath

stream_alert/classifier/main.py, stream_alert/rules_engine/main.py
to: @chunyong-lin or @Ryxias 
cc: @0xdabbad00 
resolves: #944
See #944
* Logging traceback with invocation event in both classifier and rules engine if any uncaught exception occurs.
N/A
=> logging trackback if any general exception occurs in classifier or rules engine

docs/source/rules.rst
Documentation is misleading
N/A
=> Fix incorrect documentation

tests/integration/rules/cloudtrail/cloudtrail_critical_api_calls.json, tests/integration/rules/cloudtrail/cloudtrail_public_resources.json, tests/integration/rules/cloudtrail/cloudtrail_snapshot_or_ami_made_public.json
to: @Ryxias 
* fixing poor formatting in some json test files
=> cleaning up json formatting on some test files

stream_alert_cli/manage_lambda/package.py
cc: @ryandeivert, @chunyong-lin 
Small typo.
* Fix typo in requirements.
N/A
=> Small fix for policy_universe.

stream_alert/__init__.py
=> Bump version to 2.2.1 in preparation for cutting release

docs/source/athena-arch.rst, rules/community/duo_administrator/duo_bypass_code_create_non_auto_generated.py, stream_alert/alert_processor/outputs/carbonblack.py, stream_alert/apps/_apps/aliyun.py, stream_alert/apps/_apps/slack.py, stream_alert/apps/app_base.py, stream_alert/classifier/clients/firehose.py, stream_alert/classifier/clients/sqs.py, stream_alert/shared/athena.py, stream_alert_cli/terraform/athena.py, stream_alert_cli/terraform/cloudtrail.py, tests/integration/rules/box/box_admin_events.json, tests/integration/rules/gsuite/gsuite_admin.json, tests/unit/helpers/aws_mocks.py
to: @chunyong-lin / @Ryxias 
* Hotfix/links and spelling (#967)
* Bumped slack app timeout (#983)
=> merging master into release-3-0-0 branch

.gitignore
* ignoring `/.vagrant` instead of `/vagrant`
=> adding proper vagrant ignore

docs/source/index.rst, docs/source/lookup-tables.rst, stream_alert/shared/lookup_tables/cache.py, stream_alert/shared/lookup_tables/driver_s3.py, tests/unit/stream_alert_shared/lookup_tables/test_cache.py, tests/unit/stream_alert_shared/lookup_tables/test_driver_s3.py
to: @ryandeivert or @chunyong-lin or @blakemotl 
In addition to RST documentation I fixed some broken tests
=> LookupTables documentation

streamalert_cli/terraform/cloudwatch.py, streamalert_cli/terraform/generate.py, tests/unit/streamalert_cli/terraform/test_generate.py
to: @Ryxias 
Fixing missing variable in terraform `tf_cloudwatch` module
=> fix missing tf var issue

docs/source/testing.rst
=> Fix a typo in docs

streamalert/shared/alert_table.py, tests/unit/streamalert/alert_merger/test_main.py, tests/unit/streamalert/shared/test_alert_table.py
This code doesn't look like it is being used anymore.
=> Cleans up dead code

streamalert_cli/terraform/flow_logs.py, terraform/modules/tf_cloudwatch_logs_destination/iam.tf, tests/unit/streamalert_cli/terraform/test_generate.py
to: @Ryxias 
* Removing an unused `region` variable from the `tf_flow_logs` module
* Fixing list formatting bug in `tf_cloudwatch_logs_destination` module.
Update to unit tests.
=> fix bugs found during terraform applies

terraform/modules/tf_cloudtrail/modules/tf_cloudtrail_cloudwatch/main.tf
to: @Ryxias 
Missed this in #1069.
* Removing an IAM statement that isn't actually used for anything.
Deployed
=> remove invalid/unnecessary statement in terraform 

docs/source/outputs.rst
to: @Ryxias 
related to: #1080 
resolves:
Missing new output from docs
* added `aws-ses` to outputs.rst
Ran `tests/scripts/test_the_docs.sh` and verified change visually
=> [docs] added aws-ses to outputs.rst

docs/source/outputs.rst, streamalert/alert_processor/outputs/credentials/provider.py, terraform/modules/tf_alert_processor_iam/main.tf, tests/unit/streamalert/alert_processor/outputs/test_output_base.py
to: @ryandeivert  @jack1902
related to: #1142
Addresses @ryandeivert 's comment: https://github.com/airbnb/streamalert/pull/1142#discussion_r382267969
Didn't test yet
=> Follow up PR to SSM migration

streamalert_cli/helpers.py, streamalert_cli/outputs/handler.py, streamalert_cli/outputs/helpers.py, streamalert_cli/utils.py
to: @ryandeivert @blakemotl @chunyong-lin 
https://github.com/airbnb/streamalert/pull/1138
Merges the above in, as I forgot to do it earlier
=> Merges 3.0.0 into 3.1.0... hopefully for the last time

conf/clusters/prod.json, conf/schemas/packetbeat.json, rules/community/packetbeat/packetbeat_blacklist_domain.py, rules/community/packetbeat/packetbeat_blacklist_ip.py, rules/community/packetbeat/packetbeat_dns_lookup.py, tests/integration/rules/packetbeat/packetbeat_bad_actions.json, tests/integration/rules/packetbeat/packetbeat_schema.json
to:
related to:
resolves:
Add packetbeat schema 
Sorry no unit test's
=> [Logs] Packetbeat

streamalert/alert_processor/outputs/phantom.py, streamalert/alert_processor/outputs/slack.py, streamalert_cli/terraform/scheduled_queries.py
to: @ryandeivert @blakemotl @chunyong-lin 
* Fixes incorrect input restrictions on URLs
* Fixes a bug with scheduled_queries terraform
Tested on prod yolo!
=> Fixes a bug when generating scheduled_queries terraform 

streamalert_cli/terraform/handlers.py
to: @blakemotl / @Ryxias 
Blake and Derek found a bug.
* I fixed the bug.
Local test to see if terraform complains.
=> [bug] fixing bug with building resources as targets

streamalert/athena_partition_refresh/main.py, streamalert/shared/config.py, streamalert_cli/terraform/athena.py, streamalert_cli/terraform/scheduled_queries.py
=> DRY's out some code

docs/source/apps.rst, docs/source/config-clusters.rst, docs/source/datasources.rst, docs/source/getting-started.rst, docs/source/historical-search.rst, docs/source/rules.rst, streamalert/__init__.py, streamalert/athena_partition_refresh/main.py, streamalert/shared/config.py, streamalert_cli/_infrastructure/modules/tf_scheduled_queries/cloudwatch_schedule.tf, streamalert_cli/_infrastructure/modules/tf_scheduled_queries/iam_roles.tf, streamalert_cli/_infrastructure/modules/tf_scheduled_queries/step_function.tf, streamalert_cli/_infrastructure/modules/tf_scheduled_queries/versions.tf, streamalert_cli/terraform/athena.py, streamalert_cli/terraform/scheduled_queries.py
=> official release of v3.1.1

streamalert_cli/_infrastructure/modules/tf_athena/iam.tf, streamalert_cli/_infrastructure/modules/tf_athena/main.tf, streamalert_cli/_infrastructure/modules/tf_athena/variables.tf, streamalert_cli/terraform/athena.py, tests/unit/conf/lambda.json, tests/unit/streamalert_cli/terraform/test_athena.py
Fixing bugs Chunyong found in #1217 
* Updating terraform resource names.
* Adding `lambda_timeout` variable that is used for calculating visibility window on sqs queue.
=> fixing duplicate resource issues

streamalert_cli/manage_lambda/deploy.py
Found bug with terraform targets of athena function.
* Fixing targets
=> fix terraform targets for athena deploy

streamalert_cli/_infrastructure/modules/tf_lambda/cloudwatch.tf, streamalert_cli/_infrastructure/modules/tf_lambda/iam.tf, streamalert_cli/_infrastructure/modules/tf_lambda/main.tf
related to: #1225 
Found 2 bugs during deploy of #1225.
* Fixing cycle issue with function name.
* Fixing index issue with optional resource.
Deployed
=> fixing cylce and index bug in tf_lambda module

docs/source/config-global.rst
* Doc update for `third_party_libraries` info in general section of `global.json`
=> doc update for third_party_libraries info

.github/workflows/ci.yml
=> another attempt to fix coverage in forks..

streamalert_cli/config.py, streamalert_cli/helpers.py, streamalert_cli/kinesis/handler.py, streamalert_cli/manage_lambda/deploy.py, streamalert_cli/terraform/handlers.py, streamalert_cli/terraform/helpers.py
resolves: #1266
See #1266
* Adding fix to build the `streamalert.zip` package any time lambda is being targeted, or a targetless build is being done.
=> fixing issue with streamalert.zip not existing at build times

streamalert_cli/manage_lambda/deploy.py, streamalert_cli/terraform/handlers.py, streamalert_cli/terraform/helpers.py
* Always building the deployment package to avoid issues with tf lambda module.
=> always build deployment package by default

streamalert_cli/apps/handler.py, streamalert_cli/config.py
resolves: #939
* Quick fix for #939
=> ensuring prefix is a lowercase string

Vagrantfile, docs/source/getting-started.rst, streamalert_cli/_infrastructure/_include.tf, streamalert_cli/_infrastructure/_providers.tf, streamalert_cli/_infrastructure/_variables.tf, streamalert_cli/_infrastructure/modules/tf_artifact_extractor/iam.tf, streamalert_cli/_infrastructure/modules/tf_cloudtrail/modules/tf_cloudtrail_cloudwatch/main.tf, streamalert_cli/_infrastructure/modules/tf_cloudtrail/modules/tf_cloudtrail_cloudwatch/output.tf, streamalert_cli/_infrastructure/modules/tf_flow_logs/main.tf, streamalert_cli/_infrastructure/modules/tf_globals/alerts_firehose/iam.tf, streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_setup/iam.tf, streamalert_cli/terraform/generate.py, tests/unit/streamalert_cli/terraform/test_generate.py
resolves: #1289 
See #1289 
* Updating terraform version and aws provider version
=> updating to terraform v0.13.0

Vagrantfile, docs/source/getting-started.rst, streamalert/__init__.py, streamalert_cli/_infrastructure/_include.tf, streamalert_cli/_infrastructure/_providers.tf, streamalert_cli/_infrastructure/_variables.tf, streamalert_cli/_infrastructure/modules/tf_artifact_extractor/iam.tf, streamalert_cli/_infrastructure/modules/tf_cloudtrail/modules/tf_cloudtrail_cloudwatch/main.tf, streamalert_cli/_infrastructure/modules/tf_cloudtrail/modules/tf_cloudtrail_cloudwatch/output.tf, streamalert_cli/_infrastructure/modules/tf_flow_logs/main.tf, streamalert_cli/_infrastructure/modules/tf_globals/alerts_firehose/iam.tf, streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_setup/iam.tf, streamalert_cli/terraform/generate.py, tests/unit/streamalert_cli/terraform/test_generate.py
=> official release of v3.4.0

rules/community/cloudwatch_events/cloudtrail_critical_api_calls.py
to:
related to:
resolves: https://github.com/airbnb/streamalert/issues/1298
Reason for the change
* Summary of changes
* ...
=> Update CloudTrail critical API calls 'cloudtrail:PutEventSelectors'

streamalert/__init__.py
=> 3.5.0 bump
