- stream_alert/pre_parsers.py
size: tiny
fixes an incorrect error message that may confuse users
> [pre_parsers] correct error for s3 objects > 128mb

- stream_alert_cli/test.py
* to avoid loading rules in two places (one for testing, one for the AWS Lambda function), import the entire `main` package to get the rule imports.
> [testing] import loaded rules from main.py

- requirements.txt
- terraform/variables.tf
- variables.json
* add `flow_log_settings` variable in `variables.json` and `variables.tf` to enable the usage of the new vpc flow log module.
* remove old `emulambda` dependency.
> [setup][tf] remove emulambda dep and add tfvar

- stream_alert/parsers.py
- test/unit/test_classifier.py
- test/unit/test_config.py
- test/unit/test_parsers.py
- test/unit/test_rule_helpers.py
- test/unit/test_rules_engine.py
size: small
* Ensure we are calling the `hints` option with `.get()`.  Not every parser has a `hints` property, so this would throw a `KeyError` if a given stream is analyzing both KV and CSV data.
* Add a `TestKVParser` unit testing class.
* Add descriptions to unit test methods.  Produces a nicer and readable output when running tests:
```
$ ./test/scripts/unit_tests.sh
Payload Classify CSV ... ok
Payload Classify Nested CSV ... ok
Payload Classify JSON ... ok
Payload Classify KV ... ok
Payload Classify Nested JSON ... ok
Payload Classify Nested JSON Missing Subkeys ... ok
Payload Classify JSON osquery ... ok
Payload Classify Nested JSON Generic ... ok
Payload Classify Syslog ... ok
Payload Source Mapping 1 ... ok
Payload Source Mapping 2 ... ok …
```
> [core][tests] csv parser bug and unit test descriptions

- stream_alert/handler.py
- stream_alert/sink.py
- stream_alert_output/main.py
- test/unit/test_sink.py
size: small
resolves: #51
**changes**
- Alerts will be sent in their own individual SNS messages to avoid hitting the 256kb limit
- Removing config from `StreamSink.init()` since it was unused.
- Adding tests for sink.py
> [lambda][output][testing] fix for maxing out sns message size limit

- docs/source/account.rst
size: tiny
markdown formatting was busted for the account setup page
> [docs] fix formatting

- conf/sources.json
- requirements.txt
- stream_alert/classifier.py
- stream_alert/parsers.py
- stream_alert/pre_parsers.py
- stream_alert_cli/test.py
- test/integration/rules/invalid_subnet.json
- test/integration/rules/invalid_user.json
- test/integration/rules/sample_csv_rule.json
- test/integration/rules/sample_json_rule.json
- test/integration/rules/sample_kv_rule.json
- test/integration/rules/sample_kv_rule_last_hour.json
- test/integration/rules/sample_syslog_rule.json
- test/integration/templates/s3.json
size: small
resolves: #61
Slight refactor to `test.py` to allow for a more generic way of testing various services.
Updating `sources.json` to include various source log types for s3.
`requirements.txt` now includes `moto==0.4.31`, as this is now used for boto3 mocking.
Updated integration rule files to include s3 service examples.
> [testing] updating cli testing to include s3 as a service

- stream_alert_cli/test.py
size: small
resolves: #73 
- Refactoring the cli testing code so all tests will run and report failures that occurred during the run. We will no longer bail out early on a test failure.
- Tracking if there are failures and exiting with an error code if any occur throughout the process.
> [cli][testing] cli testing will now fail gracefully after all tests have run

- conf/logs.json
- conf/sources.json
- rules/sample_rules.py
- stream_alert/rule_processor/classifier.py
- stream_alert/rule_processor/parsers.py
- stream_alert_cli/test.py
- test/integration/rules/sample_cloudtrail_rule.json
size medium
* Add default log types for `cloudtrail` eventVersions `1.04` and `1.05`.
* Add example rule for Cloudtrail
* Fix KeyError bugs in the `JSONParser` and `classifier` when parsing nested S3 data.
* Fix a bug in the `JSONParser. _key_check` where invalid records were not being removed due to the iteration technique.
* Support a new `trigger_count` key in test records to indicate the number of alerts generated by a nested record.
> Cloudtrail Example Schema, Rule, and Test

- stream_alert/rule_processor/handler.py
size: tiny
* Support the usage of AWS Lambda Environment variables to control logger level (coming soon).
* Log an error when unexpected events invoke the Lambda function.
* Fix a bug where 'Valid data, no alerts' was printing against invalid payloads.
> [lambda][rule_processor] env var log level and logger.error for invalid events

- conf/logs.json
- conf/sources.json
- rules/sample_rules.py
- terraform/modules/tf_stream_alert_cloudtrail/README.md
- terraform/modules/tf_stream_alert_cloudtrail/iam.tf
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/variables.tf
- test/integration/rules/sample_cloudwatch_cloudtrail_rule.json
- test/integration/rules/sample_cloudwatch_events_rule.json
size: medium
Adds a new Terraform module called `tf_stream_alert_cloudtrail` which accepts a Kinesis Stream as input to write CloudTrail logs to.
The module creates the following:
* AWS CloudTrail with a S3 bucket for long term storage.  If a user has an existing Cloudtrail, they can skip the creation via the `existing_trail` flag in the module (see `README.md` for example).
* CloudWatch event rule to forward all API calls (in all regions) to a designated Kinesis stream.
* IAM policy/role to allow CloudWatch Events to PutRecords to Kinesis.
Additionally, this change comes with two new schema types: `cloudwatch:cloudtrail` and `cloudwatch:ec2_event` along with a rule test/example rules. 
All testing was performed in a test AWS account, where end-to-end …
> [terraform] CloudTrail Support

- stream_alert_cli/config.py
- test/unit/stream_alert_cli/test_config.py
size: small
* When reading a v1 config, make sure to write it to disk.  This ensures that when we invoke Terraform with the new cluster format, all the variables are properly loaded.
> [cli] makes sure to write the new config format to disk

- terraform/modules/tf_stream_alert/main.tf
size: small
Retain the legacy bucket names by replacing all `_` with `.` as it previously was.
> [tf] ensure legacy output processor bucket names are retained

- terraform/modules/tf_stream_alert_flow_logs/README.md
- terraform/modules/tf_stream_alert_flow_logs/main.tf
to @strcrzy 
size small
* Add a specific `aws` provider for the `tf_stream_alert_flow_logs` Terraform module to account for multi-region resources.
* Update documentation for this change and for additional details.
> [tf] add aws provider and update docs for flow_log module

- terraform/modules/tf_stream_alert_flow_logs/variables.tf
* Fixes a bug in the CLI `lambda deploy`.  If no default value is provided, Terraform throws errors during lambda function deployment.
> [tf] add default value for flow_log module provider

- conf/logs.json
- rules/sample_rules.py
- stream_alert/rule_processor/sink.py
- stream_alert_cli/test.py
- test/integration/rules/sample_cloudtrail_rule.json
- test/integration/rules/sample_cloudwatch_flog_log_rule.json
- test/unit/test_sink.py
size: medium
* Fix a bug in `rule_processor:sink.py` to more reliably generate the SNS topic name.
* Add support in the sample `logs.json` for `cloudwatch` flow logs.
* Support testing of `flow_logs` via compressing events for the `gzip-json` parser.
* Add sample rule and test for `flow_logs`
* Add rules descriptions to previous  `cloudwatch` rules
> Sink py fix and compress testing support

- docs/source/conf-schemas.rst
- stream_alert/rule_processor/classifier.py
- test/unit/conf/logs.json
- test/unit/test_classifier.py
size: small
resolves #77 
* Support `[]`, `boolean`, and `float` schema types.
* Update docs.
* Add unit test coverage for these changes.
> List, Boolean, and Float Schema Types

- terraform/modules/tf_stream_alert/main.tf
size: small
Ensure that the `streamalerts` bucket ID follows the DNS scheme defined in other TF modules
> [tf] ensure streamalerts bucket follows DNS naming scheme

- stream_alert/rule_processor/classifier.py
size: small
* Check the loaded type of the value to convert to `boolean` before casting.  JSON may load a boolean into its correct type while other parsers will need to be converted from a string/unicode.
> [core] check loaded boolean type before converting

- stream_alert/alert_processor/main.py
size: small
Terraform replaces all `_` with `.` to generate the name of the [StreamAlerts S3 bucket](https://github.com/airbnb/streamalert/blob/master/terraform/modules/tf_stream_alert/main.tf#L56-L60).  This change must also occur in the Lambda function to ensure we send alerts to the correct bucket.
> [lambda][alert] fix a bug in getting the s3 bucket name to send alerts

- rules/sample_matchers.py
- rules/sample_rules.py
- stream_alert/rule_processor/rules_engine.py
- test/integration/rules/sample_syslog_rule.json
- test/unit/test_rules_engine.py
size: small
resolves #75 
* Add a new `@disable` decorator in the rules_engine to easily disable rules
* Update unit test cases
* Update sample configuration/rules/tests with a test matcher + disable implementation
> [core] disable decorator

- conf/logs.json
- stream_alert/rule_processor/classifier.py
- stream_alert/rule_processor/parsers.py
- test/scripts/autopep8.sh
- test/scripts/unit_tests.sh
- test/unit/conf/logs.json
- test/unit/test_classifier.py
- test/unit/test_gzip_json_parser.py
- test/unit/test_json_parser.py
- test/unit/test_kv_parser.py
size: medium
resolves #95 
* Nest all `conf/log` type options under a new key called `configuration`
* `hints` stays at the top level, since it's not an option, but rather a guard.
* `delimiter`, `separator` move under `configuration`.
* `envelope` is now called `envelope_keys` and nested under `configuration`.
* `records` is now called `json_path` and also nested under `configuration`.
* Create a new `configuration` key called `optional_top_level_keys`.
* The goal of this option is to allow log schemas to have optional keys with specific types.
* Sets default values for optional keys not in a specific incoming record.
* Fix various `pylint` offenses.
* Update unit tests
* Update sample configurations
* Update scripts
* Add an `autopep`  helper script …
> Optional Top Level Keys and Configuration Log Option

- conf/outputs.json
- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/outputs.py
size: small
* Fixing bug that would attempt to send alerts even if there was an error getting the configured output.
* Updating dispatching so only the record itself gets sent and not the included metadata.
* Changing wording of s3 example output.
> [lambda][output] fixing alert dispatching bugs

- stream_alert/alert_processor/output_base.py
- stream_alert/alert_processor/outputs.py
- stream_alert_cli.py
- stream_alert_cli/runner.py
- terraform/modules/tf_stream_alert/iam.tf
size: small
* adding AWS Lambda as a supported StreamAlert output
* terraform change to allow StreamAlert alert processor to invoke another Lambda function
* OutputProperty namedtuple now includes item to restrict during import
> [lambda][output] support for lambda as an output

- stream_alert/alert_processor/outputs.py
size: small
Revert of the change made for issue #58 to support de-duplication of incident on PagerDuty. See reopened and updated issue for more context.
> [lambda][output] revert: adding `incident_key` for pagerduty output

- docs/source/requirements.txt
This should fix the issue where readthedocs links don't work: https://github.com/airbnb/streamalert/issues/63
Example of someone else that implemented this fix: https://github.com/pytest-dev/pytest/issues/2302
> streamalert - fix rtd search links

- stream_alert_cli/runner.py
size: small
When a new output configuration is added, a logger message will now be printed informing the user that a the configuration was successful.
> [lambda][output][config] print log message when a new output added

- docs/source/outputs.rst
cc @mime-frame 
size: small
* Adding documentation updates to reflect changes made to the alert processor lambda function
* Demonstrates how to configure a new output for a currently supported service.
* Walks through the steps that need to be taken to implement support for sending to a new service.
* Updated to include Phantom as a supported output.
* Updated to include AWS Lambda as a supported output.
> [docs] updating documentation on outputs

- terraform/modules/tf_stream_alert_monitoring/main.tf
- terraform/modules/tf_stream_alert_monitoring/variables.tf
- terraform/templates/cluster_template
size small
Provides a richer set of alarms regarding:
* Lambda Throttles - Too many concurrent executions
* Lambda IteratorAge - Lambda falling behind processing
* Kinesis IteratorAge - The age of the last GetRecord request
* Kinesis Write Exceeded - Hitting shard limiits
> [tf] Additional Lambda/Kinesis CloudWatch Alarms

- conf/inputs.json
- conf/outputs.json
- stream_alert_cli/runner.py
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert/sns.tf
- terraform/modules/tf_stream_alert/variables.tf
- terraform/variables.tf
size: medium
#64 is half resolved by this change
* `inputs.json`: Declares input `sns` topics created outside the scope of StreamAlert.  The `rule_processor` is automatically subscribed to the topic ARNs and granted privileges to bets. invoked.
* `outputs.json`: New support for `aws-lambda` and `aws-s3` to dynamically update the `alert_processor` IAM policies.  This ensures the Lambda function can only send to the resources it needs to (and nothing more within the account).
* Appropriate Terraform changes to load both variable files into the `stream_alert_cli.py` runner.
* Terraformed on a test AWS account
> [tf] support SNS as an input, and arbitrary S3/Lambda functions as outputs

- conf/sources.json
- stream_alert/rule_processor/classifier.py
- stream_alert/rule_processor/config.py
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/pre_parsers.py
- stream_alert_cli/test.py
- test/integration/rules/invalid_subnet.json
- test/integration/rules/invalid_user.json
- test/integration/rules/sample_csv_rule.json
- test/integration/rules/sample_json_rule.json
- test/integration/rules/sample_kv_rule.json
- test/integration/rules/sample_kv_rule_last_hour.json
- test/integration/rules/sample_syslog_rule.json
size: small
work in progress for #64 
* Adding sns source support
* Updating tests to include sns sources
> [lambda][alert] adding support for sns as a source

- terraform/templates/cluster_template
size small
make sure we pass in the loaded s3/lambda/sns inputs/outputs through to the `stream_alert` terraform module
> [tf] pass inputs/outputs variables into stream_alert module via cluster template

- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/output_base.py
- stream_alert/alert_processor/outputs.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/rule_processor/sink.py
- stream_alert_cli/test.py
- test/unit/test_rules_engine.py
size: medium
resolve: #25 
* Alerts will now include a `rule_description` key within the `metadata` dictionary that is packaged with the alert.
* Moving the `rule_name` key that is sent with the alert into the `metadata` dictionary as well since it makes more sense and is cleaner.
* Alerts are now made up of two dictionaries: `metadata` (containing info related to this rule/alert) and `record` (containing the actual payload that triggered this alert).
* Updating tests to conform to the new `metadata` dict.
* Adding the `rule_description` as part of the alert sent to applicable configurations.
* Slack will now receive a `rule_description` as part of the message text
* PagerDuty will now receive a `rule_description` as part of the details
* Phantom will …
> [lambda][rule] send alerts with rule docstring

- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/pre_parsers.py
- test/unit/test_pre_parsers.py
size: small
* Will now yield and parse lines from an s3 file as they are read instead of reading once and then iterating over the lines a second time to parse.
> [lambda][rule] some s3 optimizations

- stream_alert/rule_processor/parsers.py
- stream_alert/rule_processor/pre_parsers.py
- stream_alert_cli/test.py
- test/unit/test_pre_parsers.py
Incoming SNS data should not be assumed to be base64-encoded, because it is designed to be a simple notification for email, texting, etc.
For example, the SNS message that the rule processor uses to [invoke the alert processor](https://github.com/airbnb/streamalert/blob/abb--sns-no-base64/stream_alert/rule_processor/sink.py#L112) is not base64-encoded.
@airbnb/streamalert-maintainers
> Remove base64 encoding from SNS input

- stream_alert_cli/test.py
size: small
* Updating the rule processor testing output to show a summary at the end indicating how many tests passed and how many failed out of the total ran.
* The tail of the output will now appear like the following if there are failures:
```
(33/35)	Tests Passed
(2/35)	Tests Failed
(1/2) test failed for rule: invalid_user [user not in the whitelist (john)]
(2/2) test failed for rule: sample_cloudwatch_cloudtrail_rule [cloudwatch cloudtrail 'Decrypt' event log]
```
* The `(#/#) Tests Passed` line will also be green, while all lines following it related to failures will be red.
* If all tests pass, only the first line above will be output, but would be:
```
(35/35)	Tests Passed
```
* This should aid in seeing which rules are passing and which are …
> [testing] improving rule processor test output by adding some summary info

- docs/source/rules.rst
Denote that one element must exist in `outputs`
> streamalert - rules.rst - outputs

- stream_alert/alert_processor/outputs.py
size: medium 
* Slack output will now use attachments and split the message on the Slack recommended size of 4000 characters/bytes.
* Output will also be formatted with tabs and "markdown" styling.
* Messages will look similar to this in Slack (with the proper App name/icon):
* Multi-part messages will have a `(Part # of n)` string after `Record`
> [lambda][output] updating slack output format to support large messages

- terraform/modules/tf_stream_alert/iam.tf
size: small
* Switching to using full aws arn for lambda invocation.
> [terraform] lambda resource update

- docs/source/conf-schemas.rst
- stream_alert/rule_processor/classifier.py
- stream_alert/rule_processor/parsers.py
- test/unit/conf/logs.json
- test/unit/conf/sources.json
- test/unit/test_classifier.py
- test/unit/test_gzip_json_parser.py
- test/unit/test_json_parser.py
- test/unit/test_kv_parser.py
size: medium
* Found that we were not applying `log_patterns` to logs that matched only one schema and fixed this so log_patterns will always be applied if they exist for a defined schema.
* Fixing a bug where typed data was not being returned in records
* Recursively nested parsing of csv and json are now supported
* Updating tests for multiple schema matching with log_patterns
* Updating tests for single schema matching with log_patterns
> [lambda][rule] fixing a bug related to log_pattern enforcement

- stream_alert/alert_processor/outputs.py
size: small
* Fixing bug where alert metadata would be unnecessarily sent with the alert body in the Slack message
> [outputs] fixing bug where alert metadata was sent with alert

- stream_alert/rule_processor/config.py
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/main.py
- stream_alert/rule_processor/pre_parsers.py
- stream_alert/rule_processor/sink.py
- stream_alert_cli/test.py
- test/unit/test_config.py
- test/unit/test_pre_parsers.py
- test/unit/test_sink.py
size: medium
* Refactoring the rule processor so alerts are sent to the alert processor (via sns) as they are processed.
* Prior to these changes, we would first iterator over all logs and apply the rule logic against them, caching any that matched a rule along the way. We would finally send them to the alert processor (one at a time) after all logs had been processed.
* These change will make this all happen sequentially and any logs that match a rule will get sent as we process (instead of caching and sending at the end).
* Will log a message on every 100 records processed from s3 so we can track progress.
* Adding some logic that will also try to estimate the number of records in the entire file during processing (we use a generator to avoid reading …
> [lambda][rule] processed logs will now be sent immediately to the alert processor

- .travis.yml
- stream_alert_cli/package.py
size: small
resolves: #79 
* Checking the `pip.main()` return code and logging error/exiting if anything other than 0 is encountered.
> [package] will log error and exit with code 1 if/when pip fails

- stream_alert/rule_processor/handler.py
Fixed bug in math when reporting on approximate number of records processed.
> [lambda][rule] order of operations bug in math when logging processed record count

- docs/source/requirements.txt
Search is broken again on ReadTheDocs.
(search for anything and click on a link)
Supposedly, this is now addressed via https://github.com/rtfd/readthedocs-sphinx-ext/pull/26
This PR removes version pinning to give it a try
> [streamalert] docs - remove requirements.txt

- stream_alert/rule_processor/parsers.py
cc: @jacknagz, @mime-frame 
This is v1 of optimizations to the json parser. I'm looking into more changes, but this is a fairly easy one with great improvements in speed. The change is as follows:
* Adding check for `envelope_keys` and if they are declared, the parser will validate that they exist before continuing to parse. If they are not declared, it will still attempt record extraction via `json_path` as usual.
* In most cases, `json_path` is used in conjunction with `envelope_keys` (meaning `envelope_keys` isn't _always_ present, but typically is). In instances where `envelope_keys` is not declared (in the case where there is no important information needed from the outer level keys), this code will not have any performance improvement. However, …
> [parsers] adding check for envelope_keys and validating if they exist

- stream_alert/rule_processor/parsers.py
* Fixing bug where an empty value for a key that is an `envelope_key` would cause `envelope_key` validation to fail in the json parser. Making this change so the code will now look if the _key_ exists, and not worry about what _value_ said key has.
> [parsers] fixing envelope_key value bug

- stream_alert/alert_processor/outputs.py
to @jacknagz 
* Adding some additional logging for pagerduty and slack http responses. Basically, if either of these fail to send we will report the error from both.
* The focus is on these two for now because they are the only two that really report problems well. 
* Phantom doesn't provide much context, aside from the potential `artifact already exists` message: https://my.phantom.us/2.1/docs/rest/artifacts.
* boto3 s3 `put_object` responses don't contain any error information: http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_object
* boto3 lambda `invoke` reposnes contain a `FunctionError` value but that doesn't seem to actually indicate _what_ the error was: http://boto3.readthedocs.io/en/latest/reference/services/lambda …
> [lambda][output] adding some additional logging for PagerDuty and slack

- stream_alert_cli/runner.py
to @jacknagz 
* Renaming secrets bucket back to the right name. This was changed to test catching a bucket not found error and properly report it.
> [cli] changing back a bucket name that was used to test a recent feature

- stream_alert/rule_processor/sink.py
to @jacknagz 
* Changing to using the cached SNS client instead of instantiating one inside of a loop every time we publish to sns. This should have been changed previously but was overlooked or overwritten.
* Also caching the topic upon instantiation instead of re-creating it every time.
> [lambda][rule] fixing up some overlooked code from a previous optimization change

- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/iam.tf
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_kinesis/main.tf
* Enable S3 versioning
* Cleanup tagging on Lambda/Kinesis resources for easier tracking
* Begin to use Terraform policy data resources over JSON strings (provides more reliability when running Terraform)
> S3 Versioning, Cleanup, and Tagging

- conf/logs.json
- stream_alert/rule_processor/parsers.py
- test/unit/conf/logs.json
- test/unit/stream_alert_rule_processor/test_json_parser.py
to @jacknagz , @mime-frame 
resolves: #166
size: small
* Nested json records that get extracted via `json_path` will now have `optional_top_level_keys` applied.
* Removing the need to call `update` on a schema to add the default value, and instead logging an error if the key does not exist in the schema. This informs the user that the `optional_top_level_keys` should also be declared as part of the `schema` in logs.json.
* A future PR is to come with a note added to the docs about the need for `optional_top_level_keys` to be declared in the schema.
> [parser] nested json records will now have optional keys applied

- stream_alert_cli/runner.py
- terraform/modules/tf_stream_alert/README.md
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert/sns.tf
- terraform/modules/tf_stream_alert/variables.tf
- variables.json
to: @austinbyers @ryandeivert 
size: medium
The primary purpose of this PR is to support the Alert Processor running from within an AWS VPC (Virtual Private Cloud).  The benefit of this change is that alerting logic will be able to reach into private services/resources behind a firewall or security groups in AWS cloud.  An example of this is an alert with Phantom as an output, or any other orchestration trigger as a result of a StreamAlert.
Along the way, I identified other small bugs with the CLI that I have also fixed.  
* Modify the `tf_stream_alert` Terraform module to support running the Alert Processor from within a VPC.
* Fix the `stream_alert_cli.py terraform status` command.
* Added an option to `stream_alert_cli.py terraform destroy` to allow …
> Support Alert Processor in VPC, Various Bug Fixes

- conf/outputs.json
- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/output_base.py
- test/scripts/autopep8.sh
- test/scripts/unit_tests.sh
- test/unit/conf/outputs.json
- test/unit/stream_alert_alert_processor/__init__.py
- test/unit/stream_alert_alert_processor/helpers.py
- test/unit/stream_alert_alert_processor/test_main.py
- test/unit/stream_alert_alert_processor/test_output_base.py
- test/unit/stream_alert_alert_processor/test_outputs.py
to @austinbyers, @jacknagz @mime-frame 
* Largely, unit tests for the alert processor
* Moving some functions in the alert processor to protected scope.
* Adding the `stream_alert.alert_processor` package to nosetests coverage.
* Alert processor tests are structured according the the corresponding file the tests are for. ie - `test/unit/stream_alert_alert_processor/test_main.py` is for testing the `stream_alert/alert_processor/main.py` file, and so on.
* The `helpers.py` file contains various helper functions imported from one or multiple `test_` files in the package.
> [tests] alert processor unit tests

- stream_alert/rule_processor/pre_parsers.py
- stream_alert_cli/test.py
to @jacknagz 
size: small
* s3 download statuses will now be logged as info statements instead of debug
* Adding code to suppress this output during test runs
* One change to code that caused pylint line too long warning.
> [lambda][rule] s3 downloads will now be logged as info statements

- rules/cloudtrail/cloudtrail_put_bucket_acl.py
- rules/cloudtrail/cloudtrail_put_object_acl.py
- rules/cloudtrail/cloudtrail_root_account.py
- test/integration/rules/cloudtrail_put_bucket_acl.json
- test/integration/rules/cloudtrail_put_object_acl.json
- test/integration/rules/cloudtrail_root_account.json
to: @jacknagz 
**What**
3 new Cloudtrail rules
1. Detect creation of insecure AWS S3 bucket ACLs 
2. Detect creation of insecure AWS S3 object ACLs
3. Detect human use of the `Root` account
See rule docblocks for details :)
**Why**
Real-word production quality rules to help others detect intrusions and insecure configurations!
**Testing**
`./test/scripts/rule_test.sh`
`(14/14)	Tests Passed`
> streamalert - cloudtrail rules - part deux

- .travis.yml
- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/output_base.py
- stream_alert/alert_processor/outputs.py
- stream_alert_cli.py
- stream_alert_cli/helpers.py
- stream_alert_cli/test.py
- test/integration/context
- test/unit/stream_alert_alert_processor/__init__.py
- test/unit/stream_alert_alert_processor/helpers.py
- test/unit/stream_alert_alert_processor/test_main.py
- test/unit/stream_alert_alert_processor/test_output_base.py
- test/unit/stream_alert_alert_processor/test_outputs.py
- test/unit/stream_alert_rule_processor/test_rules_engine.py
to @jacknagz 
* Adding option to `cli` to run rule test on a comma separated list of rules.
* New options is used like so: `python stream_alert_cli.py lambda test --processor rule --rule cloudtrail_put_bucket_acl,cloudtrail_put_object_acl`
* Updating the alert processor so it can yield back status results to the calling handler. Would like to make this more granular in the future.
* Removing an unused file (`context`)
* Migrating some helper functions from the unit testing framework to the cli package so they can be utilized across tests.
* The cli now supports running tests for the `alert` processor via: `python stream_alert_cli.py lambda test --processor alert`
* End-to-end testing is also available via: `python stream_alert_cli.py lambda test …
> [tests] alert processor testing

- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/output_base.py
to @jacknagz 
size: small
* Bug that caused logging to break with high throughput to PagerDuty
* The error occurs when attempting to send a large amount of consecutive alerts to PD.
* How the issue/fix was discovered
* PagerDuty would begin to return a 403 Forbidden Request error
* The HTTP response fp for the exception would return a weird 121 byte blob of binary data that could not be printed well.
* AWS's logging choked on printing this, throwing the following error: `'utf8' codec can't decode byte 0x8b in position 93: invalid start byte: UnicodeDecodeError`
* The change that fixes this is not reading/printing the error response data and instead just printing the url and error code being returned. It is still unclear why the response returned by …
> [lambda][alert] fixing bug that caused logging to break with pagerduty

- stream_alert_cli/config.py
- stream_alert_cli/helpers.py
- stream_alert_cli/outputs.py
- stream_alert_cli/package.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- stream_alert_cli/test.py
- test/unit/stream_alert_alert_processor/test_output_base.py
- test/unit/stream_alert_alert_processor/test_outputs.py
- test/unit/stream_alert_cli/test_terraform_generate.py
- test/unit/stream_alert_rule_processor/test_config.py
- test/unit/stream_alert_rule_processor/test_rules_engine.py
* Move `format_lambda_test_record` into the `cli.helpers` package: This is an effort to share this method across tests (for main/handler, which will come soon).  I also removed the nesting of helper methods within a `CLIHelpers` class since that paradigm wasn't being adopted.
* Modularize terraform_generate: All cluster generation was in one massive method before, this has been broken out into multiple methods for easier management.
* Unit testing: Adds initial unit tests to the terraform_generate code, there are more to add, they will come later.
* Moar unit testing: Get our coverage to 100% for the rule processor `config` module.
> JSON Templates Tests, S3 Events Support, and Moar Unit Tests

- .travis.yml
- requirements.txt
size small
The new [Ubuntu image](https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch) broke our Travis build, this PR fixes it.
* Add `sudo: required` to be more explicit 
* Ran `pip install coveralls` `pip install google-compute-engine` locally, followed by `pip freeze > requirements.txt` to update our dependencies
> Fix Travis

- rules/cloudtrail/cloudtrail_critical_api.py
- rules/cloudtrail/cloudtrail_put_bucket_acl.py
- rules/cloudtrail/cloudtrail_put_object_acl.py
- rules/cloudtrail/cloudtrail_root_account.py
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/sink.py
- stream_alert_cli.py
- stream_alert_cli/logger.py
- stream_alert_cli/runner.py
- stream_alert_cli/test.py
to @jacknagz 
* Adding a `-l/--live` option to the cli to allow for live alert dispatching to a specified cluster.
* ie - `$ python stream_alert_cli.py live-test --cluster prod --rule cloudtrail_put_object_acl`
* ~The "cluster" specified must exist in the `conf/clusters/` directory and should match the name exactly.~
* The `--cluster/-c` argument is required and must be followed by a "cluster" name.
* Available "clusters" to use for the `live-test` command are extracted from the `conf/clusters` directory (using the `<cluster>.json` files that exist there) and presented as `choices`.
* The cli package will now dynamically control if calls should be mocked out via a nested decorator, depending on if the `live` option is used.
* If the `--live` option is …
> [cli][test] live alert testing

- terraform/modules/tf_stream_alert_monitoring/main.tf
to: @jacknagz 
size: tiny
Because the CloudWatch alarm for errors computes the `Average`, the alarm looks like this:
`Threshold Crossed: 1 datapoint (1.0135819987837016E-4) was greater than the threshold (0.0).`
It makes more sense to count the total number (`Sum`) of errors instead. This is consistent with how StreamAlert counts Throttles.
> Errors statistic should be Sum, not Average

- stream_alert/alert_processor/outputs.py
- stream_alert_cli/test.py
- test/unit/stream_alert_cli/test_outputs.py
size: small
* Updating the boto3 lambda invocation to utilize a qualifier if one is provided in the output configuration.
* Updating lambda output/alert tests to go with above change.
* Patching a function to load the unit test outputs configuration during tests to avoid breaking tests with production configuration changes.
> [tests] testing fixes

- stream_alert/alert_processor/main.py
- test/unit/stream_alert_alert_processor/test_main.py
* Resolving an issue where lambda invocations of the alert processor function would fail because the return value of the main handler function is a `generator` object.
* It appears that AWS lambda expects a return value from the functions main handler that is json serializable. Using a `generator` to yield results to the caller function breaks serialization, and thus breaks invoking of the lambda function.
* This change will create a list that is instead extended with the results of the `run` function, which is then returned to the caller. `list` objects are, in fact, serializable into json 😂
> [lambda][alert] fixing bug in alert processor that cause lambda invocations to fail

- conf/outputs.json
- stream_alert/alert_processor/outputs.py
- terraform/modules/tf_stream_alert/iam.tf
to @austinbyers , @jacknagz 
size: small
* With some updates to properly invoke a lambda function with a designated qualifier, we broke terraform's configuration of said function.
* Previously, tf was creating a policy using the function name combined with the qualifier.
* This prevented proper invocation with a specific qualifier using `boto3`
* The change is to strip off the qualifier, and only use the function name when creating the policy.
* If a qualifier is not provided in the `outputs.json` configuration for this lambda, it does not break this logic. The interpolation will still extract the proper function name.
* Updating the example outputs.json configuration to include a qualifier along with the function name.
* Updating the message the lambda …
> [tf] tf change to properly configure lambda functions SA can invoke

- conf/logs.json
**What**
1) Fixed Carbonblack schemas that were denoting `timestamp` as a string, when in fact it's a float.
Example:
```
{
"cb_server": "...",
"cb_version": "...",
"computer_name": "...",
"feed_id": 123,
"feed_name": "...",
"from_feed_search": false,
"group": "...",
"hostname": "...",
"ioc_attr": {},
"ioc_type": "...",
"ioc_value": "...",
"md5": "...",
"os_type": "...",
"report_id": "...",
"report_score": 123,
"sensor_id": 123,
"server_name": "...",
"timestamp": 1497997455.021,
"type": "feed.ingress.hit.binary"
}
```
2) Fixed `carbonblack:ingress.event.netconn`, which occasionally does not have the `local_ip` and `local_port` keys 
3) Added the `feed.ingress.hit.binary` schema
**Testing**
`python stream_alert_cli.py lambda test …
> streamalert - carbonblack schema changes - round 1

- conf/logs.json
**What**
Support the log type `feed.synchronized` for CarbonBlack.
Example log:
```
{
"cb_server": "...",
"feed_id": 123,
"feed_name": "...",
"feed_update_time": "2017-06-21T08:18:03Z",
"scan_start_time": null,
"timestamp": 1498033084.509223,
"type": "feed.synchronized"
}
```
**Testing**
`python stream_alert_cli.py lambda test --processor all`
```
(14/14)	Rule Tests Passed
(50/50)	Alert Tests Passed
```
> streamalert - carbonblack - feed.synchronized

- stream_alert_cli/helpers.py
- stream_alert_cli/runner.py
to @jacknagz 
cc @airbnb/streamalert-maintainers , @zbuc
resolves: #200
size: small
* Catching `OSError` when trying to run a command that does not exist. Previously, `subprocess.CalledProcessError` would not catch this because commands must exit cleanly with an error code for that exception to be caught. Commands that do not exist do not exit with an error code, and thus this was missed.
* If the `terraform_check` fails to validate a TF install, we will now exit execution of the cli.
* Fixing formatting issue with prerequisite message printed during terraform check (space missing between "to" and "your").
> [cli][bug] fixing bug related terraform not being installed. resolves #200

- conf/clusters/prod.json
- docs/source/account.rst
- docs/source/clusters.rst
- stream_alert_cli.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/variables.tf
- test/unit/stream_alert_cli/test_terraform_generate.py
to: @ryandeivert (code) @mime-frame (docs)
cc: @airbnb/streamalert-maintainers @zbuc
size: medium
A combination of various bug fixes and feature additions.
* resolves #201 
* completes another task in #176
* Make sure we are starting with `"$LATEST"` as the AWS Lambda `current_version`.  This currently throws an error during the first deploy since the versions do not exist yet.
* Reset the Kinesis and Lambda settings to be a bare minimum.
* Enable `force_destroy` for prerequisite buckets.  This is makes destroying clusters easier, since this data is not of high value.
* Add a `stream_alert_cli.py terraform clean` command to simply remove any Terraform statefiles and other related files.  This is useful to have while troubleshooting issues with initialization.
* Fix a bug in the `init` …
> Bug Fixes (Initialization, AWS Perms, Config), CloudWatch Event Patterns, and More 

- conf/logs.json
to @jacknagz 
* Fixing small bug in `carbonblack:watchlist.hit.binary` declared schema. It turns out the `timestamp` stored at the root of the log is a `float`, but the `timestamp` stored within each entry of the `docs` list (inside the 'envelope') is a `string` value (ie: `2017-01-01T20:55:57.828Z`).
* Example:
```
{
"cb_server": "cbserver",
"cb_version": "6.1.0.170309.1140",
"docs": [
{
"cb_version": "524",
"comments": "comment",
"company_name": "Foobar Corp",
"copied_mod_len": "284904",
"digsig_issuer": "Foobar Inc",
"digsig_result": "Untrusted",
"digsig_result_code": "123123123123",
"digsig_subject": "Internal",
"endpoint": [
"1LAKDJ-F93J1"
],
"event_partition_id": [
"111111111111"
],
"facet_id": "0",
"file_desc": "Foobar Tech",
"file_version": …
```
> [logs] fixing small bug in log schema

- test/unit/stream_alert_rule_processor/test_sink.py
to @jacknagz 
* Updating the `test_sink.py` unit tests to better reflect the actual structure of data StreamAlert sends. Basically this just removes 'list' we were using in the 'default' key, and uses the map/dict to reflect what we do in production. Alerts are no longer sent in a list and are sent as a dictionary in the 'default' key.
> [tests] updating a unit test to better reflect actual data structure

- conf/logs.json
Osquery decorators are optional, so our `osquery` log schema should also make them optional
> [schemas] make osquery decorations an optional key

- stream_alert_cli.py
- stream_alert_cli/runner.py
size: medium
Refactor the StreamAlert CLI help messages for clarity and updated usage:
General help: 
```
$ python stream_alert_cli.py --help
usage: stream_alert_cli.py [command] [subcommand] [options]
StreamAlertCLI v0.2.1
Build, Deploy, Configure, and Test StreamAlert Infrastructure
Available Commands:
stream_alert_cli.py terraform               Manage StreamAlert infrastructure
stream_alert_cli.py output                  Configure new StreamAlert outputs
stream_alert_cli.py lambda                  Deploy, test, and rollback StreamAlert AWS Lambda functions
For additional details on the available commands, try:
stream_alert_cli.py [command] --help
positional arguments:
{output,live-test,lambda,terraform}
output              Define a …
```
> [cli] update CLI descriptions

- stream_alert_cli/package.py
size: small
With the updated folder structure in #210, we need to package in the folders to the `rule_processor` deployment package.
> [cli] package in the new helpers and matchers folders

- stream_alert/alert_processor/outputs.py
to @jacknagz 
* Fixing bug where `metadata` for a triggered rule was not being sent to s3 for storage along with the alert record itself.
> [lambda][alert] fixing bug where metadata for an alert was not being sent to s3

- stream_alert/rule_processor/handler.py
to @jacknagz 
* Removing a json dump to string of data that is already json. This made it difficult to copy logger output when an "invalid" log was printed, and required replacing a bunch of escape characters that were added during the json dump. The output can now be copied directly from CloudWatch logs for testing/adding new schemas without any manipulation.
> [lambda][rule] removing a json dump to string in logger output

- .travis.yml
- requirements.txt
to @jacknagz 
* Adding `sphinx-build` to travis so CI will fail if there are any warnings or errors when trying to build docs. This should help us avoid having to make massive fixes to docs in the future when updates are added.
> [ci] adding sphinx-build to CI to check for doc errors

- stream_alert/rule_processor/handler.py
to @jacknagz 
* Updating a logger call to lug incoming data after being pre-parsed instead of before. This should make troubleshooting a bit easier.
> [lambda][rule] logging incoming data after being pre-parsed instead of before

- conf/logs.json
@jacknagz 
@airbnb/streamalert-maintainers 
* osquery_status schema update to go with https://github.com/airbnb/streamalert/pull/209
> [schemas] make osquery_status decorations an optional key also

- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert/variables.tf
- test/unit/stream_alert_cli/test_terraform_generate.py
A current issue with per-cluster S3 Alert buckets is that a rule acting across multiple environments will throw a permissions error.  The reason is that a given Lambda function will try to send to another cluster's bucket, and no permission exists to allow that.
Move the creation of StreamAlerts buckets out of each cluster and into a single bucket per StreamAlert setup.
Also update unit tests accordingly.
Verified in a side account with two clusters.  Alerts were sending to the same bucket from multiple Lambda functions.
Before pulling this update and migrating to a unified bucket scheme, perform the following:
1. Copy all existing StreamAlerts to a temporary bucket.
2. Empty bucket/clear out old alerts.
3. Run `python …
> Consolidate StreamAlerts Buckets

- docs/source/conf-schemas.rst
* Clarify strict ordering only applies to the `csv` parser.
* Reiterate strict ordering in the CSV Parsing section.
> [docs] Clarify strict ordering in Schemas

- conf/logs.json
to @austinbyers , @jacknagz 
* Adding some additional carbonblack log schemas:
* `carbonblack:alert.status.updated`
* `carbonblack:alert.watchlist.hit.feedsearch.binary`
* `carbonblack:alert.watchlist.hit.ingress.process`
* `carbonblack:alert.watchlist.hit.query.process`
* `carbonblack:watchlist.storage.hit.binary`
* `carbonblack:watchlist.storage.hit.process`
* Updating some existing schemas with optional keys:
* `carbonblack:ingress.event.netconn`
* `carbonblack:ingress.event.procstart`
> [logs] adding some additional carbonblack log schemas

- requirements.txt
- stream_alert/athena_partition_refresh/main.py
- stream_alert_cli.py
- stream_alert_cli/config.py
- stream_alert_cli/package.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- stream_alert_cli/version.py
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert_athena/README.md
- terraform/modules/tf_stream_alert_athena/main.tf
- terraform/modules/tf_stream_alert_athena/variables.tf
- test/scripts/unit_tests.sh
- test/unit/helpers/aws_mocks.py
- test/unit/helpers/base.py
- test/unit/stream_alert_athena_partition_refresh/test_main.py
- test/unit/stream_alert_cli/test_config.py
- test/unit/stream_alert_cli/test_terraform_generate.py
- test/unit/stream_alert_cli/test_version.py
to: 
@ryandeivert (CLI and Misc)
@chunyong-lin (Terraform)
@austinbyers (Lambda Function)
cc: 
@airbnb/streamalert-maintainers 
As a follow up to #229 and #5, this pull request includes automation for configuring and operationalizing a StreamAlert Athena database.  Currently, this focuses on supporting the `alerts` table, with automatic partition refreshing to enable searching of alerts right after they occur.
This includes initial setup of the Athena configuration via the CLI, creation of the `streamalert` database and `alerts` table, and configuring automatic partition refreshes (via Lambda) when new data is written to the `prefix.streamalerts` bucket or others defined in the config.
* Create a new Lambda function (`<prefix>_streamalert_athena_partition_refresh`).
* Configure S3 events …
> Athena Partition Refresh

- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert_cli/test.py
to @jacknagz 
size: small
part of: #149 
* Running tests need more context to make debugging invalid test events easier (#149)
* Log messages previously printed in-line with tests when an error occurred during log classification. This was easily lost in the shuffle, especially with 100s of test events running.
* Initial change to log messages related logs that failed to classify at the end of all tests being run. These were previously printed as 'Invalid Data..' messages.
* The new message(s) will indicate two things:
* If required keys are missing
* If extra (unexpected) keys exist in the test log
* One caveat: a missing key message and an unexpected key message is printed in the event that there are misspelled keys in the log (ie: `recipientId` is …
> [cli][test] invalid logs will provide more context when running tests

- stream_alert_cli.py
- stream_alert_cli/runner.py
- stream_alert_cli/test.py
cc: @airbnb/streamalert-maintainers @VVMichaelSawyer 
resolves: #241 
size: small
Convert the `--processor` command line option type from a string to a list, which allows users to cherry pick which Lambda function is deployed.
This fixes a bug identified in #241 where the CLI would try to deploy a Lambda function that is optional (Athena Refresh).
Tested and verified by walking through the `$ python stream_alert_cli.py terraform init` workflow
> [cli] allow a list of lambda functions to be deployed

- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/metrics.py
- stream_alert/rule_processor/payload.py
- stream_alert/shared/__init__.py
- stream_alert/shared/metrics.py
- stream_alert_cli/package.py
- test/scripts/unit_tests.sh
- test/unit/stream_alert_rule_processor/test_classifier.py
- test/unit/stream_alert_rule_processor/test_handler.py
- test/unit/stream_alert_rule_processor/test_helpers.py
- test/unit/stream_alert_rule_processor/test_metrics.py
- test/unit/stream_alert_rule_processor/test_payload.py
- test/unit/stream_alert_shared/test_metrics.py
to @austinbyers , @jacknagz 
* Adding a metrics class to support publishing metrics to cloudwatch
* Including a few metrics for now, which will be added to later. Those include:
* Total records being processed
* Number of logs that failed to parse
* Number of alerts triggered
* S3 file download time (for latency visibility)
* Total number of records from S3 files
* Updating tests to cover metrics.
> [metrics] initial metrics support

- conf/logs.json
- docs/source/conf-schemas-examples.rst
- docs/source/conf-schemas.rst
- docs/source/rule-testing.rst
- stream_alert/rule_processor/parsers.py
- stream_alert/rule_processor/payload.py
- test/unit/conf/logs.json
- test/unit/stream_alert_rule_processor/test_parsers.py
to @jacknagz 
size: small
* Removing the `GzipJSONParser` class that was used for decompressing gzipped json data coming from CloudWatch flow logs via Kinesis.
* The decompression of this data will now immediately be attempted during the ingestion of Kinesis data, in: https://github.com/airbnb/streamalert/compare/ryandeivert-gzip-logging-fix?expand=1#diff-3938c84c6d412626570fb7d59e7a86daR317
* Updating all unit tests to conform to this new workflow.
* Doc updates to reflect changes.
> [lambda][rule] removing dependency on gzip json parser

- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_monitoring/main.tf
size: small
resolves #251, resoles #230 
* Fix CLI bug related to deploying all Lambda functions when the Athena function is not enabled
* Fix a bug in generating the s3_event Terraform module where input variables were left out
* Adds a retention policy for CloudWatch logs
* Adds CloudTrail log integrity
* Adjusts CloudWatch alarms to reduce FPs and more proactively alert on processing issues
If you are pulling this change in with existing clusters, you have to import the newly added CloudWatch log resource into your statefile.  You must do this for every cluster if you want to retain your old logfiles:
```
$ cd terraform
$ terraform import module.stream_alert_prod.aws_cloudwatch_log_group.alert_processor …
```
> CLI Bug Fixes and Terraform CloudTrail/CloudWatch Enhancements

- stream_alert_cli/runner.py
Fixes `stream_alert_cli.py configure prefix` to error only if the argument is *not* a string (and to check the config value)
Resolves: #256 
```
$ python stream_alert_cli.py configure prefix hello_world
StreamAlertCLI [ERROR]: Invalid prefix type, must be string
```
and `conf/global.json` is not modified.
```
$ python stream_alert_cli.py configure prefix hello_world
```
and `conf/global.json` is updated with the new prefix
> Fix 'stream_alert_cli.py configure prefix'

- test/unit/stream_alert_rule_processor/test_rules_engine.py
to @jacknagz 
size: small
* This fix clears out the private class properties of `__rules` and `__matchers` on `StreamRules` to allow tests to run in a proper state.
* If a user declared a matcher of `prod`, unit tests would break saying this matcher is already defined. The same would occur for userland rules defined with the same name as a unit test rule.
> [tests] fixing bug in tests that could cause conflicts with user matchers or rules

- stream_alert/athena_partition_refresh/main.py
- stream_alert_cli/config.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- terraform/modules/tf_stream_alert_athena/main.tf
- terraform/modules/tf_stream_alert_athena/variables.tf
- test/unit/stream_alert_athena_partition_refresh/test_main.py
to @jacknagz 
size: small
* Updating backoff logging handler to use name of function instead of function object which does not look nice in logs + updating tests
* Bug fix in cli terraform destroy command
* Fixing metrics variable name enforcing some dependencies that could cause a race condition
> [lambda][athena] athena minor tf updates and tf destroy fix

- stream_alert/rule_processor/classifier.py
- stream_alert/rule_processor/parsers.py
- stream_alert/shared/stats.py
- stream_alert_cli/logger.py
- stream_alert_cli/test.py
to @austinbyers, @jacknagz 
* Adding new `stats` module within shared to hold a timing decorator (and potentially more internal statistic related stuff in the future).
* classifier.classify_record, classifier._process_log_schemas now provide timing info
* JSON parser's parse_records now provides timing info
* This is enabled in debug mode only
`StreamAlertShared [DEBUG]: (module) stream_alert.rule_processor.classifier (method) _process_log_schemas (time): 0.7188ms`
* The decorator has no way to determine the **class** a function being timed is tied to. I even investigated hacky ways to try to determine this using the `inspect` package but came up short. I'm open to suggestions, but logging the module may be enough for our purposes for now.
> [shared][stats] adding timing decorator to log stats on methods

- stream_alert/rule_processor/__init__.py
- stream_alert/rule_processor/classifier.py
- stream_alert/rule_processor/parsers.py
size: small
Only run `json.dumps` and `LOGGER` messages when DEBUG is actually enabled.  This saves a lot of unnecessary processing in `info` mode.
Add a try catch when casting to a string for non ascii strings.  This was observed locally while testing.
> [core] conditionally log debug messages

- stream_alert_cli/outputs.py
- test/unit/stream_alert_cli/test_outputs.py
to @jacknagz 
* Fixing a bug that could cause the alert processor to run without a valid config by raising an exception if outputs.json fails to load
* Renaming a function to make its usage more clear (it was very confusing)
* Updating logger styling and updating unit test to go with above fix
> [bug] output bug fix to prevent using an empty config

- .travis.yml
- docs/source/account.rst
- manage.py
- stream_alert/alert_processor/outputs.py
- stream_alert/athena_partition_refresh/main.py
- stream_alert_cli/config.py
- stream_alert_cli/outputs.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- terraform/modules/tf_stream_alert_monitoring/main.tf
- tests/scripts/pylint.sh
- tests/unit/stream_alert_athena_partition_refresh/test_main.py
- tests/unit/stream_alert_cli/test_outputs.py
- tests/unit/stream_alert_cli/test_terraform_generate.py
to: @ryandeivert @chunyong-lin (both pls review all code)
size: medium
* Hive Add Partition support: Instead of searching an entire bucket for new partitions, add them based on S3 event notifications.  This works by parsing the S3 key using a regular expression to extract the YYYY-MM-DD-HH information from the key.  This is specific to Firehose and StreamAlert's S3 Output format
* Add an option for async Athena query execution: I plan on using this option in the future for long running processes.  To maintain state, I plan on using DynamoDB.  This iteration may come sooner if the `ADD PARTITION` command starts taking too long.
* Deduplicate partitions before issuing Athena queries.
* Add clearer log messages.
* UX improvements: Moar logger messages …
> Athena Refresh 2.0

- docs/source/rule-testing.rst
- manage.py
- stream_alert_cli/helpers.py
- stream_alert_cli/logger.py
- stream_alert_cli/runner.py
- stream_alert_cli/test.py
to @austinbyers for manage.py updates and various logging changes
to @jacknagz and @chunyong-lin for cli refactor
to @mime-frame: please confirm that log output examples below are sensible
size: medium
resolves: #149 
resolves: #154 
resolves: #245
contributes to: #276 
* Testing via `manage.py` now supports a `validate-schemas` command.
* An optional argument for this command is `--test-files` which accepts a space separated list of files (or, alternatively, rule names) to validate.
* For example: `python manage.py validate-schemas --test-files cloudtrail_put_bucket_acl`
* This command does not perform any actual rule engine operations and will simply attempt to 'classify' the record against the defined log schemas.
* All summary output is now printed through the logging object with …
> [cli][test] validation of schemas without writing a rule

- docs/source/outputs.rst
- stream_alert_cli/outputs.py
- tests/unit/stream_alert_cli/test_outputs.py
to @jacknagz 
* Raising an exception if credentials fail to encrypt with KMS. This used to allow execution to continue to the point of trying to upload an empty blob to S3, and then would fail with a different error. This helps differentiate failures.
* Updating unit tests for new exceptions being raised.
> [cli] raising exception if output creds could not be encrypted

- stream_alert/alert_processor/outputs.py
cc @airbnb/streamalert-maintainers , @fusionrace 
* Removing `StreamAlert Rule Triggered - ` prefix from container names in Phantom.
* Unit tests passing locally
> [outputs] changing phantom container name to be rule name

- terraform/modules/tf_stream_alert/iam.tf
* Include AWS Lambda function qualifier in InvokeFunction permission to resolve AccessDeniedExceptions seen in CloudWatch when invoking a function without its qualifier.
@austinbyers please add additional context about how you discovered and triaged this issue.
> [tf] quick fix for a AccessDeniedException introduced by AWS

- stream_alert/alert_processor/output_base.py
- stream_alert/alert_processor/outputs.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size: small
resolves: #287
* The current implementation of the phantom output class will create a new container for every single alert that fires. This results in one artifact per container relationship, where each rule would ideally have it's own container (full of alerts that fired for that rule). (See #287)
* This change performs a query using Phantom's api to filter on the name of the container.
* In conjunction with the change made in #286, this will now do a container lookup via the 'name' value which will be the name of the rule that triggered the alert and return the ID for the first matching container.
* If not container exists with the name of this rule, a new one will be created and that ID will be returned. The 'artifact' …
> [lambda][alert] phantom container lookup by rule name

- stream_alert/rule_processor/rules_engine.py
to @chunyong-lin 
* Adding logger info statement to log any rules that trigger.
* The statement will include the name of the rule, the log type, the entity and the service
> [lambda][rule] logging rules that trigger

- terraform/modules/tf_stream_alert/iam.tf
to @austinbyers  or @chunyong-lin 
This reverts commit b41eaffa8ee97ee50e83066334b323b408afa366.
Apparently AWS has reverted an internal change that required this change in #289 (or they're just toying with us).
> Revert "[tf] quick fix for a AccessDeniedException introduced by AWS"

- stream_alert_cli/test.py
to @chunyong-lin 
size: tiny
* Adding an extra urlopen side effect for Phantom tests to account for the urllib request use for container lookup.
> [lambda][output] fixing mocked result for phantom integration tests

- tests/integration/rules/cloudtrail_critical_api_calls.json
- tests/integration/rules/cloudtrail_put_bucket_acl.json
- tests/integration/rules/cloudtrail_put_object_acl.json
- tests/integration/rules/cloudtrail_root_account_usage.json
cc: @0xdabbad00
**Changes**
This updates the rule test descriptions to a Ruby-style test description instead of the confusing TP/FP pattern we initially started with.
This addresses https://github.com/airbnb/streamalert/issues/290
I also added some additional tests for existing rules.
**Testing**
```
StreamAlertCLI [INFO]: (17/17) Successful Tests
StreamAlertCLI [INFO]: (39/39) Alert Tests Passed
```
> [streamalert] - rule tests - make descriptions clearer

- conf/logs.json
Both `request_method` and `remote_address` are optional keys.
**Testing**
See internal
> streamalert - logs - update github unicorn schema

- conf/logs.json
**What**
Commit schema changes upstream:
- CarbonBlack schema updates
- Support for osquery snapshots
**Testing**
```
StreamAlertCLI [INFO]: (14/14) Successful Tests
StreamAlertCLI [INFO]: (30/30) Alert Tests Passed
```
> [streamalert] logs - update CB and osquery schemas

- conf/logs.json
- docs/source/conf-schemas-examples.rst
- docs/source/rules.rst
- matchers/sample.py
to: @ryandeivert or @austinbyers or @chunyong-lin 
**Details**
- Prefix osquery logs with `osquery:`, as we did with CB
- Fix outdated code comments in `matchers/sample.py`
**Testing**
```
StreamAlertCLI [INFO]: (17/17) Successful Tests
StreamAlertCLI [INFO]: (39/39) Alert Tests Passed
```
> streamalert - osquery prefix - plus outdated docs

- conf/logs.json
**Overview**
CarbonBlack has one of the most complicated, dynamic schemas 🥇 
This addresses known `Record does not match any defined schemas` ERRORs.
**Testing**
1) `python manage.py validate-schemas`
2) `python manage.py lambda test --processor all`
3) My eyes 👀
> streamalert - schema - carbonblack - fixes

- conf/logs.json
**Overview**
This PR addresses the fact that AWS has VPC flow logs that aren't strongly typed and can result in `Record does not match any defined schemas` ERRORs.
In most instances, `protocol`, `srcport`, etc are integers.
However, for the `NODATA` case (see http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/flow-logs.html), this doesn't hold true:
```
{
"messageType": "DATA_MESSAGE",
"owner": "...",
"logGroup": "...",
"logStream": "...",
"subscriptionFilters": [
"..."
],
"logEvents": [
{
"id": "...",
"timestamp": 123,
"message": "...",
"extractedFields": {
"eni": "...",
"destination": "-",
"windowstart": "12345",
"source": "-",
"flowlogstatus": "NODATA",
"version": "2",
"packets": "-",
"protocol": "-",
"bytes": "-",
"srcport": …
```
> streamalert - schemas - vpc flow logs - address NODATA case

- stream_alert_cli/logger.py
**What**
- Remove the annoying `StreamAlert [INFO]: Rule [...] triggered an alert on log type [...] from entity '..' in service '..'` output when doing local testing of rules.
- This information is already captured in the `[trigger=...]` output
**Result**
```
cloudtrail_put_object_acl
[Pass]  [trigger=1]                   rule      (s3): Storing an S3 object with an `AuthenticatedUsers` permission will create an alert.
[Pass]                                alert     (pagerduty): sending alert to 'sample-integration'
[Pass]                                alert     (aws-s3): sending alert to 'sample-bucket'
[Pass]                                alert     (slack): sending alert to 'sample-channel'
[Pass]  [trigger=1]                   rule      (s3): Storing an S3 object …
```
> streamalert - local testing - remove INFO of triggers

- conf/types.json
**What**
CB supports both `cmdline` and `command_line`
`carbonblack:feed.query.hit.process` -> `cmdline`
& 
`carbonblack:ingress.event.procstart` -> `command_line`
> streamalert - types - wrong command value for CB

- conf/clusters/prod.json
- conf/global.json
- docs/source/athena-deploy.rst
- manage.py
- stream_alert/rule_processor/handler.py
- stream_alert/shared/metrics.py
- stream_alert_cli/config.py
- stream_alert_cli/helpers.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform_generate.py
- stream_alert_cli/test.py
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert/variables.tf
- tests/unit/stream_alert_cli/test_terraform_generate.py
to @austinbyers or @chunyong-lin 
size: large
* Context on recent developments:
* StreamAlert now has support for metric logging with the merge of https://github.com/airbnb/streamalert/pull/282 ([metrics] v2 of metrics support using metric filters).
* The usage of filter patterns for metrics allows us to cheaply track whatever sort of metric we want to by simply logging certain messages to logger.
* Adding a new metric to be tracked involves adding it to the `stream_alert/shared/metrics.py` package to be used throughout the project.
* Any predefined metric can now have alarms associated with it to allow for notifications if something unexpected is occurring.
* For instance, if the number of `FailedParses` (aka incoming logs that do not match a defined …
> [cli][metrics] metric alarms configurable through the cli

- conf/logs.json
size: small
* After seeing an incoming `feed.query.hit.process` log that has a `interface_ip` key within `docs` entries, I've updated the `carbonblack:feed.query.hit.process` schema to have `interface_ip` as an optional top level key
> [logs] updating `carbonblack:feed.query.hit.process` schema

- conf/logs.json
Details: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/flow-logs.html:
- 3 possible values of OK, NODATA or SKIPDATA for `flowlogstatus`
- For the latter 2, the schema accounts for '-' vs. integers
This updates all 3 schemas to use `log_patterns`
**Testing**
```
...
python manage.py validate-schemas
```
> streamalert - logs - vpc flow - flowlogstatus update

- stream_alert/alert_processor/main.py
- stream_alert/rule_processor/payload.py
- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_payload.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to @ryandeivert @mime-frame 
size: tiny
contributes to: #304 
Remove `log_source` constrain which means `logs` keyword is optional when we define a rule if `datatypes` keyword present. Otherwise `logs` keyword is required. 
Apply Data Normalization feature to a rule, we can define a rule in this format
```
from helpers.base import fetch_values_by_datatype
@rule(datatypes=['command'])
def alert_suspicious_wget(rec):
results = fetch_values_by_datatype(rec, 'command')
for result in results:
if fnmatch(result, "wget *"):
return true
return false
```
* Integration test is passed, it covers three cases
* `logs` is present, `datatypes` is not
* `logs` is present, `datatypes` is
* `logs` is not present, `datatypes` is
* Unit test is passed, and it covers four …
> [Data Normalization] Make `logs` optional when `datatypes` is defined

- stream_alert/shared/metrics.py
size: small
* I discovered a bug where the `TotalProcessedSize` metric was using the wrong default lookup value. This fixes that.
> [metrics] fixing bug in total processed size metric default value

- conf/logs.json
* Found that osquery snapshot logs can sometimes contain a top level `"epoch"` key - this change accounts for that.
> [logs] adding an optional key of "epoch" to osquery snapshot logs

- conf/logs.json
* Updating the `carbonblack:watchlist.hit.process` to contain some additional optional top level keys for known feeds.
> [logs] adding some optional top level keys to "carbonblack:watchlist.hit.process"

- conf/logs.json
* Observed an optional top level key for log type `carbonblack:alert.watchlist.hit.feedsearch.binary` of `other_hostnames`. Updating schema to make this key optional.
> "other_hostnames" optional in "carbonblack:alert.watchlist.hit.feedsearch.binary"

- stream_alert_cli/package.py
to: @jacknagz
size: tiny
This bug will break when uploading lambda function to lambda function if user has no `threat_intel` directory created even Threat Intel feature is disabled.
Add a condition to include `threat_intel` directory in `RuleProcessorPackage`.
Deploy rule processor and alert processor in AWS testing account. It was passed.
> [cli][bug] Add a condition to include `threat_intel` directory

- stream_alert/rule_processor/handler.py
- stream_alert_cli/terraform/_common.py
- stream_alert_cli/terraform/generate.py
- tests/unit/stream_alert_cli/terraform/test_common.py
- tests/unit/stream_alert_rule_processor/test_handler.py
- tests/unit/stream_alert_rule_processor/test_helpers.py
size: medium
references: #5, #280, #320 
Part 3 completes the Lambda and CLI development necessary to send logs directly to Firehose.  At a high level, it accomplishes the following:
* Strip special characters from record keys: This enables records to be compliant with loading data into Hive.
* Payload size checks: Ensure that the max payload size for Firehose is not surpassed.
* Disable log types: For whatever reason, if a user does not want to send a top level log type (`cloudwatch` for example), it can be added to the config.  This will also remove the Firehose Delivery Stream to keep costs down
Deployed in a test AWS account to verify end to end workflows
> Lambda to Firehose: Part 3

- rules/community/duo_authentication/duo_anonymous_ip_failure.py
- rules/community/duo_authentication/duo_fraud.py
- stream_alert_cli/helpers.py
- tests/integration/rules/duo_anonymous_ip_failure.json
- tests/integration/rules/duo_fraud.json
- tests/integration/templates/stream_alert_app.json
to @jacknagz , @fusionrace 
* Adding two new example rules for Duo:
* `duo_anonymous_ip_failure`: Alerts on duo auth logs that are marked as failure due to anonymous IP
* `duo_fraud`: Alerts on duo auth logs that are marked as fraudulent by the end user
* Updating the testing framework to have support for the new `stream_alert_app` test records.
> [apps][duo_auth] adding duo auth example rules and updating tests

- app_integrations/config.py
- stream_alert_cli/version.py
- terraform/modules/tf_stream_alert_app/main.tf
to @jacknagz 
size: small
* Fixing terraform map lookup bug
* Fixing bug where json loaded string values in dict (needed for authentication) are of type unicode and needed to be cast to type string.
* Lambda versioning for the stream alert apps function will return if there is nothing to do for a given cluster.
> [apps] bug fixes discovered during deploy

- manage.py
- stream_alert/athena_partition_refresh/main.py
- stream_alert/rule_processor/handler.py
- stream_alert_cli/runner.py
- tests/unit/stream_alert_athena_partition_refresh/test_main.py
- tests/unit/stream_alert_rule_processor/test_handler.py
to: @austinbyers @ryandeivert 
size: medium
resolves: #5 
StreamAlert currently supports historical searching of `alerts` buckets only.  This PR adds support for historical search of data sent via Kinesis Firehose.
* Automatically add partitions for Athena data tables
* Support data Athena table creation from the CLI
* Convert StreamAlert schemas into Hive schemas
* All testing done in a side AWS account
> Athena Data Bucket Support

- app_integrations/apps/app_base.py
- app_integrations/apps/duo.py
- app_integrations/batcher.py
- app_integrations/config.py
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_config.py
to @jacknagz 
cc @airbnb/streamalert-maintainers , @javuto 
size: small
* In order to prevent sensitive auth info from making its way into the log output when `debug` mode is enabled, I've added a method for masking the sensitive information with `*` values before it gets printed.
* This is only used in one place and returns a copy of the origin dict to avoid altering the values needed by the function.
* Adding debug log statement that will periodically log how much time (in ms) the Lambda function has remaining. This could be useful for troubleshooting future issues (ie: timeouts).
* Adding info log statement to print when batch sending of logs is finished.
* Adding debug log statement to print if there are more logs to poll for duo_(auth|admin).
* Updating unit tests to verify the …
> [apps] adding method to mask authentication info before logging to output

- conf/logs.json
- rules/community/duo_authentication/duo_anonymous_ip_failure.py
- rules/community/duo_authentication/duo_fraud.py
to: @jacknagz 
cc: @ashmere 
**Background**
There are 3 osquery result formats, we weren't supporting one of them (`batch`). Now we are
https://github.com/facebook/osquery/blob/master/docs/wiki/deployment/logging.md#schedule-results
**Changes**
- Add osquery's `batch` schema: https://github.com/facebook/osquery/blob/master/docs/wiki/deployment/logging.md#batch-format
- Add optional `counter` key
- Small other fix: Add reference docs for DUO alerts
**Testing**
```
StreamAlertCLI [INFO]: (21/21) Successful Tests
StreamAlertCLI [INFO]: (45/45) Alert Tests Passed
```
> streamalert - add osquery 'batch' schema, add counter key, small nits

- stream_alert_cli/logger.py
to @jacknagz 
* Adding additional log output suppression for `Successfully sent * messages to Firehose*` during tests to list of suppressed messages.
* Updating the filter function to use `fnmatch` to make it a little more adaptable.
> [cli] adding suppression for firehose log messages

- terraform/modules/tf_stream_alert_monitoring/main.tf
size: tiny
Under normal operation, there may be occasional small spikes in Kinesis `WriteProvisionedThroughputExceeded` errors. We don't need to alarm for only one or two sporadic errors; these will be retried.
The new settings mean: "Alert if there are more than 3 errors per minute for 2 minutes in a row"
> Increase Kinesis write throughput exceeded alarm threshold

- app_integrations/apps/app_base.py
- app_integrations/apps/duo.py
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_apps/test_duo.py
size: small
* To make the app class interface easier to subclass/utilize, I've moved the functionality
for performing GET requests against an endpoint to within the base app class.
* Updating tests to account for the migrated code.
* Adding debug statement to log when a request occurs.
> [apps] migrating requests logic to base class

- conf/sources.json
- helpers/base.py
- matchers/matchers.py
- rules/community/github/github_disable_org_two_factor_requirement.py
- tests/integration/rules/github_disable_org_two_factor_requirement.json
**Changes**
- Add GHE to `sources.json`
- Add GHE helper functions to `helpers/base.py`
- Rename `matchers/sample.py` → `matchers/matchers.py`,  remove the sample matcher (never used), add the GHE matcher
- Add the first open source rule (disabling 2FA) with it's scrubbed test case
**Testing**
```
StreamAlertCLI [INFO]: (23/23) Successful Tests
StreamAlertCLI [INFO]: (48/48) Alert Tests Passed
```
**Followup**
I'll create another PR (non-blocking) with additional rules
> StreamAlert - Rules - Github - Part I

- rules/community/github/github_user_promotion_to_site_admin.py
- tests/integration/rules/github_user_promotion_to_site_admin.json
to: @ryandeivert (Tuesday morning)
**What**
Open source rule that alerts whenever a GHE user is promoted to a site administrator.
**Testing**
Tests added, and passing:
```
StreamAlertCLI [INFO]: (25/25) Successful Tests
StreamAlertCLI [INFO]: (51/51) Alert Tests Passed
```
> Rules - Github - Part Two

- conf/logs.json
size: tiny
* Cloudwatch event account IDs should be loaded as strings, not integers (for Athena)
* Add an optional key to one of the CB schemas
> [schemas] update cloudwatch and cb schemas

- conf/lambda.json
- stream_alert/rule_processor/handler.py
- stream_alert/shared/backoff_handlers.py
size: small
* Add `backoff` as the list of dependencies for the `rule_processor`
* Copies the backoff handlers into shared to be used by the Athena function (soon)
* Wraps the firehose request helper with a backoff decorator
Deployed the rule processor in a test account, verified logs are sending via Firehose
> [lambda] add backoff to firehose PutRecordBatch requests

- stream_alert/rule_processor/handler.py
- stream_alert/shared/backoff_handlers.py
- tests/unit/stream_alert_rule_processor/test_handler.py
size: medium
Currently, Firehose will not throw an exception if any of the records fail in the [PutRecordBatch](http://boto3.readthedocs.io/en/latest/reference/services/firehose.html#Firehose.Client.put_record_batch) request.
It will however return details in the response of the number of failed records.  This change allows for clearer diagnosis of Firehose operations.
I also modified the Firehose logger messages for clarity/consistency/usefulness
All tests performed in a StreamAlert cluster in a staging AWS account
> [lambda] add a second layer of backoff to firehose

- conf/logs.json
to: @jacknagz 
**What**
This is a stop gap solution while we address the issue/bug of type-checking being performed after a schema has been chosen (https://github.com/airbnb/streamalert/issues/353).
This issue was reported by Scott: https://streamalert.slack.com/archives/C3BHE2Z0S/p1507134986000135
I merged the 3 schemas into 1 by removing `log_patterns` and making keys that could be an integer or a string, a string.
**Note**
The PR looks like garbage, so I suggest viewing in Raw or just knowing that the final schema is the following:
```
"cloudwatch:flow_logs": {
"schema": {
"protocol": "string",
"source": "string",
"destination": "string",
"srcport": "string",
"destport": "string",
"action": "string",
"packets": "string",
"bytes": "string",
"windowstart": "integer",
"windowend": …
```
> streamalert - flow logs - one schema

- .coveragerc
The code coverage plugin `coverage` fixed an issue after the version `4.1` and it no longer shows the lines that are missing from unit tests by default. This information is rather helpful when writing unit tests because shows which parts of your code still need some testing. The parameter `show_missing` brings back the missing column, for code coverage.
Running the unit tests it shows a new column with the actual missing lines from the tests:
```
...
Name                                            Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------
app_integrations.py                                13      0   100%
app_integrations/apps.py …
```
> [tests] Show missing lines in unit tests

- .github/CONTRIBUTING.rst
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
size: small
Add an issue/pr template to this repo.  Also move the CONTRIBUTING.rst file into the `.github` directory per [Github suggestions](https://github.com/blog/2111-issue-and-pull-request-templates).
> [templates] PR and issue templates, and move contributing

- stream_alert_cli/helpers.py
- stream_alert_cli/test.py
size small
When running `manage.py live-test`, the firehose mock was not being applied.  This change ensures it's mocked.
> [cli tests] mock kinesis on live-test

- stream_alert/rule_processor/classifier.py
- tests/unit/stream_alert_rule_processor/test_classifier.py
size: small
* An issue was identified where lists/dicts trying to cast as float/int would throw TypeErrors
* This fixes the issue by catching `TypeError` for `integer` and `float` conversions
* Adds an additional unit test for reproducing the error
* Unit tested
* Pylinted
> [core] classifier list/dict type casting fix

- conf/types.json
**Changes**
This adds the fields from the DUO schemas that map to CEF fields that are compared against threat intelligence.
**Testing**
```
StreamAlertCLI [INFO]: (21/21) Successful Tests
StreamAlertCLI [INFO]: (45/45) Alert Tests Passed
```
**Things to reason about as the reviewer**
1) Can/should I just specifically reference `duo:authentication` vs. `duo`, since `duo:administrator` doesn't contain either of the fields that map to threat intel?
2) What's the best way to test changes to this conf file? I'm not sure what I did for testing is good enough.
> streamalert - threat intel - duo

- stream_alert_cli/runner.py
size: small
resolves: N/A
Creating Athena tables via the CLI requires conversion of StreamAlert schemas to Hive DDL statements.  To accommodate schemas with envelope keys, additional changes were necessary.
* Support StreamAlert envelope keys in Hive CREATE TABLE commands
* Tested by running the following command in a staging AWS account:
```
python manage.py athena create-table --refresh_type add_hive_partition \ 
--bucket <my-test-prefix>.streamalert.data \
--table_name cloudwatch_flow_logs \ 
--type data
```
> [cli] support athena table creation with envelope keys

- conf/logs.json
- stream_alert/rule_processor/handler.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform/_common.py
to: @mime-frame @ryandeivert 
cc:  @airbnb/streamalert-maintainers
size: small
Several bug fixes identified across CLI and schemas.
* Fix a bug in the `cloudwatch:events` schema.  Resources is not a map.
* Add more backoff attempts to the Firehose backoff logic
* Fix bugs in the Athena table creation code
* Sort log types when passing into the Terraform module for Firehose
Deployed in a staging account
> CLI, Athena, CloudWatch Schema fixes

- docs/source/rule-testing.rst
size: small
resolves N/A
* Updates to the documentation to go with #368 
* Describes the new structure of test events
* Includes information about the new required fields
* Updated example output to reflect current example rules
* Includes `stream_alert_app` as an acceptable `service` option
* New example to show the usage of `python manage.py lambda test --processor rule --test-files`
* ` tests/scripts/test_the_docs.sh `
> [docs] updates to go with #368

- app_integrations/apps/duo.py
- tests/unit/app_integrations/test_apps/test_duo.py
size: small
resolves N/A
* It's possible that the response from Duo's Admin API can contain 0 logs. This verifies the response contains logs before continuing.
* Check if the list of logs is not empty before trying to extract a timestamp value/return logs.
* Added unit test to verify effectiveness.
> [bug][apps][duo] adding a check to make sure the response was not empty

- terraform/modules/tf_stream_alert_app/main.tf
to: @jacknagz 
size: small
resolves N/A
* Prior to v0.1.0 of Terraform, there was not support for overwriting an `aws_ssm_parameter` resource with a new value. We now use a newer version that supports this, so this is to enable config overwriting for apps.
* Un-commenting the previously commented out `overwrite = true` property for the apps config stored in ssm.
* This is necessary to update the config from the cli with new values (ie: when rate is changed).
* Deployed a new rate with this change.
> [tf][apps] un-commenting `overwrite` option in ssm param

- helpers/base.py
- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to: @ryandeivert @javuto 
size: small
solves: #351
Context for the change
* If insert `normalized_types` to the original record, it will prevent other rules which have no datatypes parameters to work correctly.
* Create a local variable to store a copy of the record and pass it to alert if necessary.
* Unit Test
* Create unit test case to reproduce the issue.
* Apply fix and rerun unit test is passed. 
* Rule Test
* Create local testing rules and rules test is passed.
> [Data Normalization][Bug] Insert normalized types to a copy of record

- conf/sources.json
- rules/community/duo_administrator/duo_bypass_code_create_non_auto_generated.py
- rules/community/duo_administrator/duo_bypass_code_create_non_expiring.py
- rules/community/duo_administrator/duo_bypass_code_create_unlimited_use.py
- tests/integration/rules/duo/duo_bypass_code_create_non_auto_generated.json
- tests/integration/rules/duo/duo_bypass_code_create_non_expiring.json
- tests/integration/rules/duo/duo_bypass_code_create_unlimited_use.json
size: small
* 3 new rules for DUO admin logs that are centered around the creation of bypass codes.
* 3 new rules
* Associated tests
```
StreamAlertCLI [INFO]: (31/31) Successful Tests
StreamAlertCLI [INFO]: (60/60) Alert Tests Passed
```
> streamalert - rules - duo - bypass codes

- helpers/base.py
- rules/community/cloudtrail/cloudtrail_security_group_ingress_anywhere.py
- tests/integration/rules/cloudtrail/cloudtrail_security_group_ingress_anywhere.json
- tests/integration/rules/cloudtrail_security_group_ingress_anywhere.json
size: small
Alerts on Security Groups that allow anyone on the interwebs to touch your EC2 instance(s).
- Helper function called `select_key`
- Rule called `cloudtrail_security_group_ingress_anywhere`
- Tests
```
$ python manage.py lambda test --processor rule --test-files cloudtrail_security_group_ingress_anywhere
cloudtrail_security_group_ingress_anywhere
[Pass]  [trigger=1]                   rule      (kinesis): A Security Group that allows ingress from anywhere on the internet should create an alert.
[Pass]  [trigger=0]                   rule      (kinesis): A Security Group that allows ingress from an RFC1918 IP should not create …
```
> streamalert - cloudtrail - security groups - ingress

- stream_alert_cli/test.py
size: small
resolves N/A
* Observed bug when a log was defined in a test event without having a corresponding schema in logs.json:
```
...
File ".../streamalert/stream_alert_cli/test.py", line 773, in run_tests
validate_schemas):
File ".../streamalert/stream_alert_cli/test.py", line 147, in test_processor
yield self._run_rule_tests(name, test_event, formatted_record, print_header)
File ".../streamalert/stream_alert_cli/test.py", line 268, in _run_rule_tests
message = self.analyze_record_delta(file_name, test_event)
File ".../streamalert/stream_alert_cli/test.py", line 448, in analyze_record_delta
config_log_info = self.cli_config['logs'][log_type]
KeyError: u'type_of_log'
...
```
* Returning after the check to see if the logs exists …
> [bug][cli] returning after logging error if log not declared

- stream_alert_cli/test.py
to: @jacknagz 
size: small
resolves N/A
* Observed bug where header line would not be properly printed every time a file was tested.
* Will no longer utilize the index of the records to determine if the header line should be printed and just switched to toggling a boolean instead.
* Prior to fix, the following could occur:
```
[Pass]  [trigger=1]                   rule ......
```
* This fix now does:
```
cloudtrail_put_bucket_acl
[Pass]  [trigger=1]                   rule ......
```
> [bug][cli] fixing bug that caused header line to not be printed

- rules/community/cloudtrail/cloudtrail_network_acl_ingress_anywhere.py
- tests/integration/rules/cloudtrail/cloudtrail_network_acl_ingress_anywhere.json
size: small
* Alert whenever a NACL exposes resources to the internet
* Complimentary to the existing SG rule
* New rule
* New tests
```
StreamAlertCLI [INFO]: (35/35) Successful Tests
StreamAlertCLI [INFO]: (66/66) Alert Tests Passed
```
> streamalert - rules - cloudtrail - network acl - ingress

- conf/logs.json
size: small|medium|large
* Observed parse failure with `carbonblack:feed.storage.hit.binary`
* Adding optional `internal_name` key to schema.
> [schema] adding opt key to carbonblack:feed.storage.hit.binary

- .pylintrc
- docs/source/conf-schemas.rst
- docs/source/firehose.rst
- stream_alert/rule_processor/parsers.py
- stream_alert_cli/terraform/generate.py
- tests/unit/conf/logs.json
- tests/unit/stream_alert_rule_processor/test_parsers.py
size: medium
When using forwarders such as `fluentd`, `logstash`, or `rsyslog`, log data may be wrapped with additional context keys:
```
{
"collector": "my-app-1",
"date-collected": "Oct 12, 2017",
"@timestamp": "1507845487",
"data": "<0> program[pid]: {"actual": "data is here"}
}
```
In order to get to the actual payload to apply rules against, helper functions are currently needed.  
This PR adds functionality to the `json` parser to parse JSON string payloads from wrapped keys.
Usage:
Example schema per the data above:
```
"json:regex_key_with_envelope": {
"schema": {
"actual": "string"                    # the schema of the nested data
},
"parser": "json",
"configuration": {
"envelope_keys": {
"collector": "string", …
```
> Nested JSON Support

- conf/sources.json
- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to: @mime-frame or @ryandeivert 
size: small
resolves #365
Changing rule parameter `datatypes` (it is a list) to an *OR* operation from *AND* operation.
* When it is a *AND* operation, it requires all the datatypes in the list should be defined in `conf/types.json` for all the log sources expected to be analyzed. 
* When it is *OR* operation, it will not has such constraint.
Please refer to issue #365 for more details. 
* Remove method `validate_datatypes` from Rule Processor;
* Add checking to skip if CEF datatype is not defined for a log source, but still analyze log if other CEF datatypes in `datatype` list are defined. 
* Clean up the unconecessry code.
* Unit Test
* Test case `test_match_types` catch this change, and updated its assertion.
* Rule …
> [bug][data normalization] Improve 'datatypes' checking.

- stream_alert_cli/test.py
to: @jacknagz 
cc: @airbnb/streamalert-maintainers, @fusionrace 
size: small
resolves #382 
* Recent changes to the testing framework altered the order in which output from tests would be presented to the user. Previously, a single directory was used to house all of the test events. Now, test events can be organized into subfolders. The logic used to store references to files is unordered, and thus could cause std out to show a different order each time tests are ran.
* Test output will now be sorted alphabetically based on filename.
* Ran `python manage.py lambda test --processor rule` before the change and observed std out - names were **not** alphabetically ordered.
* Ran `python manage.py lambda test --processor rule` after the change and observed std out - names are now …
> [cli][test] output from tests will now be sorted on file name

- conf/logs.json
size: small
resolves N/A
* Adding optional top level keys `carbonblack:feed.storage.hit.binary` log schema
* Added temporary test event and ran `python manage.py lambda test --processor rule`
> [schema] adding optionals to feed.storage.hit.binary

- conf/types.json
size: small
A new integration app for OneLogin events was just added ([here](https://github.com/airbnb/streamalert/pull/355)) and those events have a new number of fields that can be used to extract data, using data normalization. See all the events fields [here](https://developers.onelogin.com/api-docs/1/events/get-events).
* Adding `ipaddr` as `sourceAddress`.
* Adding `actor_user_name` and `user_name` as `userName`.
I am not sure there is a way to test this, without a rule already in place.
> [data normalization] Adding for OneLogin events

- app_integrations/apps/app_base.py
- app_integrations/apps/onelogin.py
- app_integrations/config.py
- tests/unit/app_integrations/test_config.py
- tests/unit/app_integrations/test_helpers.py
to: @javuto 
size: small
resolves N/A
Different services utilize different date formats (duo=unix epoch, gsuite=rfc 3339). Instead of relying on each subclass to implement the conversion properly, the subclass should just have to provide the **format** while the base class can handle the actual conversion.
* Adding support for converting the initial timestamp from a simple unix epoch to a formatted date, depending on the date format returned by the subclass.
* The default will be the unix epoch if no format is provided.
* This method is defined as a `classmethod` as opposed to an `abstractmethod` because it is dependent upon the service and may not always be required.
* Adding ability to get the app *class* without instantiating it with a config
* …
> [apps] handle app date formatting in config

- helpers/base.py
- tests/unit/stream_alert_rule_processor/test_rule_helpers.py
size: small
resolves #385 
This bug was discovered during rule testings. It is case-sensitive while comparing record data against IOCs from IOC files. In the use case that fileHash in a record is in upper cases, however, the IOCs from IOC files maybe in lower cases, it will never have a match. 
This PR implements IOC comparison with case-insensitive and condition that users should have known if IOCs in IOC files are lowercase or uppercase.
* Add `lowercase_ioc` flag to helper function `is_ioc`.
* Add unit test cases. 
* Fix another bug that `rec['streamalert:ioc']` should be a list.
* Unit testing is passed
```
```
* Rule testing
* Add a local testing rule, and it is passed.
> [bug][threat intel] IOC matching with string case insensitive.

- rules/community/onelogin/onelogin_events_assumed_role.py
- Update references to explain what assuming a role/user means
- add author attribution
- remove empty playbook
size: small
> streamalert - rules - onelogin - update references

- tests/unit/stream_alert_athena_partition_refresh/test_main.py
- tests/unit/stream_alert_rule_processor/test_handler.py
to: @jacknagz, @mime-frame 
size: small
resolves N/A
Unit tests are getting very slow and take 86+ seconds to run
* Patching the amount of retries for backoff for firehose and sending max_tries=1 to athena get_messages.
* These changes bring unit test runs down from **86+ seconds to 3.2 seconds**
Unit tests pass.
> [tests] tweaking some unit test to speed up local tests/ci

- AUTHORS.rst
- docs/source/conf-schemas.rst
- requirements.txt
- setup.cfg
- stream_alert/rule_processor/parsers.py
- tests/unit/conf/logs.json
size: smalll
https://github.com/airbnb/streamalert/pull/387 introduced a performance hit when applying default values to envelope keys implicitly.  This change adds an explicit option to the `JSON` parser to prevent this from occuring
* Adds a parser option for optional_envelope_keys, which is needed when using json_regex_key
* Also adds `yapf`, updates AUTHORs, and docs
Unit tested
> Optional Envelope Keys

- docs/source/app-configuration.rst
- manage.py
- stream_alert_cli/test.py
size: small
resolves N/A
Previous changes to the CLI updated the `manage.py lambda deploy` and `rollback` commands to use a list of functions passed to the `--processor` arg. This PR updates the `test` command and also updates docs to go with previous changes.
* Updating the `manage.py lambda test` command to support multiple args.
* Updating docs to depict the usage of CLI `--processor` flag which now accepts a list of functions to test/deploy/rollback.
* The previous method of using multiple `--processor` flags is no longer supported and will result in only the *last* `--processor` flag having any affect.
Ran tests with various options to ensure the proper behavior occurs.
> [cli][docs] adding doc updates to reflect the --processor cli arg changes

- stream_alert_cli/test.py
- tests/integration/rules/duo/duo_bypass_code_create_non_auto_generated.json
- tests/integration/rules/duo/duo_bypass_code_create_unlimited_use.json
to: @jacknagz or @chunyong-lin 
cc: @airbnb/streamalert-maintainers, @fusionrace 
size: small
resolves #397 
See #397 
* Fixing bug for test events that should not trigger rules were not flagging tests as failures.
* This was due to not checking if the `trigger_rules` list had any rules defined before filtering alerts based on those rules.
* Adding more context to the output to explain various failures that can occur
* This will likely cause some other test events to fail, since it's more strict about defining rules that should trigger.
* Updated some test events that were triggering more rules than defined in the event's `trigger_rules` list to avoid multiple alerts per test event.
* In the future, test events that can trigger more than one rule can be placed in a single test file and …
> [cli][test] fix for rule tests that should not trigger alerts

- conf/types.json
size: small
The fields in the OneLogin events returned data can be used with data normalization. There is a non-documented field discovered after inspecting the events returned from the API that can be added as `sourceAddress`.
* Adding `proxy_ip` as `sourceAddress`.
> [data normalization] OneLogin proxy_ip as sourceAddress

- docs/source/app-configuration.rst
- docs/source/datasources.rst
size: small
New integration app [added](https://github.com/airbnb/streamalert/pull/355) for OneLogin events. Documentation had to be updated.
* Show OneLogin as available and updated the list of upcoming apps.
User the script from `tests/scripts/test_the_docs.sh` to make sure the change is valid.
> [docs][apps] Updating documentation for OneLogin new app

- requirements.txt
- tests/unit/stream_alert_cli/test_config.py
size: small
resolves #395
CLIConfig uses the filesystem to find the filenames of cluster configuration files. In the config unit tests, these filesystem operations need to be mocked out because cluster configuration files are user configured. Currently `__builtin__.open()` is mocked out, but we also need to mock out `os.path.listdir()`. Instead of mocking individual functions, __pyfakefs__ is used to create a mock filesystem.
* Added new python dependency pyfakefs to create a mock filesystem
* Update tests in test_config.py to use the mocked filesystem instead of mock_open
* Remove `prod.json` cluster config and added `abc.json` cluster config
* Step through CLIConfig.load() to make sure os.listdir() returns `prod.json`
* Run `nosetests -v tests/unit`
* …
> [testing] Remove dependency on filesystem for test_config unit tests

- terraform/modules/tf_stream_alert_app/iam.tf
- terraform/modules/tf_stream_alert_app/main.tf
to: @ryandeivert @austinbyers 
size: small
During the deployment of the OneLogin integration app, we were hitting a 64 characters limit for app names, due to using prefixes.
* Avoid the 64 characters limit by not using prefixes that make names too long.
> [tf] Workaround for 64 characters limit exceeded

- conf/sources.json
- rules/community/mitre_attack/defense_evasion/multi/obfuscated_files_or_information/right_to_left_character.py
- tests/integration/rules/right_to_left_character.json
to: @mime-frame @ryandeivert 
size: small
Malicious files can be disguised by using a encoding trick that uses the unicode character U+202E, also known as right-to-left-override (RLO). The trick hides a potentially malicious extension and makes them appear harmless.
[https://krebsonsecurity.com/2011/09/right-to-left-override-aids-email-attacks](https://krebsonsecurity.com/2011/09/right-to-left-override-aids-email-attacks)
* Adding `osquery` logs to kinesis placeholder.
* Adding `carbonblack` logs to s3 placeholder.
* Adding rule `right_to_left_character` using data normalization and tests.
Verification of schemas:
```
$ python manage.py validate-schemas
``` 
Testing of rule:
```
python manage.py lambda test --processor rule --test-file …
```
> [rules] Detect right-to-left character in commands or files

- manage.py
- stream_alert_cli/test.py
to: @jacknagz 
size: small
resolves N/A
Identified a bug when running the `python manage.py live-test --cluster prod`:
`
File "/Users/<username>/<repo-root>/stream_alert_cli/test.py", line 833, in run_tests
rules_filter = options.test_rules if not validate_schemas else options.rules if not context.mocked else None
`
`
AttributeError: 'Namespace' object has no attribute 'test_rules'
`
* Normalizing similar input flags so they save to the same var name 
* `--test-rules` and `--rules` now save to the same Namespace attribute of `rules`
* Using a dictionary of the namespace (cast with `vars`) to lookup attributes.
* The list of rules passed to `live-test` (ie: `live-test --rules <rule01> <rule02>`) will now be a unique set (duplicates are ignored) with the …
> [cli][test] fixing bug that broke live-test command

- .coveragerc
- setup.cfg
to: @jacknagz @ryandeivert 
size: small
Previous change added `show_missing = True` to `.coveragerc` to display the missing lines for unit tests. It turns out it can be all covered in the `setup.cfg` file, so we don't need to use an extra file for the coverage plugin.
* Adding coverage plugin configuration to `setup.cfg`.
Running `./tests/scripts/unit_tests.sh` to show the missing lines when the file `.coveragerc` is deleted.
> Removing .coveragerc and adding config to setup.cfg

- app_integrations/apps/app_base.py
- app_integrations/config.py
- app_integrations/main.py
- terraform/modules/tf_stream_alert_app/iam.tf
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_apps/test_duo.py
- tests/unit/app_integrations/test_config.py
to: @jacknagz 
size: medium
resolves N/A
The apps function has built in logic to detect if the execution is close to timing out, and will save state/exit cleanly if that is the case. However, if there were more logs to collect for the interval in which this lambda executed, they would not be collected until the next scheduled invocation occurs.
For instance, if a functions executes every hour, but only has enough time to process 1/2 hour worth of log data before timing out, that remaining 1/2 hour of log data would not be collected until the next scheduled invocation of the function. This is typically not an issue, and the function will catch up eventually. However, if there is a considerable change in log throughput and (ie - a company's scale …
> [apps] app successive invocations when nearing timeout

- stream_alert_cli/test.py
size: small
resolves N/A
Observed small bug in output formatting when listing errors with rules:
`
StreamAlertCLI [ERROR]: (1/1) Test failure: [duo_bypass_code_create_non_auto_generated.json] Test event with description 'A DUO bypass code that was auto generated should not create an alert.' is triggering the following rules but should not trigger at all: 'duo_bypass_code_create_non_expiring' ,'duo_bypass_code_create_unlimited_use'
`
In `'duo_bypass_code_create_non_expiring' ,'duo_bypass_code_create_unlimited_use'` above - the comma is preceded by a space instead of followed by one.
* Changing formatting so the comma is followed by a space instead of preceded by one in the comma separated output.
* Ran rule tests again with bad test …
> [cli][test] fixing comma formatting bug

- app_integrations/apps/app_base.py
- app_integrations/config.py
- app_integrations/main.py
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_config.py
- tests/unit/app_integrations/test_main.py
to: @javuto 
size: small
resolves N/A
Discovered that a partial execution of log collection would mark the config state as 'failing' upon completion, even though there was no failure. This was due to the state toggling naively marking the state to 'failing' if it was still set to 'running' at the time of exit.
* Adding a new state of `'partial'` that will get set when there are more logs to poll and a new apps function is invoked.
* The new 'partial' state must now exist in conjunction with the 'successive_invocation' event type in order for an invocation to continue.
* Adding unit tests to verify that the 'partial' flag is working as expected, and additional unit tests.
> [apps] fix for improperly marking app config as failing

- stream_alert_cli/test.py
size: small
resolves N/A
Discovered a bug where the 'logs' list within the `sources.json` file was not properly being checked for a log type. Example:
`
StreamAlertCLI [ERROR]: (1/3) Failures
`
`
StreamAlertCLI [ERROR]: (1/1) Invalid test event in file 'test_file.json' with description 'This is the description of the test event'. The 'sources.json' file does not include the log type 'carbonblack' in the list of logs for this service & entity ('s3:this.is.the.entity').
`
The above is a bug, since `carbonblack` is in the `sources.json`
* Checking the logs list for a log type instead of the 'source' which would always result in an misleading error being logged.
* Adding `return` to return after logging one error with a log to avoid …
> [cli] fixing bug in reporting errors with sources

- app_integrations/apps/app_base.py
- app_integrations/main.py
to: @javuto 
size: small
resolves N/A
Identified a very unlikely but possible race condition that could occur. In short, a 'chained' invocation of a app function could be started before the config in Parameter Store was properly updated with the `partial` state value. This could then cause the new invocation of the lambda to fail if it read the state as `running` before it was written to `partial`
* Writing the `partial` state config to parameter store before invoking the new lambda function.
* Unit tests passing.
> [apps] fix for potential but unlikely race condition

- docs/source/account.rst
- docs/source/athena-deploy.rst
- docs/source/athena-setup.rst
- docs/source/firehose.rst
size: small
We recently added support for searching data via Athena and Firehose, but there are no steps on how to set this up.
* Add some DOCS
Locally with the test_the_docs.sh script
> [docs] add athena data table creation docs

- rules/community/github/github_disable_dismiss_stale_pull_request_approvals.py
- rules/community/github/github_disable_protect_this_branch.py
- rules/community/github/github_disable_required_pull_request_reviews.py
- rules/community/github/github_disable_required_status_checks.py
- rules/community/github/github_disable_two_factor_requirement_org.py
- rules/community/github/github_disable_two_factor_requirement_user.py
- rules/community/github/github_oauth_application_create.py
- rules/community/github/github_site_admin_action.py
- rules/community/github/github_site_admin_user_promotion.py
- tests/integration/rules/github/github_disable_dismiss_stale_pull_request_approvals.json
- tests/integration/rules/github/github_disable_protect_this_branch.json
- tests/integration/rules/github/github_disable_required_pull_request_reviews.json
- tests/integration/rules/github/github_disable_two_factor_requirement_org.json
- tests/integration/rules/github/github_disable_two_factor_requirement_user.json
- tests/integration/rules/github/github_oauth_application_create.json
- tests/integration/rules/github/github_site_admin_action.json
- tests/integration/rules/github/github_site_admin_user_promotion.json
to: @javuto or @ryandeivert 
size: medium
See Changes
* New rule: `github_disable_dismiss_stale_pull_request_approvals`
* New rule: `github_disable_protect_this_branch`
* New rule: `github_disable_required_pull_request_reviews`
* New rule: `github_disable_two_factor_requirement_user`
* New rule: `github_oauth_application_create`
* Small changes (rule renaming, repro steps, description updates, ...)
```
StreamAlertCLI [INFO]: (54/54) Successful Tests
StreamAlertCLI [INFO]: (90/90) Alert Tests Passed
```
> streamalert - rules - github - 5 new rules and some cleanup

- app_integrations/apps/app_base.py
- app_integrations/apps/duo.py
- app_integrations/apps/gsuite.py
- app_integrations/apps/onelogin.py
- app_integrations/config.py
- conf/lambda.json
- conf/logs.json
- conf/sources.json
- docs/source/app-development.rst
- manage.py
- requirements.txt
- stream_alert_cli/config.py
- stream_alert_cli/helpers.py
- stream_alert_cli/runner.py
- tests/integration/rules/gsuite/gsuite_admin.json
- tests/unit/app_integrations/test_apps/test_duo.py
- tests/unit/app_integrations/test_apps/test_gsuite.py
- tests/unit/app_integrations/test_apps/test_onelogin.py
- tests/unit/app_integrations/test_config.py
- tests/unit/app_integrations/test_helpers.py
to: @javuto and @austinbyers 
size: large
resolves #348 
See #348 
tl;dr - Consume all GSuite logs:
https://developers.google.com/admin-sdk/reports/v1/guides/manage-audit-admin
https://developers.google.com/admin-sdk/reports/v1/guides/manage-audit-login
https://developers.google.com/admin-sdk/reports/v1/guides/manage-audit-tokens
https://developers.google.com/admin-sdk/reports/v1/guides/manage-audit-drive
https://developers.google.com/admin-sdk/reports/v1/appendix/activity/saml
https://developers.google.com/admin-sdk/reports/v1/appendix/activity/rules
https://developers.google.com/admin-sdk/reports/v1/appendix/activity/mobile
https://developers.google.com/admin-sdk/reports/v1/appendix/activity/gplus
...
* Adding initial implementation of G Suite …
> [apps] adding G Suite app for all activity audit reports

- docs/source/app-configuration.rst
size: small
resolves N/A
Adding doc updates to go with #426 (GSuite apps)
* Adds the following to currently supported services:
* G Suite Reports ([Activities](https://developers.google.com/admin-sdk/reports/v1/reference/activities))
- Admin
- Calendar
- Google Drive
- Groups
- Google Plus
- Logins
- Mobile Audit
- Rules
- SAML
- Authorization Tokens
* Tested locally with `tests/scripts/test_the_docs.sh `
> [docs] updates for gsuite apps

- docs/source/account.rst
size: small
Provide instructions on how to use named AWS profiles for account credential setup.
* Default to using AWS profiles
Ran the `test_the_docs.sh` script locally
> [docs][setup] use aws profiles instead of exporting creds directly

- conf/global.json
- docs/source/metrics.rst
- stream_alert_cli/terraform/kinesis_streams.py
- terraform/modules/tf_stream_alert_kinesis_streams/main.tf
- terraform/modules/tf_stream_alert_kinesis_streams/variables.tf
- tests/unit/conf/global.json
- tests/unit/stream_alert_cli/terraform/test_kinesis_streams.py
size: small
StreamAlert was enabling by default [enhanced monitoring](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_EnableEnhancedMonitoring.html) to surface infrastructure metrics at a granular level. This could ended up costly since those metrics are charged and they should be enabled when needed, instead of adding a unnecessary cost and not being utilized properly. 
* Shard level metrics are now empty by default, with the necessary documentation to enable them.
Changes were tested running `python manage.py terraform init`, `python manage.py terraform build` and `python manage.py terraform destroy` to make sure all the infrastructure is created and destroyed properly.
> [tf][kinesis] Disabling shard level metrics by default

- stream_alert_cli/helpers.py
- stream_alert_cli/test.py
to: @jacknagz 
cc: @airbnb/streamalert-maintainers, @securityclippy
size: small
resolves N/A
@securityclippy reported a bug via slack:
```
$ python manage.py live-test --cluster testing
File "manage.py", line 1346, in <module>
main()
File "manage.py", line 1341, in main
cli_runner(options)
File "/repos/streamalert/stream_alert_cli/runner.py", line 58, in cli_runner
stream_alert_test(options, CONFIG)
File "/repos/streamalert/stream_alert_cli/test.py", line 877, in stream_alert_test
run_tests(options, context)
File "/repos/streamalert/stream_alert_cli/helpers.py", line 450, in unmocked
return func(options, context)
File "/repos/streamalert/stream_alert_cli/test.py", …
```
> [cli][bug] fix potential bug that could throw an error if a mocked s3 bucket exists

- helpers/base.py
- stream_alert/alert_processor/main.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/shared/__init__.py
- tests/unit/stream_alert_rule_processor/test_rule_helpers.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
size: small
resolves #413 
1. Data Normalization: For fields added to the parsed record during rule processing, such as `envelope_keys` and `normalized_types`, they should always be prefixed with `streamalert:` to avoid collision with valid data fields.  `normalized_types` does not follow this convention.
2. Threat Intel: Remove IOC info duplication. In some records, different keys may contain the same value. After the record being normalized, there may have duplicated IOC info inserted into the record. 
* Example, a coming record 
```
{
"local_ip": "1.2.3.4",
"ipv4": "1.2.3.4"
}
```
* Keys `local_ip` and `ipv4` will be normalized to [sourceAddress](https://github.com/airbnb/streamalert/blob/master/conf/types.json#L42-L44) …
> Prefix streamalert to normalized types and remove duplicated IOC info

- conf/logs.json
- manage.py
- stream_alert/athena_partition_refresh/helpers.py
- stream_alert_cli/athena/handler.py
- stream_alert_cli/config.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/manage_lambda/package.py
- stream_alert_cli/manage_lambda/rollback.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform/handler.py
- tests/unit/stream_alert_cli/test_version.py
cc: @airbnb/streamalert-maintainers @securityclippy 
size: medium
resolves #424
There are a lot of disparate changes in this PR related to the CLI.  But it mainly is for adding capabilities for Athena to drop all tables (when destroying clusters), and rebuilding table partitions (when a schema is updated).
* Int => BigInt for Hive column defaults
* Modify the GHE schema for elapsed to be a string, there were parsing issues with Athena
* Add a continue prompt when destroying, this does some damage if you accidentally type this command
* Write helper functions for Athena when interacting with output and rebuilding partitions
* Add support for rebuilding partitions
* Add support for dropping all tables
* Other small cleanup
All tested in a side AWS account
> Rebuild Athena Partitions

- stream_alert/alert_processor/outputs.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size: small
The API v2 is available since June 2016 with no new additions added to the Events API v1 since July 2016. It will be deprecated in February 2018.
* Without breaking current code, this PR adds a new output to handle the PagerDuty Events API v2. This can be enabled gradually for rules or at once, but in any case the code is ready.
Added unit tests for the new class `PagerDutyOutputV2`. Ran unit tests, linter and rules checks:
```
...
TOTAL                                            2231     63    97%
Ran 396 tests in 7.514s
OK …
```
> [output] Adding support for PagerDuty Events API v2

- conf/lambda.json
- stream_alert/alert_processor/output_base.py
- stream_alert/alert_processor/outputs.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_alert_processor/test_main.py
- tests/unit/stream_alert_alert_processor/test_output_base.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size: medium
resolves #158 
Outputs in StreamAlert were using `urllib2` to process HTTP requests. For certain things (parsing output, parameter encoding) is simpler to use `requests` and we are already using it in app integrations.
* Replacing `urllib2` by `requests` in the `output_base.py`, to handle `GET`, `POST` checking for successful traffic.
* Added all the relevant code to the dispatchers for PagerDuty, Phantom and Slack to use the new methods using `requests`.
* Updated unit tests.
* Added `requests` as third party library in the `alert_processor_config`.
Unit tests, linter and StreamAlert processor:
```
...
TOTAL                                            2219     46    98% …
```
> [output] Replace urllib2 with requests

- app_integrations/apps/app_base.py
- app_integrations/config.py
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_config.py
to: @javuto 
size: small
resolves N/A
There are a handful of fixes in this PR that are the result of things I observed while writing the Box app. The gist is:
1. While observing CloudWatch logs, I noticed a `requests.get` call took the entire duration of an app invocation and results in the function timing out.
2. I also happened to notice that there was occasional instances of functions timing out during the cleanup phase of the app invocation - ie, if there were more logs to be collected, and the function invoked another lambda (a successor), the new invocation would happen but the current function would time out before exiting cleanly.
3. During some local testing, I identified a discrepancy with the `_determine_last_time` calculation. I was …
> [apps] bug fixes and adding padding for cleanup before func timeout

- app_integrations/apps/app_base.py
- stream_alert/alert_processor/output_base.py
size: small
Requests is replacing urllib2 in the outputs.
* Having `requests` to use a default timeout (for both `connection` and `read` calls) of 3.05 seconds, as recommended by the [requests docs](http://docs.python-requests.org/en/master/user/advanced/#timeouts).
```
...
TOTAL                                            2219     46    98%
Ran 397 tests in 8.224s
OK
$ python manage.py lambda test --processor all
...
StreamAlertCLI [INFO]: (55/55) Successful Tests …
```
> [output] Using timeout in requests methods

- stream_alert/alert_processor/outputs.py
- tests/unit/stream_alert_alert_processor/test_main.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size: small
resolves #445 
Two bugs are causing slack and phantom outputs to fail.
* Phantom output parameter needs to be wrapped in quotes
* Slack get request needs to be a post request
> [output] phantom and slack output fixes

- app_integrations/apps/app_base.py
- app_integrations/apps/box.py
- app_integrations/apps/duo.py
- app_integrations/apps/gsuite.py
- app_integrations/apps/onelogin.py
- conf/lambda.json
- conf/logs.json
- conf/sources.json
- requirements.txt
- tests/integration/rules/box/box_admin_events.json
- tests/unit/app_integrations/test_apps/test_box.py
- tests/unit/app_integrations/test_apps/test_gsuite.py
- tests/unit/app_integrations/test_config.py
- tests/unit/app_integrations/test_helpers.py
to: @javuto & @jacknagz 
size: medium
resolves #398 
See #398:
Create an App to support Box Events (admin logs):
* https://developer.box.com/reference#events
* Updates `required_auth_info` of the base app to ensure that the subclasses return an iterable (ie dict). This is to prevent subclasses from poorly implementing this method.
* New `BoxApp` for for admin (enterprise) events
* Similarly to the G Suite app(s), the box app requires a box service account to be created in the admin console of Box. This will provide the user with a json file needed for JWT authorization.
* Updating `requirements.txt` for the box sdk with jwt support (`boxsdk[jwt]==2.0.0a11`).
* This uses an alpha build of the box sdk due to [this …
> [apps] box app for admin events

- stream_alert_cli/test.py
size: small
The Slack integration tests were incorrectly mocking out a `GET` request instead of a `POST`. This was not picked up because all the integration tests included at least one output that did mock out a `POST` request.
If you just have slack as a rule output, the integration tests will fail.
```
@rule(logs=['cloudtrail:events'],
matchers=[],
outputs=['slack:sample-channel'])
def cloudtrail_critical_api_calls(rec):
```
```
cloudtrail_critical_api_calls
[Pass]  [trigger=1]                   rule      (s3): Deleting an AWS subnet (DeleteSubnet) will create an alert.
StreamAlertOutput [ERROR]: Encountered an error while sending to slack: <Mock name='mock().json().get()' id='4549616976'>
<Mock name='mock().json().get()' id='4549616976'> …
```
> [test] Slack integration tests need to mock a post request

- stream_alert_cli/test.py
to: @jacknagz 
size: small
resolves N/A
Discovered a bug when trying to use the `live-test` command where mocked secrets from previous tests could be read from disk instead of using valid credentials.
* Removes the temp dir (`$tmp/stream_alert_secrets`) before running tests to ensure the most up-to-date data is local.
* Ran `live-test` with event & local cached creds before changes and observed failure. Ran command after changes to ensure the dir is removed properly and valid creds are used.
> [cli] fixing bug where mocked secrets could be cached locally

- app_integrations/apps/app_base.py
- tests/unit/app_integrations/test_apps/test_app_base.py
to: @javuto 
size: small
resolves N/A
If connections or reads using `requests` ever timeout, the requests library catches those timeouts and raises its own exception(s). `requests.exceptions.ConnectTimeout` will be raised for connection-related timeouts, and `requests.exceptions.ReadTimeout` will be raised for timeouts during read.
Traceback observed in CloudWatch:
```
app.gather()
File "/var/task/app_integrations/apps/app_base.py", line 410, in gather
File "/var/task/app_integrations/apps/app_base.py", line 395, in _gather
File "/usr/lib64/python2.7/timeit.py", …
```
> [apps] catching connect and read timeout exceptions raised by requests

- stream_alert_cli/test.py
size: small
With the change added in #440 some tests were broken when testing the alert processor. Related to #446
* Adding test for `pagerdutyv2`.
* Fixed test for `phantom` output.
```
...
TOTAL                                            2301     46    98%
Ran 415 tests in 7.292s
OK
...
StreamAlertCLI [INFO]: (56/56) Successful Tests
StreamAlertCLI [INFO]: (90/90) Alert Tests Passed
```
> [output] Fix for output tests when using requests

- stream_alert/rule_processor/parsers.py
- tests/integration/rules/cloudtrail/cloudtrail_critical_api_calls.json
- tests/integration/rules/cloudtrail/cloudtrail_put_object_acl.json
- tests/unit/conf/logs.json
- tests/unit/stream_alert_rule_processor/test_classifier.py
- tests/unit/stream_alert_rule_processor/test_helpers.py
- tests/unit/stream_alert_rule_processor/test_parsers.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to: @jacknagz 
cc: @airbnb/streamalert-maintainers @0xdabbad00
size: small
resolves N/A
Discovered a bug where the json parser would attempt to extract records using a json path if one was defined, but would continue processing even if the path does not exist.
* Returning if `jsonpath_rw.parse(...).find(...)` does not find a valid json path.
* Updating misconfigured test events for `cloudtrail:events`
* This accounts for the majority of these changes since these json files needed json prettified.
* Some other misc cleanup.
Adding unit test to check for valid json path before continuing to process.
> [parser] fixing bug with json parser

- stream_alert/rule_processor/classifier.py
- tests/unit/stream_alert_rule_processor/test_classifier.py
to: @jacknagz 
size: small
resolves N/A
Discovered an issue with nested type conversion where the schema would still pass even if a value of a nested key was not of the right type.
1) Consider, for instance, you have this log defined in `logs.json`:
```
{
"test:log_name": {
"schema": {
"key_01": "string",
"key_02": "string"
},
"parser": "json",
"configuration": {
"json_path": "results[*]",
"envelope_keys": {
"host": "string",
"ip": "string"
}
}
}
```
2) And the incoming log looks like this:
```
{
"host": "host_name",
"ip": "0.0.0.0",
"results": [
{
"key_01": "value_01",
"key_02": "value_02"
}
]
}
```
3) When `streamalert:envelope_keys` is used and this log goes through classifying, the resulting log will look something like:
```
{
"key01": "value_01", …
```
> [lambda][rule] classifier nested type conversion bug

- conf/lambda.json
- stream_alert/alert_processor/outputs.py
- stream_alert/athena_partition_refresh/main.py
- terraform/modules/tf_stream_alert/firehose.tf
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert/metrics.tf
- terraform/modules/tf_stream_alert/variables.tf
- terraform/modules/tf_stream_alert_athena/iam.tf
- terraform/modules/tf_stream_alert_kinesis_events/README.md
- terraform/modules/tf_stream_alert_kinesis_events/main.tf
- terraform/modules/tf_stream_alert_kinesis_events/variables.tf
- tests/unit/conf/outputs.json
- tests/unit/stream_alert_alert_processor/test_main.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
- tests/unit/stream_alert_cli/test_outputs.py
to: @ryandeivert (Lambda) @chunyong-lin (Infra)
size: large
Alerts are generally sent in low volume, but there may be scenarios where this is not the case.  When using S3 as an alert output, the Alert Processor can only handle so many requests per second before timing out. 
To fix this issue, alerts can now land in S3 to be searchable in Athena via a new Firehose Delivery Stream.  This enables the Alert Processor to asynchronously send data to S3 in high volume.
* Write a new `KinesisFirehose` output plugin.
* Adjust the Athena Partition Refresh to determine the S3 key regex dynamically.
* This allows for backwards compatibility between the S3 and Firehose output plugins, since the resultant S3 key is determined based on the service.
* S3: …
> [outputs] Firehose Output and Terraform Cleanup

- stream_alert_cli/test.py
to: @javuto 
size: small
resolves N/A
Identified a bug in cli where a difficult to diagnose failure that occurs (ie: an invalid type for a value in a log causes a failure), we would not be properly report the failure at the end of processing.
For example:
```
$ python manage.py lambda test --processor rule --test-files test_log_for_bad_type
test_log_for_bad_type
StreamAlert [ERROR]: Invalid schema. Value for key [hostname] is not an int: This-Is-Not-An-Int
[Fail]  [log='unknown']               validation  (s3): Test Log for Bad Type
StreamAlertCLI [INFO]: (1/1) Successful Tests
$  echo $?
1
```
* This fix is to log a generic failure …
> [cli] reporting failures due to issue we cannot directly diagnose

- manage.py
- stream_alert/alert_processor/outputs.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size: small
PagerDuty Events API v2 [was added](https://github.com/airbnb/streamalert/pull/436).
* Added `pagerdutyv2` to the list of choices in `manage.py` so it can be added from the CLI.
```
...
TOTAL                                            2332     45    98%
Ran 420 tests in 7.407s
OK
...
StreamAlertCLI [INFO]: (96/96) Alert Tests Passed
StreamAlertCLI [INFO]: …
```
> [output] Adding pagerdutyv2 to choices in manage.py

- stream_alert_cli/helpers.py
size: small
resolves #460
If you are deploying StreamAlert in a region other than us-east-1, and you configure a firehose output, currently `./tests/scripts/rule_test.sh` will not work.  This fixes that.
* Uses the configured region for the mocked lambda location.
In `conf/global.json` configure a firehose output and set the region to `us-west-2`.  Then run the tests and note they fail. Now apply this change, and note it passes.
> [test] allow tests to run when using the firehose output and not us-east-1

- app_integrations/apps/app_base.py
- app_integrations/apps/box.py
- app_integrations/config.py
- tests/unit/app_integrations/test_apps/test_box.py
size: small
resolves N/A
During a deployment of an app for box admin event, a few bugs were discovered.
1) Two `AppIntegrationConfigError` exceptions did not have the proper string formatting for error messages.
2) Auth for the box app uses the `keyfile` stored within the auth info and the app was trying to load to use the base `auth` dict instead of the appropriate key.
3) The logic used in the config to cast auth values that are of type `unicode` to type `str` would result in nested dictionaries being omitted from the config.
* Box is the first app to actually utilize and entire dict within the auth config, so this went previously unnoticed.
* App Base: Formatting messages within exceptions properly (instead of just being a tuple …
> [apps][box] a few bug fixes with config and box app

- manage.py
- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/variables.tf
- terraform/modules/tf_stream_alert_globals/README.md
- terraform/modules/tf_stream_alert_globals/alerts_firehose/iam.tf
- terraform/modules/tf_stream_alert_globals/alerts_firehose/main.tf
- terraform/modules/tf_stream_alert_globals/alerts_firehose/variables.tf
- terraform/modules/tf_stream_alert_globals/main.tf
- terraform/modules/tf_stream_alert_globals/variables.tf
size: medium
follow up: #457 
The Firehose to deliver alerts to S3 should not be cluster based, it should be global.  See the tagged PR above for more context.
* Introduce a new `tf_stream_alert_globals` module to house global configuration sets.  The idea with this module is to be a placeholder for any other global resources we'll need in the future.  We can eventually move resources into it as well.
* Update the CLI to allow for adding new `aws-firehose` outputs.
Deployed and verified end-to-end in testing account
> Global Alert Firehose

- app_integrations/apps/onelogin.py
size: small
resolves #470 
When a requests goes to the OneLogin API, if the result of the request is `False`, we may access the response object to get information from the response. But for example, if there is a `ConnectTimeout` exception, the response will be `None`.
* Adds check to make sure the returned response is a valid JSON. Fixes #470.
```
...
TOTAL                                            2332     74    97%
Ran 420 tests in 6.865s
OK
$ python …
```
> [apps][onelogin][bug] Making sure response is valid before accessing it

- conf/logs.json
to: @jacknagz 
size: small
resolves N/A
Discovered an undocumented optional top level key for the box admin event logs of `accessible_by` after an initial deployment.
* Adding `accessible_by` as an optional top level key for box admin event log types.
Tests still passing with `python manage.py lambda test -p rule -f box_admin_events`
> [logs] adding optional top level key for box admin events

- app_integrations/apps/README.rst
to: @javuto 
size: small
resolves N/A
The `boxsdk` requirement needs to be natively compiled on an EC2 instance for the time being. This is simple walkthrough on how to accomplish that if the dependencies need updated in the future (before this stop gap is removed).
* Adding README.rst to demonstrate how to natively compile the boxsdk package on an EC2 instance.
N/A
> [apps] adding simple read me for box dependencies

- stream_alert_cli/terraform/generate.py
- stream_alert_cli/terraform/handler.py
size: small
@chunyong-lin identified a bug where if `enabled: false` was set in the cloudwatch monitoring config, it would fail Terraform.
* Fix the bug as described above
* Remove the old Athena files
Ran `python manage.py terraform generate` and unit tests prior to pushing
> [cli] cleanup athena tf.json and fix cw generate bug

- docs/source/app-configuration.rst
size: small
resolves N/A
The docs were not updated to include box as a supported service for apps.
* Adding box to the list of supported services for apps.
* Adding some links to other supported services.
Tested with:
`sphinx-build -W docs/source docs/build && open docs/build/index.html`
> [docs] adding box to list of supported apps

- app_integrations/apps/box.py
to: @javuto 
size: small
resolves N/A
After taking a second look at the docs (https://developer.box.com/reference#get-events-in-an-enterprise) I realized the _default_ limit is 100, while the actual _max_ is 500.
* This change is get the max amount possible on each call (500 instead of the default of 100).
* This should reduce the number of api calls we have to make and make the box app function run for a shorter amount of time.
* No substantial changes, but `tests/scripts/unit_tests.sh` passing
> [apps][box] bumping max log limit for box from 100 --> 500

- stream_alert_cli/helpers.py
- stream_alert_cli/test.py
to: @javuto 
size: small
resolves N/A
Rule tests that were run with `python manage.py lambda test -p all` would fail for any rules that were using firehose outputs with an error similar to:
```
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutRecord operation: Stream airbnb_streamalert_alert_delivery under account 123456789012 not found.
```
* Adding mocking support for AWS firehose output
Added a firehose output for rules and ran tests successfully.
> [cli][tests] adding mocking for firehose output

- docs/source/rules.rst
- manage.py
- stream_alert/alert_processor/helpers.py
- stream_alert/alert_processor/outputs.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_alert_processor/helpers.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
size: medium
Migrating to the PagerDuty REST API helps to simplify the code and utilize features only present in v2. You can read up on more advantages of the migration to the new API [here](https://v2.developer.pagerduty.com/docs/migrating-to-api-v2).
After adding support for the PagerDuty Events API v2, next step is to be able to create Incidents using the API.
* Adding support for PagerDuty Incidents API v2 (REST API) as output. [API reference for creating incidents.](https://v2.developer.pagerduty.com/v2/page/api-reference#!/Incidents/post_incidents).
* Added tests for new output.
* Adding context field as decorator in the alert, as `RuleAttributes` field. This allows specific rules to add some context to the alert record …
> [output] Adding new output for PagerDuty Incidents

- app_integrations/apps/app_base.py
- app_integrations/apps/box.py
- manage.py
- tests/unit/app_integrations/test_apps/test_box.py
to: @javuto 
size: small
resolves N/A
I noticed a single instance of the box app timing out in CloudWatch logs and determined that the `boxsdk` does not use a default timeout for connection or read requests (and can run indefinitely).
* Adding a timeout to the requests performed through the `boxsdk` that is the same as the default timeout for requests made through the app base.
* Wrapping the request with the `safe_timeout` function to make sure timeout exceptions that are raised do not crash the box app.
* Fixing typo in the cli within some helper text (`--test-files` --> `--test-rules`)
* Adding unit tests to verify that the timeout is properly caught and logged.
> [apps][box] add default timeout to requests made through boxsdk

- manage.py
- stream_alert/alert_processor/output_base.py
- stream_alert/alert_processor/outputs.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size:medium
resolves: #23 
Introduction of an additional output for Jira.  Alerts can now generate Jira issues.
* Jira output option added which supports multiple Jira apps (core, service desk, software)
* Jira output can be configured to create individual issues per StreamAlert alert, or to aggregate into a single issue based on rule name
* Aggregation behavior is identical to how the Phantom output aggregates alerts today
* Alert content appears in the "description" field of a Jira issue, while appended alerts are added as comments
* Unused "get_comments" method added to assist with more advanced aggregation in the future
* output_base.py modified to prevent noisy warning messages related to unverified requests from flooding the logs.  Performed with …
> [outputs] jira output

- app_integrations/apps/app_base.py
- app_integrations/apps/box.py
- app_integrations/apps/duo.py
- app_integrations/apps/gsuite.py
- app_integrations/apps/onelogin.py
- app_integrations/config.py
- app_integrations/main.py
- docs/source/app-development.rst
- manage.py
- stream_alert_cli/config.py
- stream_alert_cli/runner.py
- tests/unit/app_integrations/test_apps/test_app_base.py
to: @jacknagz 
size: small
resolves N/A
The `StreamAlertApp`s are currently loaded and cached using the `@app` class decorator while a separate function is used for returning a requested app type. Encapsulating this functionality into one place via a factory-style class to be used as a decorator would simplify this logic.
* This change is to convert the class decorator into a factory-style class to be used for decorating all subclasses.
* Adding methods for loading an app to this new decorator class.
* Apps will now be sorted in the help output printed with:
* `python manage.py app new --help`
* Adding reference to using `@StreamAlertApp` class decorator to docs.
* Adding unit tests to make sure all supported apps get registered.
* Deployed in test AWS …
> [apps] using factory-style class decorator for registering StreamAlertApps

- docs/source/clusters.rst
- manage.py
- stream_alert_cli/kinesis/handler.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform/cloudtrail.py
- stream_alert_cli/terraform/monitoring.py
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/variables.tf
- terraform/modules/tf_stream_alert_s3_events/main.tf
- tests/unit/stream_alert_cli/terraform/test_generate.py
- tests/unit/stream_alert_cli/terraform/test_monitoring.py
size: medium
To enable cross-account delivery of CloudTrail logs via S3, you can modify a policy in an S3 bucket which allows the CloudTrail service to deliver logs into specific prefixes.
Also pushing misc changes to easily enable/disable kinesis events, fixing a bug in an S3 policy, and a small change in the monitoring Terraform module.
* Support cross-account AWS Ids in CloudTrail
* S3 policy naming bug fix
* Explicitly add enabled kinesis/lambda alarms in monitoring module
* Kinesis CLI parser
* Updated tests
* Deployed in a test AWS account
> Cross Account CloudTrail Support, Kinesis CLI Parser

- stream_alert/alert_processor/outputs.py
- tests/unit/stream_alert_alert_processor/test_outputs.py
size: small
New output to use PagerDuty Incidents was added [here](https://github.com/airbnb/streamalert/pull/467). The REST API requires the header `From: validpagerdutyuser@email.com` to create a new incident.
* The header `From: ` is added to authentication, and the user will be added when creating new output.
* Modified method `_check_exists` to optionally return just a boolean.
* All tests have been modified to accommodate this change.
```
...
TOTAL                                                2516     76    97%
Ran 462 tests in 7.015s
OK …
```
> [output] PagerDuty incident requires "From:" header

- stream_alert/alert_processor/outputs/output_base.py
to: @jacknagz 
size: v small
resolves N/A
Discovered a small bug when configuring a new output via the cli where an instance method needed to be converted to a classmethod. Traceback:
```
File "manage.py", line 1239, in <module>
main()
File "manage.py", line 1234, in main
cli_runner(options)
File "/repos/streamalert/stream_alert_cli/runner.py", line 49, in cli_runner
configure_output(options)
File "/repos/streamalert/stream_alert_cli/runner.py", line 134, in configure_output
secrets_key = output.output_cred_name(props['descriptor'].value)
TypeError: unbound method output_cred_name() must be called with SlackOutput instance as first argument (got str instance instead)
```
* Converting instance method to class method and …
> [lambda][alert] fixing small bug where method should be classmethod

- stream_alert/athena_partition_refresh/helpers.py
- stream_alert_cli/athena/handler.py
- stream_alert_cli/terraform/s3_events.py
- terraform/modules/tf_stream_alert_s3_events/main.tf
- terraform/modules/tf_stream_alert_s3_events/variables.tf
- tests/unit/conf/clusters/advanced.json
- tests/unit/stream_alert_cli/terraform/test_generate.py
- tests/unit/stream_alert_cli/terraform/test_s3_events.py
size: medium
When configuring S3 event notifications on CloudTrail buckets, having the ability to filter based on a S3 key prefix allows us to route processing to certain StreamAlert clusters.  This is especially useful when multiple accounts send CloudTrail into the same S3 Bucket.
* Support `filter_prefix` and `filter_suffix` Terraform args to the s3 event notification resource
* Fix a couple bugs in Athena table creation
* Verified in a test AWS account
> S3 Events Prefix/Suffix + Athena Bug Fixes

- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
size: small
New output to use PagerDuty Incidents was added [here](https://github.com/airbnb/streamalert/pull/467). Incidents will be created with a low priority by default, unless specified.
* Added support to specify a valid priority name in the context.
* Added testing code.
```
...
TOTAL                                                  2573     73    97%
Ran 470 tests in 8.373s
OK
... …
```
> [output] Adding support for assign priority to incidents

- stream_alert/alert_processor/outputs/output_base.py
- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
size: small
There were some issues with the PagerDuty multiple APIs that was making StreamAlert to lose alerts becase the API access was being rate limited. With these changes the requests sent to the API will retry when a problem is detected, that way we can effectively mitigate the encountered rate limits, due to high volume alerts. 
* Added changes to the base output class to add retry methods for both GET and POST requests. This way the support for backoff/retry can be progressively added in each single output without breaking existing code.
* Added specific support in PagerDuty outputs to use the backoff/retry code.
* Modified existing tests to support new approach.
```
... …
```
> [output] Backoff support for all PagerDuty related outputs

- app_integrations/apps/app_base.py
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_apps/test_duo.py
size: small
In the function `_check_http_response` when a HTTP error is detected, the app base tries to grab the field `message` from the returned response JSON. This field may not exist and it generates the following error:
```
File "/var/task/app_integrations/apps/app_base.py", line 343, in _make_get_request
return self._check_http_response(response), response.json()
File "/var/task/app_integrations/apps/app_base.py", line 324, in _check_http_response
response.json()['message'])
KeyError: 'message'
```
This PR prevents that from happening by just grabbing the whole returned content, as it is done in the outputs code.
* Getting `response.content` instead of specific fields (`message`) from the response.
* Modified existing tests to …
> [apps] Extract all the returned content to avoid KeyError in JSON response

- app_integrations/apps/box.py
- app_integrations/apps/gsuite.py
- app_integrations/config.py
- tests/unit/app_integrations/test_apps/test_gsuite.py
- tests/unit/app_integrations/test_helpers.py
to: @javuto 
size: small
resolves N/A
During testing of the GSuite streamalert app, it was found that the proper permissions were not being used by the app, resulting in the following error:
`HttpError: <HttpError 401 when requesting https://www.googleapis.com/admin/reports/v1/activity/users/all/applications/admin?alt=json returned "Access denied. You are not authorized to read activity records.">`
* The GSuite app now uses a service account email to perform [domain-wide auth delegation](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account).
* This email address must be provided during app configuration and will be save the parameter store along with the keyfile's data.
* Fixing …
> [apps] utilizing delegation email for gsuite app

- stream_alert/alert_processor/outputs/jira.py
- stream_alert/alert_processor/outputs/output_base.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_jira.py
size: small
Backoff support allows to retry requests when something goes wrong.
* Changed returned value in `_post_request_retry` from a boolean to the whole `requests.Response` object.
* Added support for backoff in jira output.
* Modified tests according to changes.
```
...
TOTAL                                                    2793    103    96%
Ran 490 tests in 10.049s
OK
... …
```
> [output] Backoff support in Jira output

- stream_alert/alert_processor/outputs/slack.py
size: small
Backoff support allows to retry requests when something goes wrong.
* Added support for backoff in slack output.
```
...
TOTAL                                                    2793    103    96%
Ran 490 tests in 10.049s
OK
...
```
> [output] Backoff support in slack output

- stream_alert_cli/terraform/cloudtrail.py
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- tests/unit/stream_alert_cli/terraform/test_generate.py
size: small
Bug fix for supporting cross-account IDs in custom CloudWatch event patterns
* Bug fix on custom event patterns - It wasn't properly handling custom JSON input
* Small code cleanup
Deployed in test account
> [cli][tf] bug fix for custom event patterns + cleanup

- app_integrations/apps/README.rst
- app_integrations/apps/gsuite.py
- conf/logs.json
- tests/integration/rules/gsuite/gsuite_admin.json
to: @jacknagz 
size: small
resolves N/A
Discovered a pretty obscure bug that crashed the gsuite app on deploy with the following Traceback:
```
File "/var/task/app_integrations/apps/app_base.py", line 398, in do_gather
logs = self._gather_logs()
File "/var/task/app_integrations/apps/gsuite.py", line 120, in _gather_logs
pageToken=self._next_page_token
File "/var/task/googleapiclient/discovery.py", line 744, in method
for pvalue in pvalues:
TypeError: 'int' object is not iterable
```
* Determined that the `startTime` parameter was getting passed a value of `0` and the google api client does not like integers much :)
* Moving the storing of the initial timestamp out of the init to avoid being set to 0.
* Updating `gsuite:reports` schema to include nested …
> [apps] gsuite app timestamp fix and schema update

- terraform/modules/tf_threat_intel_downloader/dynamodb.tf
to: @jacknagz 
size: small
resolves N/A
Remove sort key from DynamoDB table. It is not necessary to have sort key in DynamoDB table, since the primary key (hash key) will also be identical from each item in the table. The primary key in the DynamoDB table is the value of IOC. 
* Remove `range_key` from terraform module, and it translates to `sort key` in DynamoDB table. 
* Tested it in AWS testing account, and it was passed.
> [tf] Remove sort key from DynamoDB table.

- stream_alert_cli/terraform/flow_logs.py
- terraform/modules/tf_stream_alert_flow_logs/iam.tf
- terraform/modules/tf_stream_alert_flow_logs/main.tf
- terraform/modules/tf_stream_alert_flow_logs/variables.tf
size: medium
The VPC flow log Terraform module currently only creates a subscription filter within a single account.  In order to support cross account subscription filters, some IAM permissions needed to change.
* Refactor to use IAM policy doc data resources
* Add an explicit cloudwatch log destination resource which allows us to grant cross account access
* Add an option in the `flow_logs` stream alert cluster module which accepts a list of `cross_account_ids`
Deployed and verified by using two test accounts
> [tf][cli] vpc flow log support clusters & cross-account delivery

- app_integrations/apps/gsuite.py
- app_integrations/batcher.py
- tests/unit/app_integrations/test_batcher.py
to: @jacknagz 
size: small
resolves N/A
1) Observed bug where a single log that exceeds the max size we can send to lambda (128k) could cause a max recursion stack overflow:
```
maximum recursion depth exceeded in cmp: RuntimeError
app.gather()
File "/var/task/app_integrations/apps/app_base.py", line 438, in gather
File "/var/task/app_integrations/apps/app_base.py", line 423, in _gather
File "/usr/lib64/python2.7/timeit.py", line 237, in timeit
return Timer(stmt, setup, timer).timeit(number)
File "/usr/lib64/python2.7/timeit.py", line 202, in timeit
timing = …
```
> [apps] safely handling single logs that exceed Lambda max input size

- conf/clusters/prod.json
- stream_alert/alert_processor/outputs/output_base.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_slack.py
size: small
Backoff was added to handle retries for outputs when something goes wrong. The current code uses `backoff.fibo` (Fibonacci), as method to define how long to wait between attempts. Also the maximum number of attempts was 3. For PagerDuty it was not making much of a difference since the requests were still rate limited, as the wait was not that long.
By moving to `backoff.expo` (Exponential), we will increase more the wait from attempt to the next one and also the maximum number to attempts will be 5.
Here is a comparison between the two approaches, with a quick script:
```
$ python compare.py
Exponential
1
2
4
8
16
Fibonacci
1
1
2
3
5
```
* Increased the timeout for default clusters.
* Changed the backoff behavior …
> [output] Increasing backoff time between retries

- conf/logs.json
size: small
resolves N/A
Observed failed parse due to some optional top level keys in the `carbonblack:watchlist.hit.binary` schema.
* Adding some optional keys to this schema.
* Tested on locally on test event that is not committed here.
> [schema] updating  with opt keys

- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
size: small
If you have already added `pagerduty-incident` as output, this will break things. Make sure you re-create the output using this new format.
PagerDuty Incidents output uses the name of a service to create a new incident. It was a bit confusing when creating a new output because other PagerDuty outputs use the `service_key` and that is the integration key.
* Using `service_name` instead of `service_key` in incident creation.
* Modified current tests to reflect this change.
```
...
TOTAL                                                    2820    100    96%
Ran 496 tests in 7.831s
OK …
```
> [output] Use service_name for PagerDuty Incidents

- stream_alert/threat_intel_downloader/threat_stream.py
- terraform/modules/tf_threat_intel_downloader/dynamodb.tf
- tests/unit/threat_intel_downloader/test_threat_stream.py
to: @austinbyers  
size: small
resolves N/A
DynamoDB has a list of [reserved words](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html), e.g. `value`, `type`. AWS document mention `The following keywords are reserved for use by DynamoDB. Do not use any of these words as attribute names in expressions.` 
Sadly, I am using `value` and `type` as attribute names in DynamoDB table. Table will be created correctly, however, it requires special handling when we want to query the table. 
So we just avoid to use these reserved words. 
* change attribute names in DynamoDB IOC table. 
* Rule testing
```
...
StreamAlertCLI [INFO]: (93/93) …
```
> [threat_intel_downloader] Update key names for the IOCs stored in DB table

- conf/types.json
size: small
resolves N/A
G Suite Admin SDK Report logs have an `ipAddress` field that maps to the source address of where an event took place.
* Adding the `sourceAddress` --> `ipAddress` mapping to the `types.json` file so we can get threat intelligence alerting on gsuite logs.
> [data-normalization] adding gsuite ipAddress to data normalization/threat intel

- conf/logs.json
- tests/integration/rules/cloudwatch/cloudwatch_control_message.json
to: @jacknagz 
size: small
resolves N/A
Observed a failed parse for an incoming CloudWatch control message log.
* Adding `cloudwatch:control_message` schema.
* Adding validation test event for the new schema.
> [schema] adding cloudwatch control message schema and validation test

- conf/types.json
size: small
resolves N/A
Box admin event logs have an `ip_address` field that maps to the source address of where an event took place.
* Adding the `sourceAddress:ioc_ip` --> `ip_address` mapping to the `types.json` file so we now have threat intelligence alerting on box admin event logs.
> [data-normalization] adding box ip_address to data normalization/threat intel

- app_integrations/apps/gsuite.py
to: @javuto 
size: small
resolves N/A
Noticed the following traceback for an exception that was not being caught in the GSuite app:
```
app.gather()
File "/var/task/app_integrations/apps/app_base.py", line 438, in gather
File "/var/task/app_integrations/apps/app_base.py", line 423, in _gather
File "/usr/lib64/python2.7/timeit.py", line 237, in timeit
return Timer(stmt, setup, timer).timeit(number)
File "/usr/lib64/python2.7/timeit.py", line 202, in timeit
timing = self.inner(it, self.timer)
File "/usr/lib64/python2.7/timeit.py", line 100, in inner
_func()
File …
```
> [apps] catching socket timeout in gsuite app (again)

- manage.py
- stream_alert_cli/config.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/manage_lambda/handler.py
- stream_alert_cli/manage_lambda/package.py
- stream_alert_cli/manage_lambda/version.py
- stream_alert_cli/terraform/handler.py
- stream_alert_cli/terraform/kinesis_events.py
- terraform/modules/tf_stream_alert_kinesis_streams/variables.tf
- tests/unit/stream_alert_cli/terraform/test_kinesis_events.py
- tests/unit/stream_alert_cli/test_version.py
size: medium
resolves #434 
When building new clusters, or deploying in the event of an infrastructure based issue, having the ability to deploy by cluster greatly decreases the time necessary to make changes.  This PR focuses on refactoring to make this possible, and also adds features for supporting batch size, and more.
* Add the ability to deploy and publish versions by cluster
* Support the `all` option in the deployment process for optional Lambdas
* Do not deploy if S3 package upload fails
* `yapf` on `stream_alert_cli/config.py`
* Update unit tests accordingly
* Deploy the rule processor
* Deploy all (enabled) processors
* Deploy by cluster
* Terraform build specific cluster
> Deploy by Cluster, Batch Size Param, and More

- docs/source/kinesis.rst
- stream_alert_cli/terraform/kinesis_streams.py
- terraform/modules/tf_stream_alert_kinesis_streams/iam.tf
- terraform/modules/tf_stream_alert_kinesis_streams/main.tf
- terraform/modules/tf_stream_alert_kinesis_streams/variables.tf
- tests/unit/stream_alert_cli/terraform/test_kinesis_streams.py
size: small
It's general best practice to not directly assign user policies, and instead assign them to groups.  This change applies this best practice, and also creates the ability to optionally create the user.  In some instances, data is delivered to Lambda in other ways (CloudWatch events, S3 notifications, etc)
* Create a clustered stream_alert group
* Assign Kinesis users to this group
* Assign the Kinesis WriteOnly policy to this group
* Add a variable to optionally create users/groups
* Local CI testing
* Deployed the change on an existing cluster, no users or access keys were deleted
* Deployed the change with `"create_user": false`
> Assign Kinesis Users to a Group, and Make User Creation Optional

- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
size: small
Context was added to rules to be able to extract information from the rule record and be utilized after (for example, outputs). This code makes that alteration possible and adds test for it.
* If context is used, it will be passed as argument of the rule.
* Test to verify the added code.
```
...
TOTAL                                                    2951     94    97%
Ran 501 tests in 8.074s
OK
$ python manage.py lambda test …
```
> Rule context can be modified within rule

- stream_alert_cli/helpers.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/manage_lambda/handler.py
- stream_alert_cli/manage_lambda/rollback.py
- stream_alert_cli/terraform/handler.py
size: small
resolves #217 
The recent change to the `deploy` command (#520) caused the `init` steps to break.  While testing, I also discovered that we can add a simple check to avoid large stacktraces when AWS creds aren't loaded.
* Since `clusters` is passed to the `deploy` method, we need to modify the one-off named tuple which mimics ArgParse to include a `clusters` attribute.
* Check for valid AWS creds by looking at the `os.environ` dictionary
* Local pylinting + unit testing
* Also did test `deploy` and `terraform` commands
> Init Bug Fix, Check for Valid AWS Creds, Rollback by Cluster

- stream_alert_cli/test.py
size: small
When using the output `pagerduty-incident` and testing the processor, some mocking was missing.
* Modified the mocked creds for `pagerduty-incident` output to reflect what the output is expecting.
* Modified the static method `_setup_requests_mocks` to be used with `pagerduty-incident` output. 
```
...
TOTAL                                                    2951    103    97%
Ran 501 tests in 7.947s
OK
$ python manage.py lambda test …
```
> [output] Mocking for rule processor testing

- app_integrations/config.py
- tests/unit/app_integrations/test_config.py
to: @javuto 
size: small
resolves #524 
See #524. The gist: a race condition can cause the state to not get written to SSM Parameter Store if the state parameter is already in the process of being updated.
* Will only save the remote state if the value of the local state has changed since it's previous value.
* Adding two unit tests to ensure that:
1) The remote state _is_ updated if the current value is being changed.
2) The remote state is _not_ update if the current value is the same as the new value being set.
> [apps] adding support for suppressing state saves if no change occurred

- stream_alert/rule_processor/rules_engine.py
- stream_alert/rule_processor/threat_intel.py
- stream_alert_cli/helpers.py
- stream_alert_cli/terraform/streamalert.py
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/variables.tf
- tests/unit/stream_alert_cli/terraform/test_generate.py
size: small
resolves N/A
* Add more dynamodb mocking which will be useful when doing rule testing while Threat Intel Beta is enabled. (Note, currently, Threat Intel Beta has issue, I am fixing now.) 
* Enforce IOC value check in lowercased. 
Also, this PR adds a conditional check to add read permission to IOC dynamodb table to Rule Process IAM role. 
* Rule test
```
...
```
* Unit test
```
...
-------------------------------------------------------------------------------------
TOTAL …
```
> Add dynamodb domain md5 mocking

- manage.py
- stream_alert_cli/config.py
- stream_alert_cli/terraform/threat_intel_downloader.py
- terraform/modules/tf_threat_intel_downloader/dynamodb.tf
- terraform/modules/tf_threat_intel_downloader/variables.tf
- tests/unit/stream_alert_cli/test_config.py
to: @jacknagz @ryandeivert 
size: medium
resolves #536
[DynamoDB Auto Scaling](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ProvisionedThroughput.html) is a useful feature when DynamoDB IOC table (built by `Threat Intel Downloader`) is processing large number of burst records by `batch_get` from Rule Processor(s). The auto scaling feature will automatically adjust Read capacity based on the traffic. 
Note: AWS DynamoDB Auto Scaling is also support Write Capacity. We don't support Write Capacity auto scaling right now, because,
* The Consumed Write Capacity is related low compared to Read Capacity.
* Write Capacity is more expensive than Read Capacity. With auto scaling it may generate unexpected cost. Right now, it is …
> Apply dynamodb autoscale

- conf/global.json
- stream_alert_cli/terraform/kinesis_streams.py
- tests/unit/conf/clusters/advanced.json
- tests/unit/conf/global.json
- tests/unit/stream_alert_cli/terraform/test_kinesis_streams.py
to: @javuto 
size: small
Shard level metrics should be clustered
* Read the `shard_level_metrics` config option from the cluster and not the global config
Unit tests
> [cli] cluster based shard level metrics

- stream_alert/rule_processor/threat_intel.py
- stream_alert_cli/config.py
- tests/scripts/unit_tests.sh
- tests/unit/stream_alert_cli/test_config.py
- tests/unit/stream_alert_rule_processor/test_helpers.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
size: small
resolves #539
Threat Intel Beta enables Rule Processor(s) to query a DynamoDB table where stores IOC data. In the implementation it doesn't have exception handling. This PR is to add exception handling for 
* ClientError
* ParamValidationError
* Add error handling when querying dynamodb table.
* Make MockDynamoDBClient great (again). It includes raising more exceptions now.
* Enforce lowercase IOC value from first place.
* Add more test cases to catch errors.
* Remove `autoscale` setting from `threat_intel` and it is only available in `threat_intel_downloader`.  This bug was caused by careless Copy&Paste ;(
* Unit test
```
...
Ran 510 tests in 8.852s
OK
```
* Rule test
```
python …
```
> Threat intel error handling

- stream_alert/rule_processor/threat_intel.py
size: small
resolves N/A
Context for the change
* Cast IOC value to string always.
* Also use `LOGGER.error` to avoid confusion while searching crash/exception in CloudWatch.
* Unit test
```
...
-------------------------------------------------------------------------------------
TOTAL                                                    3001    124    96%
Ran 510 tests in 10.134s
OK
```
* Rule test
```
...
```
> [Threat Intel] Cast IOC value to string

- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/rule_processor/threat_intel.py
- tests/unit/conf/types.json
- tests/unit/stream_alert_rule_processor/test_handler.py
- tests/unit/stream_alert_rule_processor/test_helpers.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
size: medium
resolves #531
[Threat Intel Beta PR](https://github.com/airbnb/streamalert/pull/507) is using DynamoDB table to store IOC. During deploy, we found Read Capacity Throttling issue when there are significant amount of log records processed by Rule Processor. 
This issue has been identified that threat intel should be called from rule processor handler, instead of in rules engine.
This [line](https://github.com/airbnb/streamalert/blob/master/stream_alert/rule_processor/rules_engine.py#L395) is called by every normalized record, so it doesn't take advantage of batch_get_item from DynamoDB.
Collect all normalized records and call threat_detection from Rule Processor's handler.
* Call threat intel from StreamAlert `handler`, instead of in …
> Fix read capacity overload issue

- stream_alert/rule_processor/firehose.py
- stream_alert_cli/athena/handler.py
size: medium
While creating Athena tables for CarbonBlack log types, I discovered a bug in how the CLI converts the log name format to the Athena format.  Athena tables can only have underscores in them, so all other special characters need to be converted.
* Fix a bug when looking up schemas for log names containing special characters
* Pylint fixes
Local test suite
> Firehose Table Creation Bug Fixes

- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/rules_engine.py
size: small
resolves N/A
There is a bug that one normalized record may be added to normalized records list multiple time. It will cause memory outrage when processing records from S3 (normally there are 13k-14k records in one json file from S3).
* Add a flag to indicate if the record has been added to normalized record list or not. 
* Rule testing
```
...
```
* Unit testing
```
...
-------------------------------------------------------------------------------------
TOTAL                                                    3020    117 …
```
> [threat intel] avoid duplicating normalized records.

- stream_alert/rule_processor/handler.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
- tests/unit/stream_alert_rule_processor/test_handler.py
to: @jacknagz 
size: small
resolves #527 
See #527. Metrics should track the records for the processed payload, not the incoming 'records' array.
* Using a instance property to track the total records from each processed payload.
* This value is then logged at the end of processing as the total records metric.
* Adding unit test to check for tracking the proper processed log count.
> [metrics] getting a more accurate processed record count in rp handler

- stream_alert/rule_processor/config.py
- stream_alert/rule_processor/threat_intel.py
- stream_alert_cli/logger.py
- tests/unit/conf/clusters/test.json
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
size: small
resolves N/A
During internal deploy, we realized it will be super helpful if we support enable/disable threat_intel per cluster based. So users can have choice to enable threat intel on interested clusters or trying to avoid running threat intel against certain clusters. 
* This PR is to add an explicitly disable flag for threat_intel feature based on clusters. In another words, even global threat_intel flag in conf/global.json is set to true, the cluster still can disable it by adding "enable_threat_intel": false, under rule_processor settings.
* If there is no enable_threat_intel flag in clusters' conf, it is default to True and global threat intel flag will take effect.
* Rule testing
```
python manage.py lambda test …
```
> [threat intel] Add threat_intel flag in clusters' config

- stream_alert_cli/test.py
size: small
In order to patch `GET` and `POST` requests, `MagicMocks` are used for each different output. For the tests involving the `pagerduty-incident` output, a key was missing and was making all tests to fail.
* Adding key `name` to the mocked response.
```
...
TOTAL                                                    3022    117    96%
Ran 514 tests in 9.432s
OK
...
StreamAlertCLI [INFO]: (60/60) …
```
> [output] Adding key to mocked request for api.pagerduty

- terraform/modules/tf_threat_intel_downloader/dynamodb.tf
to: @jacknagz 
size: small
resolves N/A
It is recommended to use lifecycle ignore_changes for read_capacity and/or write_capacity if there's autoscaling policy attached to the table. Otherwise, terraform will change `read_capacity` every time when you run it.  Also, we only apply autoscaling policy to `read_capacity`. Please refer to [terraform doc](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html) for more details. 
* Add `read_capacity` to lifecycle ignore list in `aws_dynamodb_table` resource.
* Terraform plan was successful.
> [tf] Ignore DDB read_capacity change since we have autoscaling policy.

- stream_alert/rule_processor/threat_intel.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
size: small
resolves 
When processing network related events, we will encounter the situation that many of the events are generated in the private subnet. It is totally not necessary to run Threat Intel against these private ip addresses. This PR proposes to filter out broadcast and private IP addresses. 
* Use IPAddress class from `netaddr` lib.
* Add unit test cases. 
* Performance scoping
Tested with 5466 cloudwatch events with IP filter, the IOC number is dropped to 2324, by 57%. It means the RC to DDB will be dropped by 57% based on the test events I have. 
* Rule Test
```
... …
```
> [threat intel] apply ip filter to only check public ip

- app_integrations/apps/gsuite.py
to: @javuto 
size: small
resolves N/A
A bug in the gsuite app prevented accessing an attribute on a module. In a nutshell, the `oauth2client` does not import the `service_account` module by default, and requires an explicit import. This results in the following traceback:
```
'module' object has no attribute 'service_account': AttributeError
app.gather()
File "/var/task/app_integrations/apps/app_base.py", line 438, in gather
File "/var/task/app_integrations/apps/app_base.py", line 423, in _gather
File "/usr/lib64/python2.7/timeit.py", line 237, in timeit
return …
```
> [apps] fixing bug in gsuite app related to imports

- stream_alert/rule_processor/threat_intel.py
- stream_alert/threat_intel_downloader/threat_stream.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
- tests/unit/threat_intel_downloader/test_threat_stream.py
to: @chunyong-lin @ryandeivert 
size: small
Backoff number of retries was set to 3 as default and that was making unit tests to slow down a bit. This should shave off 1-2 seconds from that time.
* Patch `max_tries` in backoff to 0 for unit tests.
* Adding a class property for Threat Stream to avoid hardcoding `max_tries`.
```
...
TOTAL                                                    3022    117    96%
Ran 514 tests in 9.432s
OK
$ python manage.py lambda test --processor …
```
> [threat intel][tests] Make unit tests 1-2 seconds faster

- terraform/modules/tf_stream_alert_athena/main.tf
cc: @chunyong-lin 
size: small
* Adds the "StreamAlert" tag to SQS, since SQS tagging support was added a few months ago
* `terraform validate`
> Add StreamAlert tag to Athena SQS queue

- stream_alert/rule_processor/threat_intel.py
size: small
resolves N/A
IPAddress class raise `ValueError` when the address value contains `/ `(subnet prefix), instead of raising `AddrFormatError`. (Refer to IPAddress [source code](http://netaddr.readthedocs.io/en/latest/_modules/netaddr/ip.html).)
* This fix is to catch `ValueError`, in addition to catch `TypeError` also.
* Rule testing
```
...
```
* Unit testing
```
...
-------------------------------------------------------------------------------------
TOTAL                                                    3048 …
```
> [threat intel] Catch ValueError and TypeError while processing IP IOCs

- stream_alert_cli/athena/handler.py
- stream_alert_cli/athena/helpers.py
- tests/unit/stream_alert_cli/athena/test_handler.py
size: medium
Nested log schema is not supported when creating tables in Athena.
* Added recursive support when converting log schema to Athena schema.
```
15:00 $ ./tests/scripts/pylint.sh
Starting pylint script
15:01 $ ./tests/scripts/unit_tests.sh
...
CLI - Generate Athena schema: simple ... ok (0.0003s)
CLI - Generate Athena schema: special key ... ok (0.0003s)
CLI - Generate Athena schema: nested ... ok (0.0002s)
...
Ran 521 tests in 66.392s
OK
```
> athena: added recursive schema support

- stream_alert/alert_processor/outputs/output_base.py
- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
to: @ryandeivert @mime-frame 
size: medium
PagerDuty REST API v2 allows to create incidents and assign them to a specific user from the PagerDuty account. That allows alerts to be able to be assigned when they are created. The problem is that the API does not allow to have any JSON object data, like the PagerDuty Events API v2. With this code, we are able to utilize the incident creation capabilities and also have a rich content by merging alerts/events created with the Events API v2.
* Added PUT requests support to the output base class.
* Added capability to create events and merge them with the created incidents.
* Modified unit tests to test new capabilities.
```
... …
```
> [outputs] PagerDuty Incident rich content

- .pylintrc
- stream_alert/rule_processor/main.py
- tests/scripts/pylint.sh
- tests/unit/stream_alert_rule_processor/test_init.py
- tests/unit/stream_alert_rule_processor/test_main.py
size: small
Users should be able to have non-Python files in the `rules/` directory (e.g. `README`, `REVIEWERS`, etc). The current rules import logic imports all files except `*.pyc`, `.*` and `__init__.*`. This means files like `rules/README` are also imported, which causes an `ImportError`.
* Change rule import logic to import all `*.py` files in `rules/` and `matchers/` except `__*`
* Refactor rule import logic into 3 unit-testable functions.
* Rename `test_main.py` to `test_init.py` (since it tests LOGGER during `__init__.py`)
* Added new unit tests for rule import logic.
* Added new unit tests for rule import logic.
* Verified that the rule integration tests covered the same set of rules as before (all rules are still imported)
> Import only .py files when importing rules

- conf/logs.json
size: small
resolves N/A
Add new optional key `watchlists` to cb_watchlist_hit_binarys schema.
* Add optional key watchlists to conf/logs.json
* Rule testing
```
...
```
* Unit testing
```
...
Ran 526 tests in 11.048s
OK
```
> [logs] update cb_watchlist_hit_binarys schema with opt keys.

- conf/clusters/prod.json
size: small
Update the default `prod.json` cluster, as it's fallen behind in terms of CLI updates
JSON validated locally
> [conf] update default prod cluster

- stream_alert/athena_partition_refresh/main.py
- tests/unit/stream_alert_athena_partition_refresh/test_main.py
size: small
resolves #569 
A KeyError bug was discovered when deleting messages from the StreamAlert Athena Queue.  This PR addresses the bug fix, and adds some small changes for clarity/ease of reading.
* Update unit test to closer reflect reality
* Fix the bug
* Locally with unit testing and pylint
* Deployed to a test account
> [athena] KeyError bug fix

- stream_alert/alert_processor/outputs/pagerduty.py
- stream_alert_cli/test.py
size: small
Some changes were merged [here](https://github.com/airbnb/streamalert/pull/567) to the `pagerduty-incident` output which after testing with a wide set of rules, it needed some fixes to mock properly some added functionality.
* Changes to `test.py` in order to mock properly the added code to `pagerduty-incident` output.
* Added the `integration_key` to the mocked credentials for `pagerduty-incident` output.
```
...
Ran 521 tests in 14.749s
OK
Your code has been rated at 10.00/10 (previous run: 10.00/10, …
```
> [output] Fixes for mocks to test some outputs

- stream_alert/rule_processor/firehose.py
- stream_alert_cli/terraform/cloudtrail.py
- stream_alert_cli/terraform/monitoring.py
- terraform/modules/tf_stream_alert_monitoring/main.tf
- terraform/modules/tf_stream_alert_monitoring/variables.tf
- tests/unit/conf/clusters/advanced.json
- tests/unit/conf/clusters/trusted.json
- tests/unit/stream_alert_cli/terraform/test_monitoring.py
size: medium
related to: #478 
Two changes in this PR, one is to add the Firehose Request Id string after each batch for better troubleshooting with #478, and one is to add knobs for the Cloudwatch Monitoring Terraform module.
* Add RequestId in the logger for each Firehose batch request
* Make the CloudWatch Alarm module configurable
* Fix a bug in the CloudTrail module by defaulting logging to enabled
* Update tests
Tested locally with unit tests and pylinting, deployed Lambda change onto a test account
> Add Firehose Request Id and Support Custom CW Alarm Params

- stream_alert/rule_processor/threat_intel.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
to: @chunyong-lin @javuto 
size: small
resolves N/A
* Some unit tests for functions that use backoff are not able to properly mock the backoff attempts, resulting in sluggish unit tests.
* Nesting a function that is currently an instance method so the decorator can properly have it's `max_tries` argument altered for tests.
* Adjusted unit tests, now sped up by a few seconds.
> [tests] sped up some threat intel tests with nested function wrapping

- setup.cfg
to: @jacknagz 
size: small
resolves N/A
Ignore B108 hardcorded_tmp_directory check in Bandit. In Lambda, /tmp is explicitly where local files must be stored.
* Update `setup.cfg` to ignore B108 security checking in Bandit.
* Rule testing
```
...
```
* Unit testing
```
Ran 529 tests in 8.046s
OK
> [test] Ignore B108 hardcorded_tmp_directory check in Bandit

- conf/logs.json
to: @jacknagz 
size: small
resolves N/A
We noticed the value of `repo_id` can be empty in log coming from GHE when the event is to deletion a repository. Change type of `repo_id` to string, so that the rule classifier will handle empty value properly.
* Change type of `repo_id` to string in GHE schema.
* Rule testing
```
...
```
* Unit testing
```
...
Ran 529 tests in 8.475s
OK
```
> [logs] change repo_id to string in ghe schema

- stream_alert/athena_partition_refresh/main.py
to: @jacknagz 
size: small
resolves N/A
Issue #590 is caused by unexpected messages format from SQS queue which are supposed to be in the format of `[dict(), dict(), ...]`. However, Athena received unexpected messages in the format of `[list(), list(), ...]` which results `TypeError: list indices must be integers, not str`. 
In order to fix the issue completely, I would like to get the unexpected messages so that we can add reasonable unit test to reproduce the issue.
* Add a new debug message to log `message_batch` which are the message to be deleted.
* Update error message to reflect failed response messages. 
* Rule testing
```
...
StreamAlertCLI [INFO]: …
```
> [Athena] Add debug message for issue 590

- stream_alert/rule_processor/firehose.py
size: small
resolves #478
AWS support suggests to explicitly close firehose connection to solve connection reset issue we encountered 1-2 times a day, approximately. The one line change is verified in internal environment and it does fix the issue.
* Add one line to explicitly close firehose connection.
* Rule testing
```
...
```
* Unit testing
```
...
Ran 529 tests in 7.423s
OK
```
> [rule processor] explicitly close firehose connection

- stream_alert/athena_partition_refresh/main.py
- tests/unit/helpers/aws_mocks.py
- tests/unit/stream_alert_athena_partition_refresh/test_main.py
size: small
resolves #590 
We noticed there is Athena error due to `TypeError` while deleting messages from SQS. The root cause of `TypeError` is because of complicated list comprehension logic when first deletion failed. The list comprehension added extra list around pushed back messages. 
* Break down complicated list comprehension to simpler ones.
* Add mock class for SQS client and add unit test case to reproduce error.
* Add a `max_retries` in backoff logic to make the code testable. 
* Rule testing
```
...
```
* Unit testing
``` …
```
> [athena] fix TypeError while delete messages from SQS

- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
size: small
When creating incidents it may be helpful to add a note with a bit of context of what has happened or an action taken. This adds support for creating a note to a given incident.
This is just adding the functionality and the unit tests, there will be an upcoming PR to add this to the `pagerduty-incidents` output.
* Added ability to create a text note given an incident id.
* Added unit tests for the code.
```
...
Ran 533 tests in 9.331s
OK
Your code has been rated at 10.00/10 (previous run: 10.00/10, …
```
> [output] Adding support to add notes to incidents

- docs/source/outputs.rst
- manage.py
- stream_alert/alert_processor/outputs/github.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_github.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
size: medium
resolves: https://github.com/airbnb/streamalert/issues/586
Background issue for context: https://github.com/airbnb/streamalert/issues/586
* Add a new `github` output which will create Github issues in the specified repository when alerts are generated.
```
(streamalert) patrickod@C02T70ALHF1T [12:29:52] [~/src/streamalert]  [patrickod/add-github-output]
-> %  ./tests/scripts/unit_tests.sh
...
Ran 533 tests in 13.391s
OK
(streamalert) patrickod@C02T70ALHF1T [12:33:13] [~/src/streamalert]  [patrickod/add-github-output]
-> %  ./tests/scripts/pylint.sh
Starting pylint script
Your code has been rated at …
```
> [output] Add Github output

- stream_alert/rule_processor/rules_engine.py
Improve the error message output to the user when a matcher fails to execute in
the rule_processor.
size: small
* Improve the error message output when a matcher fails to execute in the rule processor lambda execution.
> Improve error message when a matcher fails to execute

- stream_alert_cli/helpers.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/terraform/handler.py
to: @jacknagz 
size: small
resolves #194  (supersedes #359)
Two separate issues unnecessarily slow down StreamAlert deploys:
- Most Terraform operations are implemented as a `plan` followed by an `apply` after user confirmation. This requires Terraform to parse the config and walk its graph twice. The built-in `-auto-approve=false` accomplishes the same plan + user confirmation, but faster (because Terraform is only invoked once)
- There are some cases (e.g. `lambda deploy`) where we unnecessarily refresh between Terraform commands
* `tf_runner` accepts 4 keyword arguments: `action`, `refresh`, `auto_approve`, and `targets`
* `-auto-approve=false` is used instead of requesting user confirmation ourselves. Besides speed, this has another benefit: the …
> Speed up deploys with -auto-approve

- conf/outputs.json
- docs/source/outputs.rst
- docs/source/rules.rst
- manage.py
- stream_alert/alert_processor/outputs/komand.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_komand.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
size: small
resolves #602
This is basically a copy/paste job of the Phantom integration, but even simpler.  Komand has a web hook, which you hit with an authorization token, and just sent it your data.
Deployed and tested in our environment.
> Komand support added

- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
size: small
Out solution to workaround the PagerDuty limitation of creating incidents with no rich content (as in JSON data attached to the record) was to create an alert and merge it with an incident. This is done with a `PUT` request and there was a problem with the JSON payload serialization since it was provided as the `params` value in `requests`. Using the `json` value the serialization happens correctly and the requests provides the right payload in the request body.
Also tests.
* Fixed bug when merging an alert with an incident. Now `PUT` requests payload gets serialized properly as JSON.
* Bumped the `BACKOFF_MAX` from 3 to 5 to make sure we are getting the alert incident id from the PagerDuty API.
* Added more tests to the …
> [output] PagerDuty fix for merging alert into incident

- conf/global.json
- stream_alert/rule_processor/alert_forward.py
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/rule_processor/sink.py
- stream_alert/shared/metrics.py
- stream_alert_cli/terraform/generate.py
- stream_alert_cli/test.py
- terraform/modules/tf_alert_processor_iam/main.tf
- terraform/modules/tf_lambda/iam.tf
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert_globals/main.tf
- terraform/modules/tf_stream_alert_globals/variables.tf
- tests/unit/conf/global.json
- tests/unit/stream_alert_rule_processor/test_alert_forward.py
- tests/unit/stream_alert_rule_processor/test_handler.py
- tests/unit/stream_alert_rule_processor/test_sink.py
to: @jacknagz and @ryandeivert 
size: medium
In order to support alert merging (and more reliable alert delivery), we need to start keeping state about the alerts. We will do this with a Dynamo table that sits in between the Rule Processor and Alert Processor.
This PR creates the new alerts table and forks all alerts to the table *in addition to the alert processor*, so we can test the alerts table in production. We will sever the rule processor - alert processor connection in a subsequent pull request after we verify that writing to the table is working as expected.
* Fixes a bug in the `tf_alert_processor_iam` module when the output lists are empty
* Replaces the `LogsAndMetrics` custom policy in the `tf_lambda` module with the managed …
> Fork alerts to a Dynamo table

- stream_alert/alert_processor/outputs/output_base.py
- stream_alert/alert_processor/outputs/pagerduty.py
to: @austinbyers or @jacknagz 
size: small
Following up #614, I forgot to add the actual fix for the issue, which uses the `json` parameter in requests instead of `params`. Also added some code to display the rule description first for alerts going to PagerDuty, which is better for people getting the alerts and not having to scroll down JSON data before knowing what actually fired.
* `PUT` request uses `json` parameter in requests instead of `params`.
* Alert description will appear before record in PagerDuty alerts/incidents.
```
...
Ran 545 tests in 9.224s
OK …
```
> [output] Fix for PUT request bug

- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/payload.py
- stream_alert/shared/metrics.py
- tests/unit/stream_alert_rule_processor/test_helpers.py
- tests/unit/stream_alert_rule_processor/test_payload.py
cc: @airbnb/streamalert-maintainers @chunyong-lin 
size: small
Currently when the rule processor receives S3 event notifications, it will still try and download the file, but instead pre processing should just exit at this point.  I have also added a quick metric for NormalizedRecords
* Ignore empty S3 files
* Add NormalizedRecords metric
* Update tests
Local CI
> S3Payload Ignore Empty Files, NormalizedRecords Metric

- .gitignore
to: @austinbyers
size: small
partially addresses #419 
Each deploy will generate all the `.tf.json` files, there is no need to store them in the repo. If you have stored those files in your repo, and each deploy updates them, this change will start ignoring them so you should consider doing a `git rm terraform/*.tf.json` to avoid keeping outdated files.
* Ignore any file with extension`.tf.json`, since they are generated on deploy commands.
```
...
Ran 545 tests in 9.224s
OK
Your code has been rated at 10.00/10 (previous run: 10.00/10, …
```
> [tf] Ignore .tf.json files

- conf/lambda.json
- conf/sources.json
- rules/community/binaryalert/binaryalert_yara_match.py
- stream_alert/alert_processor/main.py
- stream_alert/athena_partition_refresh/main.py
- stream_alert/rule_processor/main.py
- stream_alert/threat_intel_downloader/main.py
- stream_alert_cli/helpers.py
- stream_alert_cli/manage_lambda/package.py
- stream_alert_cli/terraform/threat_intel_downloader.py
- stream_alert_cli/test.py
- terraform/modules/tf_stream_alert_globals/main.tf
- terraform/modules/tf_threat_intel_downloader/dynamodb.tf
- terraform/modules/tf_threat_intel_downloader/variables.tf
- tests/integration/rules/binaryalert/binaryalert_yara_match.json
- tests/unit/stream_alert_athena_partition_refresh/test_main.py
size: small|medium|large
resolves: #267
resolves: #572  
A collection of small fixes and features that I've accumulated
* #620 added support for SNS and SQS outputs, but did not update the alert tests to mock those outputs. This has been fixed
* Per #572 , Dynamo autoscaling works best with the service role automatically generated by AWS. We use that instead of creating our own IAM role
* Run `terraform fmt` to fix a spacing issue which snuck in
* The `third_party_libraries` config option is generally only applicable to the rule processor, where users can specify additional libraries to install for their rules to work. To reduce confusion, this config option has been removed from the other default lambda configs (although it will …
> A collection of small fixes

- rules/community/binaryalert/binaryalert_yara_match.py
- stream_alert/alert_processor/helpers.py
- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/outputs/aws.py
- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_alert_processor/helpers.py
- tests/unit/stream_alert_alert_processor/test_helpers.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
cc: @airbnb/streamalert-maintainers  @mime-frame 
size: small
We want to generate unique alert IDs to track them throughout their lifetime. For example, we can use them in the subject of messages sent via SNS
* Adds alert UUID to alert dictionary
* Adds a subject to SNS messages with rule name + alert ID
* [unrelated] Fix BinaryAlert rule docstring
* BuildKite CI
* Deploy to a test account - the SNS alert showed up in my inbox:
`binaryalert_yara_match triggered alert 091b1fd6-51f7-4be4-982e-9378b0af8cf6`
> Add alert UUID and use it in SNS subject

- stream_alert/alert_processor/outputs/output_base.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
to: @ryandeivert or @javuto 
size: small
resolves N/A
During an internal triage, I found out we need to catch ReadTimeout and ConnectTimeout while sending [requests post request](https://github.com/airbnb/streamalert/blob/master/stream_alert/alert_processor/outputs/output_base.py#L398). [requests.execptions.Timeout](http://docs.python-requests.org/en/master/_modules/requests/exceptions/) will catch both `ReadTimeout` and `ConnectTimeout`.
* Add `requests.exceptions.Timeout` to default exceptions in output base class
* Update unit test cases. 
* Unit test
```
...
Ran 548 tests in 9.324s
OK
```
* Rule test
```
...
StreamAlertCLI [INFO]: (61/61) Successful Tests
StreamAlertCLI …
```
> [output] catch requests timeout exceptions

- stream_alert/rule_processor/payload.py
- tests/unit/stream_alert_rule_processor/test_payload.py
size: small
resolves #613 , resolves #629 
There were two small bugs with the S3 Payload pre-parsing.  One was a vague error message when downloading from S3, one was failing to catch an `IOError` when the Lambda container's disk is full
* Catch `IOError` on download from S3
* Show the key and bucket when the object size is too big
* Update tests
Local CI testing with nose and pylint
> [s3 payload] catch ioerror, and provide more context on s3 object error

- conf/logs.json
- stream_alert/rule_processor/firehose.py
- stream_alert/rule_processor/payload.py
- stream_alert/rule_processor/threat_intel.py
- stream_alert_cli/athena/handler.py
- stream_alert_cli/terraform/handler.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
to: @mime-frame or @ryandeivert 
size: small
* Add CB audit log schema
* Fix typos (😂 )
Local rules, linting, and unit testing
> CB Audit Schema, Fix Typos

- terraform/modules/tf_stream_alert_athena/main.tf
to: @jacknagz 
size: small
The athena results bucket was using the name of the bucket as the tag when it should be using `StreamAlert`. This is mostly for billing tracking purposes.
* Changing the `Name` resource tag to `StreamAlert`
> [athena] fixing athena results bucket tag name

- stream_alert_cli/terraform/handler.py
size: small
* @austinbyers discovered an issue during initialization where the `alerts` table creation failed:
```
StreamAlertAthena [ERROR]: The query SHOW TABLES LIKE 'alerts'; returned FAILED, exiting!
StreamAlertAthena [ERROR]: The query CREATE EXTERNAL TABLE alerts (log_source string,log_type string,outputs array<string>,record string,rule_description string,rule_name string,source_entity string,source_service string)PARTITIONED BY (dt string)ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'LOCATION 's3://<prefix>.streamalerts/alerts/' returned FAILED, exiting!
StreamAlertCLI [ERROR]: The alerts table could not be created
```
* Thanks to Austin for proactively testing the fix :)
* Changing when the `create_table` function is …
> [athena] fixing when the create_table gets called

- stream_alert/rule_processor/alert_forward.py
- stream_alert/shared/metrics.py
- stream_alert_cli/test.py
- terraform/modules/tf_stream_alert/main.tf
- terraform/modules/tf_stream_alert_globals/main.tf
- tests/unit/stream_alert_rule_processor/test_alert_forward.py
- tests/unit/stream_alert_rule_processor/test_handler.py
size: small
Batch writing in Dynamo is far easier than I previously thought, because boto3 provides a [context manager](http://boto3.readthedocs.io/en/latest/guide/dynamodb.html#batch-writing):
```python
with table.batch_writer() as batch:
batch.put_item(Item={})
```
The batch writer automatically handles buffering and retrying items which failed to write. So we can remove a bunch of custom logic we added to do this.
* Use `batch_writer()` for the alerts table instead of the underlying client
* Replace the `UnprocessedAlerts` custom metric with `FailedDynamoWrites`
* Rename `ALERT_TABLE` environment variable in the rule processor to `ALERTS_TABLE` (makes more sense to me - I kept naming variables "alerts_table")
* Change the alert as …
> Use context manager for Dynamo batch_write

- terraform/modules/tf_stream_alert_cloudtrail/main.tf
size: small
The new `terraform-provider-aws`[ added support for cloudtrail event_selector](https://github.com/terraform-providers/terraform-provider-aws/pull/2258). Attempting to apply the streamalert cloudtrail module attempts to overwrite the defaults:
* Adding the `event_selector` to the cloudtrail module to keep the current setting from getting overwritten.
> [tf] fix to address terraform support for cloudtrail event_selector

- stream_alert/alert_processor/outputs/output_base.py
- stream_alert_cli/helpers.py
- tests/unit/stream_alert_alert_merger/test_main.py
to: @ryandeivert or @chunyong-lin 
size: small
When syncing #642 internally, we found a couple of bugs related to rule testing. Namely:
- The output credentials bucket was not mocked correctly because it had the wrong name
- The mocks for the threat intel table and the alerts table conflict with each other 
* Reverted name of the secrets bucket in the alert processor (`prefix.streamalert.secrets` is correct, not `prefix_streamalert_secrets`)
* Remove `@mock_dynamodb2` decorator from methods which setup mock tables, because the context is already mocked when those methods are called
* Deployed this to a test account and tested the slack integration (to confirm output secrets are working as expected). Going forward, I'll make sure to test outputs with …
> Fix bugs introduced from #642

- stream_alert/rule_processor/firehose.py
- stream_alert/rule_processor/threat_intel.py
to: @austinbyers or @jacknagz 
size: small
Identified a function that used backoff that does recursive record sanitization. If the function ever backs-off, this would result in unnecessary calls to sanitize keys.
* Moving the record dumping and sanitization to outside of the backed-off function.
* Changing another small instance of something similar in the threat_intel module.
Unit tests passing, etc
> small optimization to avoid multiple recursive calls

- terraform/modules/tf_stream_alert/variables.tf
- terraform/modules/tf_stream_alert_app/main.tf
- terraform/modules/tf_stream_alert_athena/main.tf
- terraform/modules/tf_stream_alert_globals/alerts_firehose/variables.tf
size: small
CloudWatch log search performance depends on how many log streams exist within a log group.  This PR is an attempt to make searching quicker by lowering the amount of log streams retained in a single group.
* Reduce cloudwatch log retention for Athena, Rule Processor, Apps, and Firehose
None
> [tf] reduce cloudwatch log retention to 14 days

- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to: @ryandeivert or @austinbyers 
size: small
When using the PagerDuty output `PagerDutyIncidentOutput`, the target service and default escalation policy were stored by name, making the output to generate 2 extra requests to the API, to verify those items (and retrieve both IDs). If those IDs are provided when creating the output, we no longer need to verify them and less API calls will be needed. In environments where there is a large number of alerts generated per hour, saving 2-3 API calls per alert helps to avoid API throttling.
* Storing service ID and escalation policy ID as part of the output, it saves 2-3 requests per alert to the API.
* Modified unit tests accordingly.
* Context will contain now the policy ID to be assigned to.
```
$ rm …
```
> [output] Reducing the PagerDuty API requests per alert

- stream_alert/rule_processor/rules_engine.py
- stream_alert/rule_processor/threat_intel.py
- tests/unit/conf/logs.json
- tests/unit/conf/sources.json
- tests/unit/conf/types.json
- tests/unit/stream_alert_rule_processor/test_helpers.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
to: @ryandeivert
size: small
resolves #654 
Please see issue #654 where has example and detail.
* Remove the flag which prevent a record to be normalized more than once.
* Refactor `check_alerts_duplication` to remove duplicated records.
* Add unit test case to reproduce issue and verify fix.
* Rule testing
```
...
```
* Unit testing
```
...
Ran 556 tests in 9.120s
OK
```
> [threat intel] allow one record to be normalized multiple times

- stream_alert_cli/test.py
size: small
Related to https://github.com/airbnb/streamalert/pull/652, this is needed for testing alerts using the new format of the PagerDuty output and storing the service and escalation policies IDs.
* Adding mocked `service_id` and `escalation_policy_id` in the alert processor CLI tests.
```
...
Ran 555 tests in 10.902s
OK
...
StreamAlertCLI [INFO]: …
```
> [output] Fix for alert processor cli and pagerduty incidents

- stream_alert_cli/manage_lambda/version.py
- stream_alert_cli/terraform/alert_merger.py
- stream_alert_cli/terraform/alert_processor.py
- stream_alert_cli/terraform/app_integrations.py
- stream_alert_cli/terraform/lambda_module.py
- tests/unit/stream_alert_cli/terraform/test_alert_processor.py
size: small
Due to lambda configs living in different places in the conf directory, support is needs for accepting a lambda config from arbitrary places.
* `tf_lambda` module generation now expects the lambda config to be passed from the caller
Updating unit tests for how this affects the `description` for the function
> [cli][tf] lambda tf module generation now expects the lambda config from caller

- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
size: small
resolves N/A
The PR #655 will exhaust the memory when processing a patch of log file contains thousands logs. Will look for new solution.
* Revert the changes made in PR #655 
* Rule testing
```
...
```
* Unit testing
```
...
Ran 562 tests in 9.943s
OK
> Revert PR #655

- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to: @jacknagz 
size: medium
resolves #654
The fix to allow one record to be normalized multiple times with **different set of datatypes** in PR #655 causes memory exhausting issue. We can reproduce the issue by profiling memory usage using library `memory_profile`.
The root cause of memory exhaustion is caused by one record is normalized multiple times with **same set of datatypes** and normalized records list is grown in linear speed when threat intel feature enabled. User may not notice the memory issue unless there are thousands records been normalized in one lambda invocation.
The solution is to check if a record has been normalized by the **same set of datatypes** or not. If so, use normalized information from existing normalized records, otherwise …
> [Data Normalization] Fix memory exhausting issue

- manage.py
- stream_alert_cli/athena/handler.py
- stream_alert_cli/helpers.py
- stream_alert_cli/terraform/handler.py
- tests/unit/stream_alert_cli/test_helpers.py
to: @austinbyers
size: small
The CLI currently lacks the ability to rebuild the athena 'alerts' table. This abstracts away the differentiators between 'data' tables and the 'alerts' table so the same code can be used for rebuilding both.
**NOTE**: This PR is currently being compared to @austinbyers `austin-alert-class` branch since it is dependent on some of his changes. Once his PR merges, I will switch this to compare against master.
* Updating athena cli code to handle refreshing both 'data' and 'alerts' table types.
* This uses @austinbyers `Alert` class to determine the most up-to-date set of keys and value types in an alert and transforms that into a schema that reflects said keys/values.
* Removing '--table-type' requirement from athena cli …
> [cli] adding support for alert table rebuilding

- stream_alert/alert_processor/outputs/slack.py
cc: @jacknagz 
size: tiny
#666 introduced a bug in the Slack output: the rule name (which appears at the beginning of the slack message) was accidentally replaced with the rule description, leading to Slack messages which were hard to read.
* Revert https://github.com/airbnb/streamalert/commit/943e6ccf12fb198093a85823de84f2bae22b8f39#diff-d23b5ca88d24a7ca4a9150e246c621afR226
- Slack message in test account returned to correct format
- Manually reviewed all other output changes in #666 (again) to make sure a similar bug didn't happen elsewhere
> Bug fix: Slack rule name in message

- manage.py
- stream_alert_cli/terraform/athena.py
size: small
A CLI argument for the `python manage.py lambda test -p rule` subcommand was improperly not part of the mutually exclusive group.
* Fiing the -r/--test-rules and -f/--test-files arguments to be part of the same mutually exclusive group.
Attempted to run the command with these args at the same time and received the expected error:
`manage.py lambda [subcommand] [options] test: error: argument -f/--test-files: not allowed with argument -r/--test-rules`
> [cli][bug] fixing lambda test arg that was incorrect

- stream_alert_cli/athena/handler.py
to: @jacknagz 
size: small
The athena lambda config used to require different bucket/refresh type information for various tables that were created. Now only bucket names and whether they are for data or alerts is required.
* Removing some code that would overwrite the existing bucket entry when creating a new table.
* This only adds new buckets if they don't already exist, and sets them as 'data' buckets.
* Buckets are needed in this dict so s3 event notifications to the athena partition refresh function get configured properly for the buckets.
> [cli][bug] removing bad update to athena lambda config

- conf/global.json
- stream_alert_cli/manage_lambda/version.py
- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_stream_alert_globals/main.tf
- terraform/modules/tf_stream_alert_globals/variables.tf
- tests/unit/conf/global.json
- tests/unit/stream_alert_cli/terraform/test_generate.py
- tests/unit/stream_alert_cli/test_version.py
size: small
We need to begin storing some general information related to rules to enable staging/promotion/etc. This is the beginning of changes to enable that.
* Creating `rules_tables` DynamoDB table in terraform with a hash key of `RuleName`
* Updating terraform generation for read/write capacity for this table.
* General cleanup of some generation code where kwargs is unnecessary and/or being abused.
* Another PR is incoming that will actually add information to this table upon deploy.
Updating unit tests for new `rules_table` settings.
> [tf] add table for storing rule information

- app_integrations/config.py
- stream_alert_cli/manage_lambda/package.py
- tests/unit/app_integrations/test_config.py
size: small
resolves #682
See #682, gist: rapid state saving can cause issues with SSM and will produce a `TooManyUpdates` error
* Adding backoff to the `_save_state` function that will backoff on `ClientError` exceptions.
* The saving will be attempted 5 times and will then raise an exception.
* Adding `backoff` to app integration packaging requirements.
Updating unit tests to patch new `MAX_SAVE_TRIES` class property, but no other test changes were required for this.
> [apps] adding backoff to state saving in apps functions config

- manage.py
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/shared/stats.py
- stream_alert_cli/test.py
size: medium
There is often the need for more insight into how long a rule takes to run. This could help us  understand any performance impact caused by rules.
* Adding a `time_rule` decorator to use on rule functions.
* Adding a cli `--stats` flag for use during `manage.py lamdba test ...`
* Adding a cli `--repeat` flag that can repeat a test n number of times.
* A new `RuleStatistic` class is now used for tracking rule processing time and call count.
Statistic output will be similar to:
```
duo_bypass_code_create_non_auto_generated                  0.05602837 ms       6 calls      0.00933806 avg
cloudtrail_security_group_ingress_anywhere                 0.05793571 ms      10 calls      0.00579357 avg …
```
> adding logic to perform basic rule statistics

- manage.py
- stream_alert_cli/config.py
- stream_alert_cli/terraform/threat_intel_downloader.py
- terraform/modules/tf_threat_intel_downloader/variables.tf
- tests/unit/stream_alert_cli/test_config.py
to: @strcrzy 
size: small
resolves: N/A
This PR is a follow-up to PR #684 which supports exclusive filtering in *threat_intel_downloader*. Add *excluded_sub_types* setting to *threat_intel_downloader* terraform module so that *excluded_sub_types* setting will be written to `conf/lambda.json` under *threat_intel_downloader*.
Also, this PR corrects prefix when generate default config for *threat_intel* and *threat_intel_downloader* lambda functions. So users don't manually update them. 
* Deploy changes to AWS testing account was successful.
* Rule testing
```
...
```
* Unit testing …
> [threat_intel_downloader] filtering part2

- stream_alert/rule_processor/classifier.py
to: @jacknagz 
size: small
resolves #676 
See #676
* Fixing bug during classification that would not fail if an invalid 'type' was defined in a log schema.
* We should investigate how we could 'validate' this before it gets to this point in processing, since logs invalid log schemas are basically just burning processing time for every log.
> fixing bug where unsupported types in logs would not fail classification

- conf/outputs.json
size: v small
Just removing an old config option that is no longer necessary, as it is a hard-coded required output.
> removing unnecessary output that is now required by default

- conf/global.json
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/main.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/shared/rule.py
- stream_alert_cli/test.py
- tests/unit/conf/global.json
- tests/unit/stream_alert_rule_processor/test_handler.py
- tests/unit/stream_alert_rule_processor/test_main.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
- tests/unit/stream_alert_shared/test_rule.py
size: medium
Currently based largely on changes in #689, this enables specifying arbitrary paths from within which to import rule and matcher files.
* Adding `rule_locations` and `matcher_locations` options to global config (see [Up for Disucssion](#up-for-discussion) below for more info).
* Moving rule import logic to the `stream_alert.shared.rule` module so it is decoupled from the lambda handler code.
* Calling the import code from within the new `RulesEngine` class, which will load the various paths in the config.
* Updating `stream_alert_cli/test.py` to remove the formerly required `import stream_alert.rule_processor.main` line to force rule loading out of band.
* Updating message in a `NameError` that was improperly formatting …
> adding support for specifying rule import paths

- stream_alert/alert_processor/outputs/aws.py
- terraform/modules/tf_alert_processor_iam/main.tf
to: @javuto 
size: small
The SQS output sends the entire alert dictionary (including rule description, outputs, etc), but most downstream processing needs only the alert record. Indeed, the Lambda output sends only the alert record.
* Send only the alert record to SQS outputs (the log which triggered an alert)
* Lookup the SQS queue by name instead of hardcoding the URL
* Deploy to another account
> SQS output sends only record and looks up queue URL

- manage.py
- stream_alert_cli/config.py
to: @jacknagz 
size: small
Someone in Slack sent a screenshot of a poorly formatted exception message. **This should be the last Exception in our _current_ code that handles formatting incorrectly.** Reviewers should look out for improper formatting in the future.
* Using `str.format()` for custom exception message during instantiation instead of the invalid `('%s', arg)` syntax that should only be used for logging (not exceptions).
* Removing hard-coded alerting outputs from the CLI and loading them straight for the `StreamAlertOutput` class. Now when new outputs are implemented, they do not need to be updated here.
> [cli] fix error message and remove hard-coded services for outputs

- conf/global.json
- manage.py
- stream_alert/shared/rule_table.py
- stream_alert_cli/helpers.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/rule_table.py
- stream_alert_cli/runner.py
- tests/unit/stream_alert_shared/test_rule_table.py
size: large
In order to support rule staging, we need to implement a 'front end' for the rules DynamoDB table. This is the first iteration on a RuleTable performing that interaction.
Adding initial `RuleTable` that currently handles operations such as:
* Loading the state of all rules currently in the table
* Diff'ing the existing remote rules against the local rule set.
* Updating an empty table with rules (presumably adding rules for the first time). This operation will have rules bypass the 'staging' state and go straight to 'production'
* Updating a table that has previously existing entries with new rules. This operation will have rules go into the staging state for a default window of 48 hours (for now).
* Printing a …
> support for adding rule information to dynamo table

- stream_alert_cli/manage_lambda/deploy.py
size: small
The rule table should only really be updated if the rule processor is being deployed (not, say, if only the alert processor is deployed).
* Ensuring rule processor is being deployed before updating rules tables.
> fix to only update rule table if rule proc is deployed

- docs/source/rules.rst
- stream_alert/rule_processor/handler.py
to: @javuto 
size: small
Some docs are outdated and reference previous syntax for rule decorator import.
* Removing usage of `StreamRules`
N/A
> some doc updates for new rule importing syntax

- stream_alert/shared/rule_table.py
- tests/unit/stream_alert_shared/test_rule_table.py
size: small
The `RuleTable` class needs the ability to toggle the staging state of a given rule.
* Removing the `NewlyStaged` attribute from the default dynamo record, as I'm not sure it will actually be utilized and can be added back later if necessary.
* Adding a `toggle_staged_state` function to the RuleTable that will attempt to update the given rule's record with the new state. If moving to staging, this will also set the `staged_at` and `staged_until` attributes for the rule.
Adding unit tests to cover new toggle functionality.
> adding rule staging toggling to the rule table

- stream_alert/shared/rule.py
- tests/unit/stream_alert_shared/test_rule.py
to: @jacknagz 
size: small
A stretch goal for rule staging would allow for identifying changes to the body of a rule (as opposed to just _new_ rules). The idea involves checksumming the contents of the rule.
* This is a POC of how we can identify changes to the contents of a rule function, exclusive of the docstring, code comments, or changes to the decorator arguments.
* Adding a `checksum` property to the `Rule` class which generates an md5 as a checksum for the contents of the rule function, or returns the previously cached hash if this has already been computed.
* This gets the raw code for a rule function, using `inspect`, and walks the AST for the code. It then calculates a running hash for the expressions within the function, excluding the …
> adding simple rule checksumming POC

- manage.py
- stream_alert_cli/logger.py
- stream_alert_cli/rule_table.py
- stream_alert_cli/runner.py
size: small
Users need the ability to run a command to stage or unstage a current rule in the rules db.
* Adding a subcommand to support staging or unstaging of rules.
* Staging will work like so:
`$ python manage.py rule-table stage foo_rule bar_rule`
* Un-staging will work like so:
`$ python manage.py rule-table unstage foo_rule bar_rule`
> [cli] adding stage subcommand to rule-table command

- stream_alert_cli/test.py
size: small
[This change](https://github.com/airbnb/streamalert/pull/703/commits/c3a292c2725dd768fea42b2aad022fa18e41a9ac) sets the logger levels before getting to the testing phase, so this code is no longer necessary.
* Removing unnecessary code block that is no longer required due to aforementioned change.
> removal of code since loggers now have their levels set before testing happens

- manage.py
to: @javuto or @jacknagz 
size: medium
I noticed a ton of redundancy in the CLI's argparse parser creation.
* Adding a helper to simplify CLI parser/subparser generation and reduce code redundancy.
> adding subparser generation helper to reduce redundancy

- manage.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/rule_table.py
size: small
The deploy process needs to be able to explicitly stage or unstage a given list of rules.
* Adding `--stage-rules` and `--unstage-rules` arguments to the lambda deploy process.
* Creating a new subclass of the `argparse.Action` class that is used for handling errors with the user providing the same rules for both the `--stage-rules` and `--unstage-rules` arguments.
> [cli] deploy flags to support --stage-rules and --stage-rules during deploy

- conf/global.json
- manage.py
- stream_alert/rule_processor/handler.py
- stream_alert/rule_processor/rules_engine.py
- stream_alert/shared/rule.py
- stream_alert/shared/rule_table.py
- stream_alert/shared/stats.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
- tests/unit/stream_alert_shared/test_rule.py
- tests/unit/stream_alert_shared/test_rule_table.py
- tests/unit/stream_alert_shared/test_stats.py
size: medium
Now that there is a rule table, the rule processor needs the ability to check the table for information on whether or not a rule is staged, etc.
* Making a temporary update to the CLI so the default for deploy does NOT put new rules into staging.
* Note: this will be reverted when the rule promotion lambda is in place & live.
* Fixing bug in firehose region lookup in the env.
* Adding a `_RULE_TABLE` class property to the `RulesEngine` that is cached throughout executions. It will be refreshed (aka recreated) if the configurable `refresh_minutes` have passed since the last refresh.
* Fixing stutter in `Rule.rule_name` attribute naming (renamed to `Rule.name`)
* Adding `is_staged` method to `Rule` class to allow rules to …
> rule processor - adding check for staged rules

- manage.py
- stream_alert/shared/rule.py
- terraform/modules/tf_stream_alert/iam.tf
to: @chunyong-lin or @austinbyers 
size: small
Discovered some small bugs related to rule staging that needed addressed.
* Adding IAM perms so the rule processor can read rule table (`dynamodb:Scan`)
* Fixing CLI help message in `manage.py`
* Ensuring rule info is returned before looking up staged status
Deployed to test
> assortment of small fixes to rule staging

- stream_alert/shared/helpers.py
- tests/unit/stream_alert_rule_processor/test_threat_intel.py
to: @ryandeivert or @strcrzy 
size: small
resolves N/A
Some ip address field actually contains a subnet. We need to handle `ValueError` when try to case a subnet to an `IPAddress` object. Also, we will return `Falso` early if the ip address is `::1`. 
* Return earlier if address is `::1`. 
* Widen exception handling in helper `valid_ip`.
* Add unit test case responding to the fix.
* Rule testing
```
...
```
* Unit testing
```
...
Ran 690 tests in 13.114s
OK
```
> [threat intel] handle more exceptions when processing IP IOCs

- stream_alert_cli/terraform/streamalert.py
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert/variables.tf
- terraform/modules/tf_stream_alert_globals/output.tf
- tests/unit/stream_alert_cli/terraform/test_generate.py
size: small
* Referencing the rules table ARN from the globals module instead of hard coding.
> using rules table arn from tf globals module

- requirements-top-level.txt
- requirements.txt
- stream_alert/alert_processor/outputs/carbonblack.py
- stream_alert_cli/manage_lambda/package.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_carbonblack.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
to: @ryandeivert @austinbyers 
cc: @chunyong-lin 
size: small
This feature aims to automate binary hash banning, using the CarbonBlack API through the use of an output. 
1. The output receives the `md5hash value` from the StreamAlert rule processor
2. The Carbon Black API (cbapi) takes the `md5hash value` and checks whether it is currently banned on the CB Enterprise Response Cloud.
3. If True, the cbapi then checks if the banned hash is enabled.  If True, the automation is exited.
4. If the `md5hash value` is not enabled (False), a command is sent to enable the hash.
5. If the `md5hash value` does not exist (False), an object is created that includes the binary hash value, banned hash text and checks the bit for the enabled feature.
6. If unsuccessful, a log is recorded. …
> Add a Carbon Black output for hash banning using the CBAPI

- stream_alert/rule_processor/rules_engine.py
- stream_alert/shared/utils.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
to: @ryandeivert @austinbyers 
size: median
resolves #717 
In current Data Normalization implementation, Data Normalization is applied to a record right before rule matching. So one record may be normalized multiple times when there are different rules using different `datatypes`. For example,
* Rule 1 
```
@rule(datatypes=['command'], ...)
def rule_get_commands(rec):
...
```
* Rule 2
```
@rule(datatypes=['sourceAddress'], ...)
def rule_get_ip_address(rec):
...
```
* Rule 3
```
@rule(datatypes=['command', `sourceAddress`], ...)
def rule_get_command_and_ip_address(rec):
...
```
In this case, one record will be normalized 3 times!!! The performance will become bottleneck when you will thousands records read from files from S3 bucket, and it will result …
> [Data Normalization] Improve performance

- stream_alert/alert_processor/outputs/aws.py
- stream_alert/rule_processor/firehose.py
- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_lambda/output.tf
- tests/unit/conf/outputs.json
- tests/unit/stream_alert_alert_processor/test_outputs/test_aws.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
- tests/unit/stream_alert_rule_processor/test_firehose.py
size: medium
resolves #708 
resolves #609 
This PR is a combination of several small fixes, including Terraform 0.11.X support, various Firehose tweaks, and a new output for easily getting up and running with StreamAlert.  Having a Cloudwatch Log output allows users to quickly setup StreamAlert end-to-end without building additional infra or plugging in SaaS applications.
* Support Terraform 0.11.X, and update the AWS provider.
* Add a new `CloudwatchLog` AWS output which simply logs alerts to the alert processor log stream.
* Reset the Firehose client if an error is raised - This was suggested by AWS as a potential fix to 
#478 
Locally with unit tests, deployed in a side account to verify end-to-end flow on all features
> Terraform 0.11.X, Cloudwatch Log Output, Firehose Bug Fixes

- docs/source/outputs.rst
- stream_alert/alert_processor/main.py
- stream_alert/alert_processor/outputs/aws.py
- stream_alert/alert_processor/outputs/carbonblack.py
- stream_alert/alert_processor/outputs/github.py
- stream_alert/alert_processor/outputs/jira.py
- stream_alert/alert_processor/outputs/komand.py
- stream_alert/alert_processor/outputs/output_base.py
- stream_alert/alert_processor/outputs/pagerduty.py
- stream_alert/alert_processor/outputs/phantom.py
- stream_alert/alert_processor/outputs/slack.py
- tests/unit/stream_alert_alert_processor/test_main.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_aws.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_carbonblack.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_github.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_jira.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_komand.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_phantom.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_slack.py
size: medium
I noticed that the way logging 'success' or 'failures' during alert dispatching was sort of janky. This updates the way logging occurs to make it much easier for someone to implement an alert output and not reason about logging statuses.
* The alert output's `_dispatch` method now just returns True or False, depending on success or failure.
* Updating the output base class's `dispatch` method to call the subclass `_dispatch` method and handle the status logging of the result.
* Updating the alert processor to remove a now unnecessary method (`_send_alert`).
* Updates to documentation to explain the new interface for this.
* Updating all unit tests for the changes made.
> better alert processor output success/failure logging

- stream_alert/alert_processor/outputs/slack.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_slack.py
size: small
We observed issues with the `SlackOutput` where many thousands of attachments could be included with a message.
* Fixing an issue with message splitting that was a result of the message not containing any new line characters (or no new line characters within the max message size limit).
* If new lines do not exist in the range, we will fall back on splitting on the last _space_ in the chunk of text.
* If neither space nor new lines exists in the chunk of text, we will split on the max message size, ignoring delimiters altogether.
* Simplifying the attachment generation code significantly.
* Adding tests for the various characters (or lack there of) we can split one (new line, space, none).
* Adding test for the max …
> fixing bug where slack messages would split on each character if no newline existed

- stream_alert/rule_processor/payload.py
- stream_alert_cli/test.py
- tests/unit/stream_alert_rule_processor/test_payload.py
to: @austinbyers or @ryandeivert 
size: small
To ensure Lambda's disk space is cleared on each invocation, let's shred the temp directory.
* Shred temp
* Update tests
* Round for file sizes
Local, CI, and deployed in a side account
> [payload] shred the tmp directoy before downloading s3 objects

- terraform/modules/tf_stream_alert_monitoring/main.tf
to: @austinbyers or @chunyong-lin 
size: small
The Terraform module for `monitoring` is used to create CloudWatch alarms when certain thresholds are passed.  When alarms are triggered, a message is sent to an SNS topic, which can be subscribed by PagerDuty.
While digging through [PagerDuty documentation](https://www.pagerduty.com/docs/guides/aws-cloudwatch-integration-guide/), I discovered that the alarm wasn't configured to report back to SNS when alarms recover, which can auto resolve PagerDuty incidents.
* Send messages to the cloudwatch monitoring SNS topic when the triggered alarm recovers
Deployed in a test account
> [tf] send message to SNS topic when alarms recover

- stream_alert/rule_processor/firehose.py
to: @jacknagz or @chunyong-lin 
size: small
The vast majority of our lambda execution time is spent trying to send data to firehose via boto3. This can cause timeouts, etc. The AWS kinesis team suggested shortening the connect and read timeouts to cause retries to happen faster. It's our understanding that if the connect or read takes anything over a few seconds, it's likely not going to succeed at all. Therefore, it's advantageous to just have the attempt killed at retried sooner.
* As suggested, this changes the connect and read timeouts for boto3 via settings in a botocore.client.Config.
* Adding logger statement that will track firehose `FailedPutCount` values that are greater than 0.
> adding connect and read timeouts for firehose client

- stream_alert/rule_processor/firehose.py
- tests/unit/stream_alert_rule_processor/test_firehose.py
to: @jacknagz 
size: small
If firehose fails to send some records within a batch of records, the response will identify which ones failed to send. We can leverage this information to only retry items that failed, instead of retrying the entire batch.
* Fixing issue with firehose client reset when a backoff exception occurs.  This resets the client with the proper config, which includes connect and read timeout information.
* Adding logic to only retry firehose records that have failed to send in the batch. This modifies the list of records by reference, and the backed-off function will see the new, modified list.
Tested in a local script with backoff and adding unit tests for the function that performs the stripping of successful records from the batch.
> [firehose] only retry failed records when re-calling put_record_batch

- stream_alert/rule_processor/firehose.py
size: small
resolves NA
The PR #736 adding timeout when sending records to firehose, so we need to retry when firehose read timeout happened.
* Handle firehose read timeout.
* Rule testing
```
...
```
* Unit testing
```
...
Ran 736 tests in 12.525s
OK
```
> [firehose] backoff when firehose read timed out

- stream_alert/rule_processor/firehose.py
- tests/unit/stream_alert_rule_processor/test_firehose.py
size: small
The current firehose request wrapper function will always log the original batch size when sending the firehose. This doesn't give us an idea of how many records are being _retried_ if they failed to send with the original request.
* Fixing the logger statement to log the amount of messages being sent currently (which could be different than the original/total batch size if this is not the first attempt).
> [firehose] fixing logger message to print count of messages being tried

- stream_alert/rule_processor/parsers.py
- tests/unit/stream_alert_rule_processor/test_parsers.py
size: small
When on-boarding space delimited logs, I ran into a bug where a configured space delimiter would load as unicode and not as a str, which caused an error in the CSV library.
* Cast all delimiters as strings
* Add a unit test
Unit testing!!!!1
> Support Space Delimited Logs

- stream_alert_cli/terraform/flow_logs.py
- terraform/modules/tf_stream_alert_flow_logs/variables.tf
size: small
Found a bug where passing `log_retention` into the `flow_logs` module did nothing
* Make it work!
Locally with Terraform in a side account
> [tf] support custom log retention in vpc flow log groups

- stream_alert_cli/terraform/cloudwatch.py
- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_stream_alert_cloudwatch/README.md
- terraform/modules/tf_stream_alert_cloudwatch/iam.tf
- terraform/modules/tf_stream_alert_cloudwatch/main.tf
- terraform/modules/tf_stream_alert_cloudwatch/variables.tf
- tests/unit/conf/clusters/advanced.json
- tests/unit/stream_alert_cli/terraform/test_generate.py
to: @jacknagz for CLI, @austinbyers for tf
size: medium
To enable cross-account ingestion from a CloudWatch Log group subscription, StreamAlert needs to create CloudWatch Log destination to collection the logs.
* Adding a new terraform module (`tf_stream_alert_cloudwatch`) that will create a CloudWatch Log destination in each available region.
* Creates the following in _each region_:
* IAM role that will grant CloudWatch Logs the permission to put data into your Kinesis stream.
* Permissions policy to define which actions CloudWatch Logs can perform.
* `kinesis:PutRecord` for the Kinesis stream
* `iam:PassRole` for the previously created IAM role
* A CloudWatch Log destination that points to the cluster's default Kinesis stream.
* Policy that defines …
> [tf][cli] add cross-account cloudwatch logs support

- conf/logs.json
- stream_alert/rule_processor/parsers.py
- tests/integration/rules/cloudwatch/cloudtrail_via_cloudwatch.json
- tests/unit/conf/logs.json
- tests/unit/stream_alert_rule_processor/test_parsers.py
size: small
Logs that are ingested via CloudWatch logs subscription filter have a unique format. The format is described [here in step 8 under Example # 1](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html). The `message` objects within the list of `logEvents` are stored as embedded json objects. However, currently, there is no easy way to use a json path in combination with loading an embedded json object. This adds support for loading of embedded json objects for json records extracted via a json path.
* Adding new `logs.json` config option of `embedded_json` that is a boolean indicating if the extracted json object is an embedded object (encoded json within json).
* Adding json loading logic for …
> [parsers] add cloudtrail via cloudwatch logs support

- terraform/modules/tf_stream_alert_cloudwatch/iam.tf
- terraform/modules/tf_stream_alert_cloudwatch/outputs.tf
to: @austinbyers or @jacknagz 
size: small
Most AWS resource names have a 64 character limit. This `cloudwatch_subscription_role` IAM role resource name easily exceeds that in most cases and needs to be shortened.
* Shortening resource name so it shouldn't typically overflow the 64 character limit.
Terraform plan successfully with this module enabled.
> [tf] shortening resource name due to 64 char limit and adding role arn output

- helpers/base.py
- requirements-top-level.txt
- tests/unit/stream_alert_rule_processor/test_rule_helpers.py
cc: @ryandeivert 
size: small
Needed to support the use of path specific wild carding. See difference between fnmatch() and PurePath().match() below.
* Added path_matches_any() to helpers/base.py
* Added unit testing for path_matches_any()
Local Unit Testing
```
$ nosetests -s -v ~/repos/streamalert/tests/unit/stream_alert_rule_processor/test_rule_helpers.py
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Helpers - Path Matches Any ... ok
Helpers - Starts With Any ... ok
Helpers - Starts With Any ... ok
Helpers - Contains Any ... ok
Helpers - Matches Any ... ok
Helpers - Last Hour ... ok
Helpers - Fetch values from a record by normalized type ... ok
Helpers - Loading valid JSON ... ok
Helpers - Loading invalid JSON ... ok …
```
> Adding Helper Function To Support Wildcards With Specific Path Matching

- conf/lambda.json
to: @ryandeivert, @airbnb/streamalert-maintainers
size: small
Lambda config needs to have third party libraries specified
* Added lib name to lambda.json
none needed
> Adding pathlib2 to lambda.json file

- stream_alert_cli/terraform/cloudtrail.py
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/variables.tf
- tests/unit/stream_alert_cli/terraform/test_generate.py
size: medium
The cloudtrail terraform module currently supports sending cloudtrail logs to an s3 bucket, but does not support sending to a CloudWatch logs group. Sending to a CloudWatch Logs group would allow for sending to kinesis (skipping s3 altogether). 
* Updating the cloudtrail terraform module to optionally support sending logs to a CloudWatch logs group (along with the default s3 bucket).
* Fully deployed and enabled in test account.
* Updated unit tests for new cloudtrail module generation.
> [tf] cloudtrail to cloudwatch to kinesis support

- stream_alert_cli/terraform/cloudtrail.py
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/variables.tf
- terraform/modules/tf_stream_alert_cloudwatch/iam.tf
- terraform/modules/tf_stream_alert_cloudwatch/outputs.tf
to: @jacknagz or @austinbyers 
size: small
A bug was found with the policy doc that should allow `logs:PutSubscriptionFilter` for the cloudwatch destination.
* Fixing bug by using the destination arn and not the kinesis stream arn the destination points to.
* Using the output of the destination arn as the destination in the subscription filter of the CloudTrail module.
* Applied changes in test deploy with much success.
> [tf] fixing bug with policy resource value

- stream_alert/rule_processor/rules_engine.py
- stream_alert/shared/lookup_tables.py
- stream_alert_cli/helpers.py
- stream_alert_cli/test.py
- tests/unit/conf/global.json
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
- tests/unit/stream_alert_shared/test_lookup_tables.py
to: @ryandeivert or @austinbyers 
size: medium
resolves N/A
This PR is to support lookup tables in Rule Processor. The lookup tables are globally shared and can be referenced in a rule. 
The lookup tables feature will download json files from S3 buckets and load them into memory. The buckets info can be configured in `conf/global.json`, for example,
```
"infrastructure": {
"lookup_tables": {
"buckets": {
"bucket_name": [
"foo.json",
"bar.json"
]
},
"cache_refresh_minutes": 10,
"enabled": false
},
...
}
```
* Add a new class LookupTables to handle downloading files from S3 buckets and loading them into memory. It also refreshes lookup tables, similar to how to refresh rule table.
* Mock S3 bucket for integration and unit testing.
* Rule testing
``` …
```
> [lookup_tables] Support lookup tables

- stream_alert_cli/terraform/cloudtrail.py
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/variables.tf
size: small
It's possible to enable the `cloudtrail` module in a different cluster than the `cloudwatch` module, but the cloudtrail module needs access to a destination arn from the cloudwatch module in order to send events to it.
* Adding support for a config option to supply a destination arn that is different than the current cluster's destination arn.
Applied and deployed 👏
> [cli][tf] adding ability to send cloudtrail to another cluster's cloudwatch destination

- conf/logs.json
- stream_alert/rule_processor/parsers.py
- tests/integration/rules/cloudwatch/cloudtrail_via_cloudwatch.json
- tests/integration/rules/cloudwatch/rds_aurora_via_cloudwatch.json
- tests/unit/stream_alert_rule_processor/test_parsers.py
size: medium
Some logs are csv format, but are embedded within a json object. Ideally, these could be extracted and still parsed as csv.
* Adding support to the csv parser to allow for extracting csv data via a json_path.
* Migrating some of this parsing from the `JSONParser` to the `ParserBase` class to be used across the subclasses.
* Adding support for extracting 'envelope' keys for csv-in-json logs.
* This logic was largely migrated from the `JSONParser` class to `ParserBase` with some exceptions. This can be improved at a later date.
* Adding log patterns to `cloudwatch:control_message` so it does not get misclassified as another log type.
* Adding `cloudwatch:rds_aurora` schema that leverages the new csv-in-json logic to extract …
> [parsers] support csv embedded within json logs

- helpers/base.py
- setup.cfg
- stream_alert_cli/test.py
- tests/unit/stream_alert_rule_processor/test_rule_helpers.py
to: @strcrzy 
size: small
For rules which are very noisy, it may be helpful to return only a sample of the true positives.
* Add a `random_bool` base helper function
* Unit tests and pylint
> Add random_bool helper function

- stream_alert_cli/manage_lambda/deploy.py
size: small
There is a bug where the IAM resources for apps are not added to the terraform targets during a deploy of the apps functions.
* Fixing bug by adding the iam tf targets alongside the lambda tf targets during deploy of the apps functions.
No unit tests but tested by doing a generate locally to make sure all the proper targets are included.
> [apps] fixing terraform bug where app iam would not be targeted during deploy

- stream_alert_cli/terraform/athena.py
- terraform/modules/tf_stream_alert_athena/iam.tf
- terraform/modules/tf_stream_alert_athena/kms.tf
- terraform/modules/tf_stream_alert_athena/main.tf
- terraform/modules/tf_stream_alert_athena/variables.tf
- terraform/modules/tf_stream_alert_globals/main.tf
- tests/unit/stream_alert_cli/terraform/test_athena.py
size: small
contributes to: #758 
We will be encrypting all StreamAlert data at rest, and Dynamo and SQS are the easiest to start with.  For reference, https://github.com/airbnb/binaryalert/pull/121 is a similar PR which enabled server-side encryption for BinaryAlert
* Enable server-side encryption for the alerts and rules DynamoDB tables
* We'll do the optional threat intel table later
* Enable server-side encryption of the only SQS queue (athena_partition_refresh) using a newly created KMS key
**WARNING**: Applying this change will delete your existing alerts table. Make sure it is empty (with no pending alerts) before re-creating it
* Deployed from scratch in a test account. Used the AWS console to verify the two tables and the …
> Enable server-side encryption for alerts/rules tables and SQS

- app_integrations/main.py
size: small
All (most?) of our other Lambda functions import `absolute_import`, which suppresses errors in AWS Lambda logs related to `unable to import...`.
* Adding the absolute import line to the apps function as well.
> using absolute import to get rid of aws lambda import warning

- terraform/modules/tf_threat_intel_downloader/iam.tf
size: small
resolves N/A
In PR #728 we changed to use [get_parameter](https://github.com/airbnb/streamalert/blob/master/stream_alert/threat_intel_downloader/main.py#L87) rather than use `get_parameters`. So we need `ssm:Get*` permission.
* Use `ssm:Get*` for threat intel downloader role.
This is terraform change. Run `terraform plan` internally, and plan will only change threat intel download ssm permission.
> Fix threat intel downloader permission

- terraform/modules/tf_stream_alert_monitoring/main.tf
size: small
resolves N/A
The PR #734 enables CloudWatch alarm recovery and it helps resolving alarms more efficient. But lambda invocation errors are considered to be critical ones. We should have the awareness and know when and why there are lambda invocation errors. Remove alarm recovery from lambda invocation errors, so we will get paged event the errors are not consistent anymore.
* Remove `ok_action` from lambda invocation error metric alarm.
It is terraform code change, integration and unit tests won't be affected.
> [tf] remove alarm recover from lambda invocation errors

- stream_alert/shared/lookup_tables.py
- tests/unit/stream_alert_shared/test_lookup_tables.py
to: @austinbyers or @ryandeivert 
size: small
resolves #766
* Check issue #766 
* Handle `TimeoutError` while streaming S3 file. Catch this will both catch `ReadTimeoutError` and `ConnectionTimeoutError`. Refer to source code [here](https://github.com/boto/botocore/blob/master/botocore/vendored/requests/packages/urllib3/exceptions.py#L95).
* Unit test
```
...
LookupTables - Read file from S3 timeout ... ok (0.0532s)
...
Ran 751 tests in 11.802s
OK
```
> [lookup_tables] handle read timeout error

- stream_alert_cli/terraform/cloudtrail.py
- tests/unit/stream_alert_cli/terraform/test_generate.py
size: small
Since the `event_pattern` is a json object, and our configs are json, we do not need to double encode it within our configs.
* Removing the requirement that the event pattern be embedded json within the cluster config for the cloudtrail module.
Updating tests for change.
> no longer double-encoding event pattern json for cloudtrail config

- conf/global.json
- stream_alert_cli/config.py
- stream_alert_cli/terraform/generate.py
- tests/unit/conf/global.json
- tests/unit/helpers/base.py
- tests/unit/stream_alert_cli/terraform/test_generate.py
size: small
Having the terraform state bucket and S3 logging bucket configurable gives users flexibility in where they store these files.
* Adds S3 access logging as a top-level config option.
* Fixes a bug where the existing terraform bucket and key in the config are ignored
For both of these, the bucket listed in the config is the one which is used, and it will be automatically created only if `create_bucket = True` (which it is by default, for backwards compatibility)
* Deployed to a test account with the default option (create buckets automatically)
* Switch both terraform state and access logging to other, existing buckets:
```
Terraform will perform the following actions:
- aws_s3_bucket.logging_bucket
~ …
```
> Make terraform state and s3 logging buckets configurable

- stream_alert_cli/terraform/rule_promotion.py
- terraform/modules/tf_rule_promotion_iam/main.tf
- terraform/modules/tf_rule_promotion_iam/variables.tf
- tests/unit/stream_alert_cli/terraform/test_rule_promotion.py
size: small
The Rule Promotion lambda logged an error of:
`Query 61aa0909-9608-427a-9df3-c7def32f516f FAILED with reason Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 12345), exiting!`
* Fixing s3 permission for reading athena data
Updating unit test and deployed.
> updating rule promo perms to allow reading athena data from s3

- stream_alert/rule_promotion/promoter.py
- stream_alert/rule_promotion/publisher.py
- stream_alert/rule_promotion/statistic.py
- stream_alert/shared/athena.py
- stream_alert/shared/rule.py
- tests/unit/stream_alert_rule_promotion/test_publisher.py
- tests/unit/stream_alert_shared/test_athena.py
- tests/unit/stream_alert_shared/test_rule.py
size: small
When I observed the error noted in #778, I realized athena errors could be handled/propagated better. For instance, errors such as that one should have resulted in a AWS Lambda error, but instead was just logged as an error.
* Introducing an `AthenaQueryExecutionError` exception class that should be used to raise any errors that occur during the execution process.
* Updating all applicable areas where errors/exceptions that were previously just logged should probably bubble up and either cause and exception or be handled by the caller.
* Updating calling code to be more concise and handle exceptions where necessary.
* Removing some now unnecessary return result checks, since exceptions will be raised when the return result …
> updates to raise appropriate errors from athena client, etc

- stream_alert_cli/manage_lambda/deploy.py
- terraform/modules/tf_rule_promotion_iam/main.tf
size: small
There is a bug that will not update the rule table if the following command is used:
`python manage.py lambda deploy --processor all`
* Fixing bug to update the rule table if any of the deployed functions is the rule processor.
* Adding permission for `glue:GetPartition` to rule promotion function iam.
Tested in deploy.
> ensuring rule table is updated if any of the deployed functions is the rule processor

- app_integrations/config.py
- tests/unit/app_integrations/test_config.py
size: small
Occasionally, apps functions can timeout when reading the config from ssm. Shortening the boto connect/read timeout may assist with this. 
* Shortening the boto client connect and read timeout to 5 seconds (from the default of 60).
No real testing needed - updating old unit tests.
> adding boto config ssm read and connect timeout too apps config loading

- stream_alert/rule_processor/rules_engine.py
- tests/unit/stream_alert_rule_processor/test_rules_engine.py
size: small
resolves #787 Required subkey check fails when the subkey exists, but the value is false
Subkeys with False or None values should still cause the rule to be run
* Required subkeys with none or false values should still cause the rule to be run.
* Using `any()` instead of `all()` should be faster, as `any()` can exit early if a subkey is missing.
* Check the type of the subkey item to make sure it is a dictionary
* Added `test_process_subkeys_false_none_value` to test `None` and `False` values for subkeys.
* Added `test_process_subkeys_non_dict` to make sure non dictionary subkey objects are handled.
1. Created a new unit tests `test_process_subkeys_false_none_value` and `test_process_subkeys_non_dict`
2. Tests fail
3. Implemented fix in …
> [core] allow req_subkeys with none and false values

- stream_alert_cli/terraform/rule_promotion.py
- terraform/modules/tf_rule_promotion_iam/main.tf
- terraform/modules/tf_rule_promotion_iam/variables.tf
- tests/unit/stream_alert_cli/terraform/test_rule_promotion.py
size: small
The rule promotion Lambda function needs permission to use the KMS key for the Athena table
* Grant `kms:Decrypt` for rule promotion Lambda
* Test deploy
> Grant rule promotion Lambda kms:Decrypt permissions for Athena

- stream_alert/shared/rule.py
- tests/unit/stream_alert_shared/test_rule.py
to: @chunyong-lin, @jbussing 
size: small
The introduction of the `Rule` class broke the rule `__doc__` string replacement for description substitution.
This change introduces a non-hacky way of replacing a rule's description with an alternate value.
* The default description will be the rule's current docstring, but can be overridden with `rule_name.description = ...` within the rule itself.
Adding unit test to ensure the replacement happens as expected.
> adding better support for description replacement within rule

- app_integrations/apps/README.rst
- app_integrations/apps/aliyun.py
- conf/logs.json
- conf/sources.json
- docs/source/app-configuration.rst
- requirements-top-level.txt
- requirements.txt
- stream_alert_cli/manage_lambda/package.py
- tests/integration/rules/aliyun/aliyun_basic.json
- tests/unit/app_integrations/test_apps/test_aliyun.py
- tests/unit/app_integrations/test_apps/test_app_base.py
- tests/unit/app_integrations/test_helpers.py
cc: <optional-cc-to-specific-users>
size: medium
SteamAlert doesn't have an app that collects ActionTrail events from Aliyun
* Adds an app that collects ActionTrail events from Aliyun
* Schema definition for the new log type is included
* Unit tests for the app as well as schema validation tests are included
* Documentation for authorizing the app is included in the README in the apps directory as well as in a section of the app-configuration.rst in the docs directory
Barebones StreamAlert session created, the Aliyun app configured and deployed, and verifying that events are listed as captured in the log
> [apps] Aliyun ActionTrail app

- app_integrations/apps/README.rst
- stream_alert_cli/manage_lambda/package.py
size: small
Observed the following error with the latest streamalert apps deploy:
```
module initialization error
Cannot load native module 'Crypto.Hash._SHA256': Trying '_SHA256.so': cannot load library /var/task/Crypto/Util/../Hash/_SHA256.so: /var/task/Crypto/Util/../Hash/_SHA256.so: invalid ELF header. Additionally, ctypes.util.find_library() did not manage to locate a library called '/var/task/Crypto/Util/../Hash/_SHA256.so', Trying '_SHA256module.so': cannot load library /var/task/Crypto/Util/../Hash/_SHA256module.so: /var/task/Crypto/Util/../Hash/_SHA256module.so: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called …
```
> adding precompiled libs for aliyun streamalert app

- stream_alert_cli/terraform/generate.py
- stream_alert_cli/terraform/rule_promotion.py
- terraform/modules/tf_rule_promotion_iam/main.tf
- terraform/modules/tf_stream_alert/iam.tf
- terraform/modules/tf_stream_alert_globals/main.tf
- terraform/modules/tf_stream_alert_globals/output.tf
- terraform/modules/tf_stream_alert_globals/variables.tf
- tests/unit/stream_alert_cli/terraform/test_rule_promotion.py
size: small
If the rule staging feature is not enabled, the rules dynamo table does not need to be created.
* Adding a conditional to only create rules table if staging is enabled.
* Updating other dependent resources.
* Adding check to only allow the rule promotion lambda to be created if the rule_staging feature is enabled
* Performed a `python manage.py terraform build` with setting enabled and disabled, and ensured the right resources would be created.
* Added unit test to ensure rule promo lambda module is not created.
> [rule-staging] only creating rules table if rule staging is enabled

- stream_alert_cli/terraform/rule_promotion.py
size: tiny
* removing trailing comma silly typo in comment
> removing trailing comma typo in comment

- conf/logs.json
- tests/integration/rules/mitre_attack/right_to_left_character.json
size: medium
Update schemas for 
* Aliyun ActionTrail where `apiVersion` should be optional.
* CarbonBlack has some new schemas added and schema update.
* Rule testing
```
...
StreamAlertCLI [INFO]: (76/76) Successful Tests
StreamAlertCLI [INFO]: (36/36) Alert Tests Passed
```
> Update schema 08102018

- rules/community/cloudtrail/cloudtrail_mfa_policy_abuse_attempt.py
- tests/integration/rules/cloudtrail/cloudtrail_mfa_policy_abuse_attempt.json
cc: @strcrzy 
size: small
resolves #803 
Because `errorCode` is an optional parameter set in `optional_top_level_keys`. If the record does not contain it, it gets set to the default value for it's type. In this case `str()`.
So checking that the key exists is not enough to indicate an error, instead check the value evaluates to True.
* Only alert if the contents of `errorCode` is not False.
* Added integration test.
* Added new integration test: `Successfully creating an MFA device, while the user is not MFA'd should not create an alert.`
> [rules] cloudtrail_mfa_policy_abuse_attempt rule logic improved

- stream_alert_cli/terraform/athena.py
- terraform/modules/tf_stream_alert_athena/main.tf
- terraform/modules/tf_stream_alert_athena/variables.tf
- tests/unit/stream_alert_cli/terraform/test_athena.py
size: small
I missed a few extra resources in https://github.com/airbnb/streamalert/pull/806.
* Removing `aws_cloudwatch_event_rule` and `aws_cloudwatch_event_target`
Updating unit tests.
> [tf][athena] removing cloudwatch event rule and target

- conf/global.json
- docs/source/firehose.rst
- stream_alert/rule_processor/firehose.py
- stream_alert/rule_processor/handler.py
- stream_alert_cli/athena/handler.py
- stream_alert_cli/helpers.py
- stream_alert_cli/terraform/firehose.py
- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_stream_alert_kinesis_firehose_delivery_stream/main.tf
- terraform/modules/tf_stream_alert_kinesis_firehose_delivery_stream/variables.tf
- tests/unit/conf/global.json
- tests/unit/stream_alert_cli/terraform/test_firehose.py
- tests/unit/stream_alert_cli/terraform/test_generate.py
- tests/unit/stream_alert_rule_processor/test_firehose.py
to: @austinbyers or @chunyong-lin 
size: large
Currently, StreamAlert uses individual AWS Firehose delivery streams for each log type ingested and parsed. This enables a somewhat simple and reliable way to determine if processing of a specific log type has dropped off.
* Slight refactor to StreamAlertFirehose client to make performing some actions easier.
* The prior class required instantiation for performing operations such as determining enabled log types, etc, which was overkill.
* Migrating a few methods to be class methods, since instantiation will create a boto client which is not needed for CLI operations.
* Also renaming from `StreamAlertFirehose` to just `FirehoseClient` since it's less wordy.
* Updating all areas that used this class.
* …
> [tf][firehose] support per firehose metric alarms for IncomingRecords

- stream_alert/athena_partition_refresh/main.py
- terraform/modules/tf_stream_alert_athena/main.tf
size: small
@austinbyers observed the following stack trace:
```
%d format: a number is required, not unicode: TypeError
File "/var/task/stream_alert/athena_partition_refresh/main.py", line 212, in handler
AthenaRefresher().run(event)
File "/var/task/stream_alert/athena_partition_refresh/main.py", line 180, in run
sqs_rec['attributes']['SentTimestamp'])
File "/usr/lib64/python2.7/logging/__init__.py", line 1155, in debug
self._log(DEBUG, msg, args, **kwargs)
File "/usr/lib64/python2.7/logging/__init__.py", line 1286, in _log
self.handle(record)
File "/usr/lib64/python2.7/logging/__init__.py", line 1296, in handle
self.callHandlers(record)
File "/usr/lib64/python2.7/logging/__init__.py", line 1336, in …
```
> [athena] fixing logger format string and using lambda alias for invocation

- stream_alert/apps/app_base.py
size: small
Identified bug from recent refactor that allowed for looping of gather calls to not take into account the time apps may have to 'sleep' between new api requests.
* Adding the sleep seconds returned by the app to the calculated time that would be needed for another request to be successfully made.
> fixing bug where apps could time out between gather calls

- stream_alert/rule_processor/main.py
- stream_alert/rule_processor/parsers.py
size: small
We were seeing some errors of the form `'int' has no attribute 'update'` because:
```python
json.loads("0") == 0  # Returns an integer!
```
* Add a top-level `try: except` around the rule processor to log the invocation event if an exception is raised for easier troubleshooting
* Check if nested records are dictionaries before continuing to process them
* Changes have already been deployed in our account
> Better JSON and top-level error handling

- stream_alert/athena_partition_refresh/main.py
size: small
Currently, the Athena refresh function can be throttled if too many queries happen in a short time. Every time the athena refresh function is invoked, it first checks if the database exists (using 1 query) and then will run another query to perform actions. We can limit our number of queries by caching the athena client, effectively cutting our # of queries in half (most of the time).
Example of error:
```
Athena query failed:
An error occurred (ThrottlingException) when calling the StartQueryExecution operation (reached max retries: 4): Rate exceeded: AthenaQueryExecutionError
File "/var/task/stream_alert/athena_partition_refresh/main.py", line 212, in handler …
```
> caching athena client in partition refresh function to help with throttling

- conf/types_new.json
- stream_alert/classifier/classifier.py
- stream_alert/classifier/normalize.py
- stream_alert/classifier/parsers.py
- stream_alert/classifier/payload/payload_base.py
- tests/unit/streamalert/classifier/payload/test_payload_base.py
- tests/unit/streamalert/classifier/payload/test_payload_record.py
- tests/unit/streamalert/classifier/test_classifier.py
- tests/unit/streamalert/classifier/test_normalizer.py
- tests/unit/streamalert/classifier/test_parsers_base.py
- tests/unit/streamalert/classifier/test_parsers_csv.py
- tests/unit/streamalert/classifier/test_parsers_json.py
- tests/unit/streamalert/classifier/test_parsers_kv.py
to: @strcrzy , @chunyong-lin 
Again, sorry this is fairly large. This largely builds upon in-flight changes in #821, and you'll notice this branch is being PR'd against that branch. This is getting meta, but once that branch merges into the main `ryandeivert-function-split` feature branch, I will switch this PR to the main feature branch.
Follow up to #821 
This adds two more of the core components of the `classifier` function, namely the actual `Classifier` and a `Normalizer` class.
* Some updates to code that is in Part 1 (#821), such as:
* Updating `ParserBase` properties to be more clear, wherein some (most) properties are now protected instead of public. This is mostly so it's obvious what properties should be used be callers.
* Adding a …
> function split part 2, adding classifier and normalizer 

- stream_alert/classifier/classifier.py
- stream_alert/classifier/clients/__init__.py
- stream_alert/classifier/clients/firehose.py
- stream_alert/classifier/main.py
- stream_alert/classifier/parsers.py
- stream_alert/shared/helpers/boto.py
- tests/unit/streamalert/classifier/clients/test_firehose.py
- tests/unit/streamalert/classifier/test_classifier.py
to: @strcrzy , @chunyong-lin 
Follow up to #822
This PR adds the `FirehoseClient` for historical data retention, and also implements the AWS Lambda handler for the `classifier` function. Note that this PR is being compared against the `ryandeivert-func-split-pt-2` branch. All of these will merge into the central `ryandeivert-function-split` branch upon review/approval.
* Updating `FirehoseClient` batching logic to use jsonlines and simplifying it quite a bit through the use of a generator.
* Adding shared helper for boto configs to set default timeouts.
* Adding comprehensive `FirehoseClient` tests and removing moto usage
> function split part 3, adding firehose client for data retention

- manage.py
- stream_alert_cli/apps/handler.py
- stream_alert_cli/athena/handler.py
- stream_alert_cli/config.py
- stream_alert_cli/kinesis/handler.py
- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/manage_lambda/rollback.py
- stream_alert_cli/outputs/handler.py
- stream_alert_cli/rule_table.py
- stream_alert_cli/runner.py
- stream_alert_cli/terraform/generate.py
- stream_alert_cli/terraform/handlers.py
- stream_alert_cli/test/handler.py
- stream_alert_cli/threat_intel_downloader/handler.py
- tests/unit/stream_alert_cli/manage_lambda/test_rollback.py
The CLI has never properly exited with error codes for the various handlers. This PR is to add a uniform interface for returning on errors and exit properly.
* Each CLI handler returns `False` if there is an error, or `True` otherwise.
Ran tests and checked errors code to ensure this is working.
>  properly exiting CLI on errors for all handlers

- requirements.txt
cc: <optional-cc-to-specific-users>
size: small
Currently requirements.txt is missing two dependencies, 
```
pyfakefs
pathlib2
```
Added both and pinned working version
unit tests fail with missing libraries.  (they actually still fail after adding them, but they fail LESS and fail for non-library-missing based reasons)
> adding missing reqs

- stream_alert/apps/_apps/gsuite.py
- tests/unit/stream_alert_apps/test_apps/test_gsuite.py
cc: @ryandeivert 
size: small
The GSuite event de-duplication logic didn't de-duplicate events correctly because the app context was being read before it was correctly initialised.
* Read _context during the first _gather_logs() run, not during __init__()
* Updated the unit test to set the context instead of last_run_event_ids directly
1. Updated the unit test to set the _context instead of last_run_event_ids directly
2. Unit tests pass
3. Deployed to StreamAlert cluster
4. Verify contents of state in parameter store
5. Verify logs in CloudWatch logs
6. Events correctly de-duplicated
> [apps] Fixed bug in GSuite event de-duplication

- manage.py
- stream_alert/rules_engine/rules_engine.py
- stream_alert/shared/lookup_tables.py
- stream_alert_cli/test/handler.py
- stream_alert_cli/test/results.py
- tests/unit/stream_alert_shared/test_lookup_tables.py
* Slight change to the interface used to access lookup tables.
* Adding support for `--quiet` flag during running of tests.
* Using this flag will log tests that fail, but will suppress logging of tests that pass
```
$ python manage.py test rules --quiet
[INFO 2018-11-07 18:03:00,659 (stream_alert_cli.runner:58)]: Issues? Report here: https://github.com/airbnb/streamalert/issues
Running tests for files found in: tests/integration/rules/
Summary:
Total Tests: 77
Pass: 77
Fail: 0
[INFO 2018-11-07 18:03:01,106 (stream_alert_cli.runner:85)]: Completed
```
Updating unit tests
> small change to how lookup tables are accessed and quiet test logging

- stream_alert_cli/manage_lambda/deploy.py
- stream_alert_cli/manage_lambda/rollback.py
- stream_alert_cli/terraform/apps.py
- stream_alert_cli/terraform/monitoring.py
- tests/unit/stream_alert_cli/manage_lambda/test_rollback.py
- tests/unit/stream_alert_cli/terraform/test_monitoring.py
Patrick (@patrickod) reported a bug with the apps function where the destination classifier function did not exist.
* Updating the classifier function name passed to apps in the terraform generation.
* Fixing some other issues related to deploy/rollback functionality.
Deployed this code.
> [bug] updating terraform generate code, and deploy/rollback logic, for apps

- stream_alert_cli/manage_lambda/package.py
* Fixing a bug identified by a user related to packaging of matchers/helpers that are no longer in the same place as previous defined.
> [bug] fixing a bug with matchers and helpers packaging in the rules engine

- stream_alert_cli/manage_lambda/package.py
related to: #859 
Remove mention of the 'helpers' directory from the list of package files for
the AlertMerger and AlertProcessor packages, fixing runtime exceptions that
prevent them from being built.
size: small
Fixes broken package builds introduced by the refactor of the matcher/rule codebase and associated directory structure
Confirmed packages build locally & are executing correctly when deployed
> [bug] remove 'helpers' from alert merger and processor package files

- docs/source/rules.rst
- rules/community/mitre_attack/defense_evasion/multi/obfuscated_files_or_information/right_to_left_character.py
- rules/helpers/base.py
- stream_alert/alert_processor/main.py
- stream_alert/classifier/classifier.py
- stream_alert/rules_engine/threat_intel.py
- stream_alert/shared/__init__.py
- stream_alert/shared/normalize.py
- stream_alert/shared/utils.py
- tests/unit/stream_alert_alert_processor/test_main.py
- tests/unit/stream_alert_shared/test_normalizer.py
- tests/unit/streamalert/rules_engine/test_threat_intel.py
Rules using `datatypes` (aka normalization) will break with this change. Rule tests should identify this, but all rules should be updated to use the `Normalizer` class like so:
```python
from stream_alert.shared.rule import rule
from stream_alert.shared.normalize import Normalizer
@rule(...)
def test_rule(rec):
value = Normalizer.get_values_for_normalized_type(rec, 'normalized_type')
return value == 'bad_value'
```
The current data normalization stores _paths_ to values instead of the raw values. In turn, this requires more overhead when performing lookups for the actual normalized value.
* Moving the normalization logic (ie: `Normalizer` class) to the shared module.
* Migrating the `fetch_values_by_datatype` method to the …
> update normalization logic to store raw values instead of paths to values in json

- stream_alert_cli/config.py
- tests/unit/stream_alert_cli/test_cli_config.py
Third party packages that are dependencies for the function out of the box are included in the [packaging logic](https://github.com/airbnb/streamalert/blob/master/stream_alert_cli/manage_lambda/package.py#L287) and therefore should not be included in the user config.
* Removing duplicative dependency of `requests` for the `threat_intel_downloader` package.
Updating unit test.
> [bug] removing threat_intel packaging third party packages from config

- stream_alert_cli/terraform/generate.py
- stream_alert_cli/terraform/metrics.py
A bug where the wrong value is being used for custom metric alarms prevent custom alarms from being created. I also discovered a bug with the `source` key in the custom metric alarm generation. A trailing comma was causing the value to become a list when dumped to json.
Error from Terraform: `Error loading configuration: Error loading /Users/ryan_deivert/airrepos/streamalert/terraform/metric_alarms.tf.json: Error parsing source for metric_alarm_alert_merger_0: At -: root: unknown type for string *ast.ListType`
* Fixing variable for json dumping.
* Removing trailing comma.
> [bug] fixing bug with custom metric alarm generation

- stream_alert/__init__.py
- stream_alert/alert_merger/main.py
- stream_alert/classifier/clients/sqs.py
- stream_alert/shared/alert.py
- stream_alert/shared/normalize.py
- tests/unit/stream_alert_shared/test_alert.py
- tests/unit/stream_alert_shared/test_normalizer.py
cc: @airbnb/streamalert-maintainers, @patrickod 
Current messages being sent to SQS can contain sets that are a result of inserting 'normalized' data into the record. This is byproduct of changes made [here](https://github.com/airbnb/streamalert/pull/854/files#diff-4c63584097304cf3ed86ce070f20b238R61).
Traceback provided by @patrickod:
```
set(['INSERT_IP_HERE']) is not JSON serializable: TypeError
File "/var/task/stream_alert/classifier/main.py", line 27, in handler
Classifier().run(event.get('Records', []))
File "/var/task/stream_alert/classifier/classifier.py", line 249, in run
self.sqs.send(self._payloads)
File "/var/task/stream_alert/classifier/clients/sqs.py", line 178, in send
records = self._payload_messages(payloads)
File …
```
> [bug] adding list serialization for sets to messages sent to sqs

- stream_alert/athena_partition_refresh/main.py
- stream_alert/rules_engine/alert_forwarder.py
- tests/scripts/rule_test.sh
- tests/unit/stream_alert_athena_partition_refresh/test_main.py
to: 
related to:
resolves:
Fix some small spelling mistakes. For rule_test.sh script, forward bash arguments for convenience.
Only major change is passing `$@` to `rule_test.sh`. I found it convenient to use `./tests/scripts/rule_test.sh` as a layer of indirection to `./manage.py test rules`, but would require me to write out the special options, such as `./manage.py test rules --test-files xxxxyyyyzzzz.json`.
If the intention of the `rule_test.sh` script is NOT to indirect `manage.py` then my logic is probably wrong and I can get rid of this stuff.
`rule_test.sh`
```
Summary:
Total Tests: 77
Pass: 77
Fail: 0
[INFO 2019-01-07 17:46:41,715 (stream_alert_cli.runner:85)]: Completed
```
`unit_test.sh`
```
...
stream_alert/threat_intel_downloader/__init__.py …
```
> Small fixes; pass cli args to rule_test.sh

- stream_alert/alert_processor/outputs/credentials/provider.py
- stream_alert/alert_processor/outputs/output_base.py
- stream_alert_cli/outputs/handler.py
- tests/unit/stream_alert_alert_processor/helpers.py
- tests/unit/stream_alert_alert_processor/test_outputs/credentials/test_provider.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_output_base.py
related to:
resolves:
This PR sits on top of #875, in response to [this comment](https://github.com/airbnb/streamalert/pull/875#discussion_r248055606). I split this into a separate PR to make it easier to understand.
I split out the new `OutputCredentialsProvider` guts into this new concept—`CredentialsProvidingDriver`. The idea is these drivers each are strategies for fetching Credentials from **somewhere**.
I implemented 4 drivers: S3, local files, spooled file, and ephemeral. I tried to design the interface to be plug-and-play-ready for a SSM migration in the future (#240).
The new algorithm can be found in `setup_drivers()`. The pseudocode works like this:
* Ask Ephemeral Driver if credentials are already cached in memory. If so, …
> Refactors Drivers for OutputCredentialsProvider

- stream_alert/classifier/clients/firehose.py
- stream_alert/classifier/clients/sqs.py
- stream_alert_cli/helpers.py
- stream_alert_cli/terraform/handlers.py
resolves: #863 
resolves: #865 
resolves: #866 
resolves: #873 
Some boto3 clients (sqs and firehose) experience some sporadic/transient issues that AWS has informed us should be retried.
* Catching exceptions in `SQSClient` and `FirehoseClient` and retrying.
* Fixing bug in `list-targets` cli command that was unnecessarily checking for AWS creds.
* Better logging of errors related to expired token when checking for AWS creds.
> catching errors in firehose and sqs clients to be retried

- README.rst
Super small change; I noticed the link to the "getting started" was going nowhere.
> Fixes broken link in README

- stream_alert/alert_processor/outputs/demisto.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_demisto.py
For whatever reason, Demisto considers integers to be invalid JSON inputs for some specific fields. Example, if you send a label:
```
{ 
"labels": [
{
"type": "this_type",
"value": 0,
}
]
}
```
It just rejects the request entirely:
```
{
"id": "bad_request",
"status": 400,
"title": "Bad request",
"detail": "Request body is not well-formed. It must be JSON.",
"error": "json: cannot unmarshal number into Go value of type string",
"encrypted": false,
"multires": null
}
```
The fix is to type-cast all JSON values to strings.
```
--------------------------------------------------------------------------------------------
TOTAL                                                           4732    104    98%
[success] 6.60% …
```
> [demisto] Fixes a bug where demisto rejects non-string types

- stream_alert/alert_processor/outputs/aws.py
- stream_alert/alert_processor/outputs/carbonblack.py
- stream_alert/alert_processor/outputs/demisto.py
- stream_alert/alert_processor/outputs/github.py
- stream_alert/alert_processor/outputs/jira.py
- stream_alert/alert_processor/outputs/komand.py
- stream_alert/alert_processor/outputs/pagerduty.py
- stream_alert/alert_processor/outputs/phantom.py
- stream_alert/alert_processor/outputs/slack.py
- stream_alert/shared/alert.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_demisto.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_slack.py
Small improvement over #898
This is done as step 1 in preparation for _Alert Publishers_. In order to implement a proper interface between _Alerts_ and _Outputs_ we need to have this layer communicate across a common vocabulary.
Instead of referencing fields on the alert directly, all `OutputDispatchers` now reference `alert.publish_for(---, ----)`. Currently it has an empty implementation, but in the near future _Alert Publishers_ will be used to modify the return value of this.
This (more or less) replaces `output_dict()`.
All OutputDispatchers offer a simple default integration with some default summary/title/priority/severity. 
However, they also can be overridden by certain fields. You can see an example of this here: …
> [Output] Standardize outputs around `publish_for()` method

- stream_alert/classifier/clients/firehose.py
- stream_alert/classifier/clients/sqs.py
- tests/unit/streamalert/classifier/clients/test_firehose.py
to: @Ryxias 
resolves: #902 
See #902
* Only yielding a batch of records if there are any to send to firehose.
Updating unit tests to confirm there is in fact no batch yielded.
> [bug] fixing issue with trying to send empty batch to firehose (#902)

- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_stream_alert_athena/main.tf
- terraform/modules/tf_stream_alert_cloudtrail/main.tf
- terraform/modules/tf_stream_alert_kinesis_firehose_setup/main.tf
- tests/unit/stream_alert_cli/terraform/test_generate.py
to: @Ryxias 
* Enforcing SSL access only to all StreamAlert S3 buckets.
Updating unit tests to reflect new S3 bucket policy on resources.
> enforce ssl access only on all S3 buckets

- stream_alert/classifier/clients/firehose.py
- stream_alert/classifier/clients/sqs.py
to: @Ryxias 
resolves: #896 
resolves: #910 
See #896, #910
* Adding [`HTTPClientError`](https://github.com/boto/botocore/blob/b55f926bdf73d8783133da851919f5feffc7b655/botocore/exceptions.py#L79) to the list of exceptions to catch and retry.
* This exception now covers both the `ConnectionClosedError` and `ReadTimeoutError` exceptions.
> [bug] retrying ReadTimeoutError via HTTPClientError in sqs and firehose clients

- stream_alert_cli/terraform/classifier.py
- stream_alert_cli/terraform/lambda_module.py
- terraform/modules/tf_lambda/cloudwatch.tf
- terraform/modules/tf_lambda/main.tf
- terraform/modules/tf_lambda/variables.tf
- tests/unit/stream_alert_cli/terraform/test_alert_processor.py
- tests/unit/stream_alert_cli/terraform/test_rule_promotion.py
- tests/unit/streamalert_cli/terraform/test_generate_classifier.py
- tests/unit/streamalert_cli/terraform/test_generate_rules_engine.py
Currently, the `tf_lambda` module does not support custom tags and will only add the `Name: StreamAlert` tag to Lambda/CloudWatch resources.
* Adding the ability to include custom tags in the `tf_lambda` module.
* Any custom tags will be merged with the default tags (ie: `Name: StreamAlert`)
* Updating `classifier` terraform generation code to include the `Cluster` tag.
Updating all unit test for Lambda terraform generation.
> adding ability to add `Cluster` tag to classifier lambda/cloudwatch resources

- publishers/community/slack/slack_layout.py
- stream_alert/shared/description.py
- stream_alert/shared/publisher.py
- tests/unit/stream_alert_alert_processor/test_publishers/slack/test_slack_layout.py
- tests/unit/stream_alert_shared/test_description.py
A peek into what publishers can do!
I implemented a cute service that parses the `rule_description` and does fuzzy extraction of fields like `author:` and whatnot. I did this because I wanted to adhere to our current "conventions" of rule writing. It may not be perfect but it's workable
There are a bunch of mixable publishers for Slack now. Each of them corresponds with a particular colored-section in the above image. To get the exact image above:
```
from publishers.community.slack.slack_layout import PrettyLayout, AttachRuleInfo, AttachPublication, AttachFullRecord
from publishers.other import other_publisher
@rule(
publishers=[
other_publisher,   # presumably your own publisher
Summary,      # Prints the first rausch colored section …
```
> [Alert Publishers] Add some community Slack Publishers

- docs/source/outputs.rst
- docs/source/publishers.rst
- publishers/community/slack/slack_layout.py
- stream_alert/alert_processor/outputs/aws.py
- stream_alert/alert_processor/outputs/carbonblack.py
- stream_alert/alert_processor/outputs/demisto.py
- stream_alert/alert_processor/outputs/github.py
- stream_alert/alert_processor/outputs/jira.py
- stream_alert/alert_processor/outputs/komand.py
- stream_alert/alert_processor/outputs/phantom.py
- stream_alert/alert_processor/outputs/slack.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_slack.py
- tests/unit/stream_alert_alert_processor/test_publishers/slack/test_slack_layout.py
I decided that having magic fields like `pagerduty-incident:asdf` were too easy to get mixed up with normal top-level keys.
*NOTE* I did NOT update the PagerDuty output because I'm currently messing with that on #911  and I don't want to deal with the merge conflicts. They're all going into `2.2.0` anyway.
I introduced a standard to publisher keys: All of them must start with an at-sign `@`.
> [Alert Publishers] Standardizes magic fields with @-sign prefix

- publishers/community/slack/slack_layout.py
- stream_alert/shared/description.py
- tests/unit/stream_alert_alert_processor/test_publishers/slack/test_slack_layout.py
- tests/unit/stream_alert_shared/test_description.py
to: @ryandeivert or @chunyong-lin 
A feature request to add an even-more-customizable slack message, instead of forcing a dict which is harder to read.
* Adds new AttachStringTemplate publisher
* Minor cosmetic improvements to the rule description parser
* Better scopes the `_previous_publication` to `@slack._previous_publication` to reduce data bleeding
CI + tested on stage
> Improvements to Slack Publishers

- publishers/community/pagerduty/pagerduty_layout.py
- stream_alert/alert_processor/outputs/pagerduty.py
- stream_alert/shared/publisher.py
- tests/unit/publishers/community/pagerduty/test_pagerduty_layout.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
to: @chunyong-lin or @ryandeivert 
Nice to have
* Add code support for images on pagerduty-v2. v1 was already supported.
* Adds a new publisher, `AttachImage` that attaches images. It's meant to be subclassed.
* (MInor) adds support for `component`, `group`, and `class` on Pagerduty v2, which aren't really major features but they're nice to have.
CI + Tested on Staging
> [Publishers] Adds support for images on Pagerduty v2

- stream_alert/alert_processor/outputs/output_base.py
- stream_alert/alert_processor/outputs/pagerduty.py
- tests/unit/stream_alert_alert_processor/test_outputs/test_pagerduty.py
to: @ryandeivert or @chunyong-lin 
The `pagerduty-incident` code used to have a serious bug where, due to the way it would sequence multiple write methods non-atomically, it could result in a situation where a Pagerduty alert is sent but the output fails. This results in the alert retrying, creating *another* Pagerduty alert, then failing again... repeating ad infinitum.
This PR introduces two concepts:
PagerDuty's code used to do the following:
* `POST /incidents` (Create an incident container)
* `POST /events/enqueue` (Create an alert)
* `GET /incidents?dedup_key=???` (Find the alert-incident)
* `PUT /incidents/#/merge?incident_id=???` (Merge the alert-incident into the incident container)
I found that this was redundant; the workflow is optimized …
> Make PagerDuty output idempotent; adds support for responder requests

- docs/source/app-configuration.rst
- stream_alert/apps/_apps/README.rst
- stream_alert/apps/_apps/intercom.py
- tests/unit/stream_alert_apps/test_apps/test_app_base.py
- tests/unit/stream_alert_apps/test_apps/test_intercom.py
cc: @patrickod  
[Intercom](https://github.com/intercom) recently made V1.2 of our API stable. V1.2 introduces a new [**Activity Logs** endpoint](https://developers.intercom.com/building-apps/docs/api-changelog#section-view-activity-logs-for-admins-through-our-api). This endpoint makes it possible to get a log of activities taken by all admins in an app via a GET request. 
We (@catpham on behalf of Intercom Security team) are opening this PR to add an Intercom app integration to Streamalert. We think this would be a useful integration for customers who want to automate and further facilitate their Intercom app activity auditing and alarming.
This PR has 3 commits:
1. Adding the Intercom app integration
2. Adding unit tests for the Intercom app …
> [apps] add Intercom app integration

- docs/source/getting-started.rst
Terraform 0.12.X requires explicit relative paths (using a ./ prefix). See: poseidon/typhoon#457. This breaks things, so we should be more explicit about required version.
* Adding terraform required version note
> make Terraform version compatibility more explicit

- stream_alert/rule_promotion/statistic.py
- tests/unit/stream_alert_rule_promotion/test_statistic.py
to: @ryandeivert or @chunyong-lin 
We have a query in the rule promotion lambda that runs several count queries and `UNION ALL`s them together. 
The problem with `UNION ALL` type queries is that Presto is will perform the queries independently of one another; overlapping partitions will be redundantly scanned reducing the speed of the query and also increasing the amount of data scanned, making it slower and more costly.
I modified the `UNION ALL` query to a `GROUP BY` query.
🤷‍♂ CI?
> Restructures a compound query in rule promotion to be more efficient

- stream_alert/rules_engine/threat_intel.py
- tests/unit/streamalert/rules_engine/test_threat_intel.py
to: @chunyong-lin or @Ryxias 
cc: @airbnb/streamalert-maintainers\
resolves: #942 
See #942
* The param validation error that was occurring happened because there were no "keys" being queried against [here](https://github.com/airbnb/streamalert/blob/60e6e7c8f8de631b4ae3c5e4f6177ac2d360d451/stream_alert/rules_engine/threat_intel.py#L204).
Adding a simple unit test to ensure this should be working.
> fixing threat intel bug that caused exception when records contain no potential IOCs

- stream_alert/shared/normalize.py
- tests/unit/stream_alert_shared/test_normalizer.py
to: @Ryxias or @chunyong-lin 
resolves: #942 (actually this time)
Normalization will currently store empty values, like so:
```
'streamalert:normalization': {
'userName': [],
'processPath': []
}
```
and even:
```
'streamalert:normalization': {
'userName': [''],
}
```
... if there is an empty value for the key.
* Updating normalization so it only stores _keys_ if there is in fact a non-empty value to normalize.
Adding some unit tests and removing one that is no longer relevant.
> fixing storage of empty values in normalization

- conf/lambda.json
- requirements-top-level.txt
- requirements.txt
- rules/community/cloudtrail/cloudtrail_critical_api_calls.py
- rules/community/cloudtrail/cloudtrail_public_resources.py
- rules/community/cloudtrail/cloudtrail_snapshot_or_ami_made_public.py
- stream_alert_cli/manage_lambda/package.py
- tests/integration/rules/cloudtrail/cloudtrail_critical_api_calls.json
- tests/integration/rules/cloudtrail/cloudtrail_public_resources.json
- tests/integration/rules/cloudtrail/cloudtrail_snapshot_or_ami_made_public.json
to:
related to:
resolves:
This uses the CloudTrail logs to detect potential misconfigurations and violations of best practices.  It does the following:
- Detects when additional features are turned off (GuardDuty, S3 Public Block Access, and EBS Default Encryption).
- Detects when EBS snapshots, RDS snapshots, or AMIs are made public.
- Detects when resources that use resource policies are made public, the most important being S3 buckets (previously only S3 buckets made public via ACLs were detected) and ElasticSearch clusters.  Additionally it detects Glacier, SQS, SNS, ECR, KMS, and SecretsManager being made public.
- Adds the library `policyuniverse` which was created by Patrick Kelley of Netflix (who also created Security Monkey where that library …
> Best practice rules

- conf/global.json
- stream_alert_cli/terraform/classifier.py
- stream_alert_cli/terraform/common.py
- stream_alert_cli/terraform/generate.py
- terraform/modules/tf_classifier/variables.tf
- terraform/modules/tf_stream_alert_globals/classifier_queue/sqs.tf
- terraform/modules/tf_stream_alert_globals/classifier_queue/variables.tf
- terraform/modules/tf_stream_alert_globals/main.tf
- terraform/modules/tf_stream_alert_globals/variables.tf
- tests/unit/conf/global.json
- tests/unit/stream_alert_cli/terraform/test_generate.py
- tests/unit/streamalert_cli/terraform/test_generate_classifier.py
to: @ryandeivert  @chunyong-lin 
related to: #955 
resolves: #885 
As explained in #885, there is a bug in StreamAlert where the classifier SQS resource does not properly adopt the `PREFIX`.
This problem is complicated by the fact that AWS SQS is stateful, and the resource cannot be renamed without destroying it.
To address the issue, we adopted the suggestion in #955; allowing for the SQS resource name to be conditionally specified.
Now, users can add the StreamAlert prefix to _**NEW**_ classifier SQS deployments. This is configured on `global.json` through the parameter:
`globals.json`
```
...
"infrastructure": {
"classifier_sqs": {
"use_prefix": null
}
},
..
```
The default value currently is `None`/`null`. This is not actually a valid value and will …
> Adds optional prefix to SQS URL

- stream_alert/classifier/payload/payload_base.py
- tests/unit/streamalert/classifier/payload/test_payload_base.py
- tests/unit/streamalert/classifier/payload/test_payload_record.py
to: @Ryxias 
related to:
resolves:
When a record cannot be classified it is logged to CloudWatch. In the current state when printing out a payload, the code relies on the underlying data type to format itself as a string. However this can lead to inconsistent behavior with dictionaries especially when python thinks that there is unicode in the dictionary. This makes working with failed classifications a pain because the output varies. Sometimes it gets output as an actual JSON string, sometimes it gets output as a unicode python dictionary.
* Updated payload_base to encode the record as a JSON string using json.dumps
* Updated tests to reflect the change in output(actual JSON string versus python representation of a dictionary)
Passed unit and …
> Fixed logging output for failed classifications

- conf/lambda.json
related to:
resolves: #964 
I split PR #970 into two PRs, because it includes different bug fixes and we want to check in different fixes to different branch, `master` vs `release-2-3-0`.
This new PR fixes a duplicated dependency `policyuniverse` causes `rules_engine` deployment to be failed when it builds dependencies for `rules_engine` with error message 
```
ERROR: Double requirement given: policyuniverse==1.3.2.0 (already in policyuniverse, name='policyuniverse')
```
* Remove `policyuniverse` from `third_party_libraries` list in `conf/lambda.json`. This dependency is hardcoded in [package.py source file](https://github.com/airbnb/streamalert/blob/master/stream_alert_cli/manage_lambda/package.py#L214), that will be called …
> [conf] Remove duplicated policyuniverse dep from lambda conf

- stream_alert/apps/_apps/slack.py
to: @chunyong-lin @ryandeivert 
related to:
resolves:
The slack app has been failing consistently due to a read timeout. This also occurs locally when testing the endpoint. Additionally the timeout did not appear to change even if the count param was lowered. Therefore we need to bump the default timeout for the app. 10 was chosen to give it some headroom above 8.5 which is around when the timeout stopped happening in local testing. 
* Changed the slack app default request timeout to 10 up from 6.05
Integration and unit tests passed locally.
> Bumped the slack request timeout to 10

- stream_alert/apps/_apps/aliyun.py
- stream_alert/apps/app_base.py
- tests/unit/stream_alert_apps/test_apps/test_aliyun.py
- tests/unit/stream_alert_apps/test_apps/test_app_base.py
related to: #970
resolves:
#970 only fixes partial issue related to Aliyun. During troubleshooting, I discovered the `_last_timestamp` will never be updated if there are more logs to pull but the timeout of Aliyun app lambda function is reached and the lambda function will be finished with starting timestamp. During next Aliyun app run, it will pull same logs over and over again.
This PR is to update `_last_timestamp` correctly, but it will still has small possibility to lose partial ActionTrail events at the same condition that there are more logs to pull but the timeout of Aliyun app lambda function is reached. 
To lower the data loss possibility, suggest to have longer timeout (e.g. 300 sec) for lambda function (aliyun app) …
> [apps] Correctly update aliyun timestamp

- conf/global.json
- stream_alert_cli/terraform/generate.py
- tests/unit/stream_alert_cli/terraform/test_generate.py
related to: #885 
In #960 I added the classifier SQS resource prefix as an optional variable. The default behavior was _"you must specify this or I will error"_.
As promised, in `3.0.0`+, the default behavior now uses SQS resource prefix by default.
> Changes 3.0.0+ behavior to by default include SQS prefix

- .gitignore
A `venv` directory should only be ignored if it's at the root of the repo.
* Updating `.gitignore` to only ignore `venv` at root of repo.
* Removing IDE/environment-specific ignored items.
* **These should be added to your [_global_ `.gitignore`](https://help.github.com/en/articles/ignoring-files#create-a-global-gitignore), not the local one**
> tweaking .gitignore file slightly for venv and IDE files

- .gitignore
- stream_alert/athena_partition_refresh/main.py
- stream_alert/classifier/parsers.py
- stream_alert/shared/rule.py
- stream_alert_cli/terraform/athena.py
- stream_alert_cli/terraform/rule_promotion.py
- tests/unit/streamalert/classifier/test_parsers_csv.py
to: @Ryxias  
* ensuring same order for some terraform variables
* ensuring csv reader receives str when bytes is passed
* adding record logging upon rule failure
* adding logic to not raise exception on s3 test event in athena func
* adding __pycache__ to gitignore
* Adding unit test for csv bytes vs str
> misc fixups to python3 changes

- stream_alert/shared/logger.py
- tests/unit/stream_alert_shared/test_logger.py
to: @Ryxias or @chunyong-lin 
I discovered that tracebacks in the python3 Lambda environment log in a terrible format to CloudWatch Logs. One line gets logged per-entry, instead of a uniform stack trace.
* Adding a custom formatter that replaces new lines with carriage returns.
* Applying formatting to applicable handlers (inside and outside of Lambda env).
Adding unit tests for new formatter logic.
> fixing trash logging in cloudwatch logs

- stream_alert/apps/_apps/slack.py
to: @chunyong-lin, @ryandeivert 
The slack app was still timing out with a 10s api request timeout causing the app to constantly fall behind on data. Bumping the timeout to 30s resolved this issue.
* Bumped default slack request timeout from 10s to 30s.
Unit and integration tests passing locally.
> bumping slack app timeout to 30 seconds

- requirements-top-level.txt
- requirements.txt
to: @chunyong-lin / @Ryxias 
The default shlex supports unicode now, and ushlex is not a thing in python3.
* Removing the ushlex package.
> removing ushlex due to py3 incompatibility

- stream_alert/shared/logger.py
Changes made in #988 stripped the formatting within the lambda execution environment.
* Making change to retain the original formatter's format.
* As specified by the AWS Lambda logging handler, this will now be:
`[%(levelname)s]	%(asctime)s.%(msecs)dZ	%(aws_request_id)s	%(message)s`
> small hack to retain original lambda formatter

- stream_alert/classifier/parsers.py
- tests/unit/streamalert/classifier/test_parsers_base.py
to: @chunyong-lin / @Ryxias 
Discovered bug in classifier when joining a list of not strictly integers:
```
[ERROR] TypeError: sequence item 0: expected str instance, int found
File "/var/task/stream_alert/classifier/main.py", line 26, in handler
Classifier().run(event.get('Records', []))
File "/var/task/stream_alert/classifier/classifier.py", line 244, in run
self._classify_payload(payload)
File "/var/task/stream_alert/classifier/classifier.py", line 164, in _classify_payload
self._process_log_schemas(record, logs_config)
File "/var/task/stream_alert/classifier/classifier.py", line 129, in _process_log_schemas
parsed = parser.parse(payload_record.data)
File "/var/task/stream_alert/classifier/parsers.py", line 482, in …
```
> fix bug with joining non-string values

- conf/lookup_tables.json
- stream_alert/shared/lookup_tables/cache.py
- stream_alert/shared/lookup_tables/driver_dynamodb.py
- stream_alert/shared/lookup_tables/driver_s3.py
- stream_alert_cli/lookup_tables/handler.py
- stream_alert_cli/runner.py
- tests/unit/stream_alert_shared/lookup_tables/test_driver_dynamodb.py
- tests/unit/stream_alert_shared/lookup_tables/test_driver_s3.py
I've added several `manage.py` commands that allow LookupTables to be managed by the CLI.
Shows all currently configured tables.
Using the `--table` and `--key` options, queries the respective LookupTable and returns the value at the key.
Using the `--table`, `--key` and `--value` options, it sets the value into the given LookupTable's key.
> LookupTables management via manage.py

- stream_alert_cli/terraform/generate.py
- stream_alert_cli/terraform/handlers.py
- terraform/modules/tf_lookup_tables/README.md
- terraform/modules/tf_lookup_tables/main.tf
- terraform/modules/tf_lookup_tables/variables.tf
* The `manage.py generate` process now will automatically generate IAM Policies for all of the `classifiers`, `rule_engine`, `alert_processor`, and `alert_merger` to access LookupTables. It uses the `lookup_tables.json` configurations to determine which resources to grant access to.
A long, time consuming process on Staging environment
> Automatically generates AWS IAM Policies for LookupTables

- stream_alert/rule_promotion/statistic.py
- tests/unit/stream_alert_rule_promotion/test_statistic.py
related to: #974 
resolves: #1000 
See [issue #1000 python3 throws TypeError: '<' not supported between instances of 'str' and 'int'](https://github.com/airbnb/streamalert/issues/1000) for the details and root cause.
* Change default value of alert_count from a string to an integer `-1`.
See the reproduce step in issue #1000
> [rule_promotion] Change default value of alert_count to -1

- stream_alert/apps/app_base.py
- tests/unit/stream_alert_apps/test_apps/test_app_base.py
related to: #974 
resolves: #998 
See the details in issue #998 
* Handle `JSONDecoderError` by returning `False, None` without calling to `.json()` method in `response` object
* Add unit test case
* Added following unit test case to reproduce `JSONDecoderError` exception we see in issue #998.
```
@patch('requests.sessions.Session.request')
def test_make_post_request_gateway_timeout(self, requests_mock):
"""App Integration - Make Post Request when gateway timed out"""
requests_mock.return_value = requests.Response()
requests_mock.return_value.status_code = 504
assert_raises(JSONDecodeError, self._app._make_post_request, '', None, None, False)
```
* After we reproduce and well catch the issue, we add current unit test case to test the exception handling …
> [apps] Handle JSONDecoderError

- stream_alert/shared/lookup_tables/core.py
- stream_alert/shared/lookup_tables/driver_dynamodb.py
- stream_alert/shared/lookup_tables/driver_s3.py
- stream_alert_cli/test/handler.py
- tests/unit/stream_alert_shared/lookup_tables/test_driver_s3.py
I found during the production preview that the integration tests didn't work; so I fixed them
> Fixes issues with Integration tests

- manage.py
- stream_alert/__init__.py
- stream_alert_cli/lookup_tables/handler.py
I designed LookupTables' drivers to be able to store any complex JSON-serializable type...
Sadly the CLI command as-is could not do anything other than string. Whooops!
* Now there's a new option: `--json`. It accepts the input `--value` as a JSON encoded string.
* I added a new subcommand, `list-add`. 
* I restructured some of the subcommand code
> Accepts JSON from LookupTables CLI, adds `list-add` command

- streamalert_cli/terraform/generate.py
- terraform/modules/tf_lookup_tables_dynamodb/main.tf
- terraform/modules/tf_lookup_tables_dynamodb/variables.tf
- terraform/modules/tf_lookup_tables_policy/main.tf
- terraform/modules/tf_lookup_tables_policy/variables.tf
- terraform/modules/tf_lookup_tables_s3/main.tf
- terraform/modules/tf_lookup_tables_s3/variables.tf
to: @Ryxias 
There is a bug in terraform that prevents it from being able to get the count for lists that have computed properties.
See: https://github.com/hashicorp/terraform/issues/10857
Fixed here: https://github.com/hashicorp/terraform/issues/12570#issuecomment-512621787
* Adding hard-coded `role_count` as a variable, instead of computing the role list length dynamically.
Terraform apply
> adding role_count var to lookuptables terraform due to tf bug

- streamalert_cli/terraform/classifier.py
- streamalert_cli/terraform/metrics.py
- terraform/modules/tf_alert_processor_iam/main.tf
- terraform/modules/tf_classifier/firehose.tf
- terraform/modules/tf_classifier/variables.tf
- terraform/modules/tf_cloudtrail/main.tf
- tests/unit/streamalert_cli/terraform/test_generate_classifier.py
to: @Ryxias 
* Ensuring order of metric alarms remains unchanged by sorting them by name
* Fixing firehose permission with classifier. This was introduced with firehose prefixing
* fixing inconsistent order of metric alarms
* fixing missed resource name prefix + cluster
Updates to unit tests
> [WIP - do not merge] fixing bugs found during resource migration

- streamalert/shared/lookup_tables/utils.py
- streamalert_cli/lookup_tables/handler.py
- streamalert_cli/test/handler.py
- tests/integration/fixtures/lookup_tables/dynamo-backed-table.json
to: @ryandeivert @chunyong-lin @blakemotl @fusionrace 
Per request from @fusionrace, LookupTables can now import data from a JSON file.
* Adds a new lookup tables CLI command: `lookup-tables set-from-json-file`
* Adds two options to `list-add`: `--sort` and `--unique`
* Refactors some magic code into its own class with disclaimer
There is now a subcommand under the `lookup-tables` command, called `set-from-json-file`
```
$ ./manage.py lookup-tables --help
usage: ./manage.py lookup-tables [-h]
{describe-tables,get,set,list-add,set-from-json-file}
...
Describe and manage your LookupTables
positional arguments:
{describe-tables,get,set,list-add,set-from-json-file}
optional arguments:
-h, --help            show this help message and exit
Available …
```
> [LookupTables] Adds new JSON file import CLI command

- streamalert/shared/normalize.py
- tests/unit/streamalert/shared/test_normalizer.py
fixes: #893
```
[ERROR] TypeError: unhashable type: 'dict' Traceback (most recent call last): File "/var/task/streamalert/classifier/main.py", line 26, in handler Classifier().run(event.get('Records', [])) File "/var/task/streamalert/classifier/classifier.py", line 245, in run self._classify_payload(payload) File "/var/task/streamalert/classifier/classifier.py", line 185, in _classify_payload Normalizer.normalize(parsed_rec, record.log_type) File "/var/task/streamalert/shared/normalize.py", line 118, in normalize record.update({cls.NORMALIZATION_KEY: cls.match_types(record, log_normalized_types)}) File "/var/task/streamalert/shared/normalize.py", line 68, in match_types values.add(value)
```
A small change in the data coming into one …
> Fix unhashable type dict bug

- streamalert/alert_merger/main.py
- streamalert/shared/alert_table.py
- tests/unit/streamalert/alert_merger/test_main.py
- tests/unit/streamalert/shared/test_alert_table.py
to: @ryandeivert or @chunyong-lin or @blakemotl 
We found a couple bugs in the alert merger that caused performance issues.
* Fixes a bug in `_get_alerts()` (which I renamed to `_alert_generator()` where a generator was being immediately materialized, greatly increasing up-front memory consumption
* Sets a limit of 5000 alerts to be processed by the Alert Merger, for a single invocation on any single rule_name. This prevents OOM errors when there are too many alerts on the table. This case also includes a warning.
* Changes the up-front consistent scan operation to a generator to alleviate the need for scanning upfront. Removes high consistency requirement.
Guess I'll find out on production? _**Fingers crossed**_
> AlertMerger query optimizations

- docs/source/clusters.rst
- terraform/modules/tf_kinesis_streams/iam.tf
related to: #1027 
See #1027 
* Adding documentation to show how to supply custom kinesis stream name
N/A
> adding documentation for optional kinesis stream name

- streamalert_cli/terraform/rules_engine.py
The `STREAMALERT_TRACK_RULE_STATS` is currently getting set even if the rules engine config contains something like:
`"log_rule_statistics": false`
which is bad.
* Updating the environment variable inclusion to look for a truthy setting.
N/A
> fix setting of rules engine environment variable

- .travis.yml
- streamalert_cli/test/handler.py
to: @Ryxias or @ryandeivert 
related to: #1019 
resolves: #1044
PR #1019 introduced `stats` argument from cli command line, but is not always exist. It exists in rule test parser, but not classifier parser. When I run `python manage.py test classifier` it throws error `AttributeError: 'Namespace' object has no attribute 'stats'`. 
I did print out the value of options when it passed to test handler, it doesn't has `stats` attribute. 
```
Namespace(command='test', debug=False, files=set(), files_dir='tests/integration/rules/', quiet=False, rules=set(), subcommand='classifier', verbose=False, **{'test subcommand': 'classifier'})
```
The full traceback for future reference
```
python manage.py test classifier                 
Traceback (most recent call …
```
> [cli] Handle when AttributeError when test classifier

- docs/source/clusters.rst
- streamalert_cli/config.py
- streamalert_cli/terraform/s3_events.py
- terraform/modules/tf_lambda/variables.tf
- terraform/modules/tf_s3_events/main.tf
- terraform/modules/tf_s3_events/variables.tf
- tests/unit/conf/clusters/advanced.json
- tests/unit/conf/clusters/test.json
- tests/unit/conf/clusters/trusted.json
- tests/unit/streamalert_cli/terraform/test_generate.py
- tests/unit/streamalert_cli/terraform/test_s3_events.py
to: @chunyong-lin / @Ryxias 
resolves: #1026 
See #1026
* not sorting keys in config, since it is not necessary
* fixing typo in tf description
* removing s3 events legacy garbage for config
* updating tf_s3_events module for proper handling of more than one filter per bucket
* updating tf_s3_events module generation code and tests
* updating documentation to reflect changes to tf_s3_events module
Updates to unit tests. I also init'd this module by itself with tf vars to ensure it was working as expected.
> fixing the tf_s3_events module to properly handle multiple lambda_function blocks

- docs/source/clusters.rst
- streamalert_cli/terraform/s3_events.py
- terraform/modules/tf_kinesis_events/variables.tf
- terraform/modules/tf_lookup_tables_dynamodb/main.tf
- terraform/modules/tf_s3_events/main.tf
- terraform/modules/tf_s3_events/variables.tf
- tests/unit/streamalert_cli/terraform/test_generate.py
- tests/unit/streamalert_cli/terraform/test_s3_events.py
related to: #1035 , #1052 
* Fixing documentation update that was missed.
* Adding fix for potential invalid terraform module name (eg - a bucket name contains a `.`)
* Fixing issue where no `lambda_function` block would be defined for s3 events where no `filter_prefix` or `filter_suffix` parameters were set.
* Removing unnecessary prefixing from role policy/lambda permission resources in `tf_s3_events` module.
* Removing duplicative variable declaration in `tf_kinesis_events` module.
* Updating `# TF-UPGRADE-TODO` block to use local arn list directly as list.
Updating unit tests.
> fixing small bugs with terraform 12 code

- streamalert/apps/_apps/box.py
- tests/unit/streamalert/apps/test_apps/test_box.py
resolves: #1040 
See #1040 
* Adding a change to detect a requests timeout and retry with increased timeout. 
* Once 5 attempts have been made, the original timeout exception will still be raised.
Updating unit test to for retry failure/success cases.
> adding fix for box app request timeout (#1040)

- conf/global.json
- docs/source/getting-started.rst
- streamalert_cli/terraform/generate.py
- streamalert_cli/terraform/handlers.py
- streamalert_cli/terraform/helpers.py
- tests/unit/conf/global.json
- tests/unit/streamalert_cli/terraform/test_generate.py
- tests/unit/streamalert_cli/terraform/test_helpers.py
to: @ryandeivert @chunyong-lin @Ryxias 
resolves: [#1054](https://github.com/airbnb/streamalert/issues/1054)
Currently if multiple people attempt to deploy to the same Streamalert deployment, there is nothing stopping them. This can result in a broken state file since two users are reading/writing from it at the same time. Terraform has native support for remote state locking. In the case of the s3 backend this involves using a DynamoDB table.
This implementation attempts to create and destroy the table automatically as part of the cli process. It bypasses terraform because once locking is enabled the table needs to be created and instead uses boto3. I tested to see if terraform was smart enough to recognize there was a module to create the locking …
> [terraform] support remote state file locking

- streamalert_cli/terraform/handlers.py
related to:
resolves: #1047
During a new deployment of StreamAlert based on branch `release-3-0-0` to stage environment, re-run `python manage.py init` if first init was failed and it would be interrupted with error messages
```
Error: module 'metric_filters_Classifier_FailedParses_PROD_AGGREGATE': unknown module referenced: classifier_prod_lambda
Error: module 'metric_filters_Classifier_SQSFailedRecords_PROD_AGGREGATE': unknown module referenced: classifier_prod_lambda
Error: module 'metric_filters_Classifier_FirehoseRecordsSent_PROD_AGGREGATE': unknown module referenced: classifier_prod_lambda
(...)
```
My investigation is that terraform configuration file `terraform/prod.tf.json` for `prod` cluster (in my case) is deleted but it has been saved in …
> [cli] Fix unknown module referenced bug

- streamalert/classifier/classifier.py
- streamalert/shared/config.py
- streamalert/shared/exceptions.py
- streamalert_cli/config.py
- tests/unit/streamalert/classifier/test_classifier.py
to: @chunyong-lin / @blakemotl 
A misconfigured source configuration will cause the classifiers to fail to process data. Currently, an error is logged and the function just exits. This should fail more verbosely so the user knows something is wrong.
* Adding a new `ConfigError` class (that inherits from a new `StreamAlertError` class)
* Raising `ConfigError` exceptions if there is a sources misconfiguration.
Updating unit tests to check that exceptions are now raised.
> raise exception when config sources are misconfigured

- conf/schemas/osquery.json
related to:
resolves:
If you have mixed osquery versions running in your environment, you may want to update the osquery schemas. In a recent PR, osquery team [Change logNumericsAsNumbers to numerics](https://github.com/osquery/osquery/pull/6002) from osquery v4.1.0. Key `logNumericsAsNumbers` exists in osquery for a while.
* Added two new keys to `conf/schemas/osquery.json` as optional top level keys.
> [schema] Add two new keys to osquery.json file

- streamalert_cli/athena/handler.py
- streamalert_cli/athena/helpers.py
- tests/unit/helpers/config.py
- tests/unit/streamalert_cli/athena/test_handler.py
- tests/unit/streamalert_cli/athena/test_helpers.py
related to:
resolves: #963 
It is pretty common that there will have new keys added to an log schema over the time.  StreamAlert users will have to add these new keys as optional keys to the schema. If the users use Athena to search historical data, it is required to rebuild the table for the log schema which has new key added.
StreamAlert provides command line to alter the table based on the new schema by running following command.
```
manage.py athena rebuild-partitions  --bucket s3.bucket.name  --table-name my_athena_table
```
However, [the maximum allowed query string length in Athena API call is 262144 bytes](https://docs.aws.amazon.com/athena/latest/ug/service-limits.html). In current implementation, StreamAlert will save the whole query into a …
> [cli] Allow to rebuild partitions when the statement length exceeds the limit

- streamalert/athena_partition_refresh/main.py
- tests/unit/streamalert/athena_partition_refresh/test_main.py
to: @ryandeivert @chunyong-lin @Ryxias 
There is a small bug in the Athena partition refresh function where if enough consecutive s3 event notifications are for files and folders that are invalid, the function will throw an exception and fall into a loop where it keeps trying to process these events. An example of this happening, is the creation of s3 placeholder files that end in _$folder$, which fail the regex check.
* Remove the exception thrown when add_partitions adds no partitions(it already logs this anyway)
* Log when a placeholder file is processed by the function.
* Updates tests to account for these changes.
Passing unit/integration tests.
> Don't throw an exception if no partitions are added

- streamalert/classifier/parsers.py
- tests/unit/streamalert/classifier/test_parsers_json.py
related to: 
resolves: #1084
Please see #1084 
* ran unit_test and pylint
> Fix a parser bug when processing raw event encapsulated in a string

- tests/unit/streamalert/classifier/test_parsers_json.py
related to:
resolves:
We use single quote around strings rather than double quotes. Call me crazy...
```
```
> [unit test] Use single quote around strings

- streamalert_cli/terraform/rules_engine.py
- terraform/modules/tf_rules_engine/iam.tf
- terraform/modules/tf_rules_engine/variables.tf
- tests/unit/streamalert_cli/terraform/test_generate_rules_engine.py
related to:
resolves: #1083 
Running `terraform init` failed on `terraform` count
* Updated `streamalert_cli` to pass `bool` to `tf_rules_engine` instead of using the arn for the count (`bool` is known before apply)
* Updated test case to include new key
* Ran `tests/scripts/unit_tests.sh`
* Ran `tests/scripts/pylint.sh`
* Changed to the `tf_rules_engine` directory and ran `terraform fmt`
* Did a full deploy from scratch and it works!
> [terraform] Implemented a fix for the count error

- streamalert_cli/terraform/generate.py
- streamalert_cli/terraform/handlers.py
TL;DR fixing #1047 and #1048 
related to: #1060 #1047 #1048 
resolves: #1048 #1047
The fix introduced in #1060 to fix #1047 caused #1048 . Having deployed numerous times recently, this is how i have managed to remove both issues at the same time.
* changing back to `init=True` so that the backend on destroy is configured as local resolves: #1048 
* Changing which files are removed by the `terraform_cli` to include the metric_filters resolves #1047 (this is because the `metric_filters.tf.json`
Whilst this fixes two issues, it does introduce a new one: 
```Error: Error deleting CloudWatch Log Metric Filter: ResourceNotFoundException: The specified log group does not exist.```
Above is a snippet from: …
> [terraform] fixed #1048 issue by reverting #1060 and fixed #1047

- tests/integration/rules/trendmicro/trendmicro_schema.json
related to:
resolves:
Forgot to enable the tests on previous branch
* validate_schema_only `true` -> `false`
- `./manage.py test rules`
> [testing] enable trend tests, previously only schema

- rules/community/cloudtrail/cloudtrail_public_resources.py
to: @chunyong-lin @ryandeivert 
related to:
resolves: 
Lambda error when this rule was evaluated. There is a `.get()` on a `string`. Setting default as `{}` so that `.get()` works
* default `''` -> `{}`
* Ran `tests/scripts/rule_test.sh`
* Ran `tests/scripts/unit_tests.sh`
> [rule] Fix cloudtrail_public_resources

- conf/schemas/cloudtrail.json
- tests/integration/rules/cloudtrail/cloudtrail_quicksight.json
related to:
resolves: #1100 
Having setup an org cloudtrail, i had errors on events coming in. These keys were added and it resolved the errors
* Added `sourceIPAddress` and `userAgent` to `cloudtrail:events` schema
* Ran `tests/scripts/rule_test.sh`
* Ran `tests/scripts/unit_tests.sh`
* Added an additional test schema only event to `tests/integration/rules/cloudtrail/`
> [core] Updated cloudtrail:events optional_key

- conf/lambda.json
- conf/outputs.json
- docs/source/outputs.rst
- requirements-top-level.txt
- requirements.txt
- streamalert/alert_processor/outputs/teams.py
- streamalert_cli/manage_lambda/package.py
- tests/unit/streamalert/alert_processor/outputs/test_output_base.py
- tests/unit/streamalert/alert_processor/outputs/test_teams.py
related to: #1078
resolves: #1078
We use Microsoft Teams instead of Slack, so I wanted to have the ability to use SA and Teams together 😄
* Implemented `TeamsOutput` (very very similar to the `SlackOutput`)
* Added Tests
* Updated documentation for outputs.rst
* I implemented the output and tested it against an Incoming Webhook on our Teams Instance
* wrote tests in a style similar to the `SlackOutput` tests
* Ran tests and now have 100% Code Coverage for this new addition
* Ran `pylint` against files
* ran `make html` and visually checked addition in browser
> [outputs] add Microsoft Teams as an alerting output

- docs/source/dynamic-outputs.rst
- docs/source/index.rst
- docs/source/rules.rst
- streamalert/rules_engine/rules_engine.py
- streamalert/shared/rule.py
- tests/unit/streamalert/rules_engine/test_rules_engine.py
- tests/unit/streamalert/shared/test_rule.py
related to:
resolves: #1075 
Wanted the ability to dynamically configure outputs based on information in the record
* Now possible to pass dynamic_outputs to the @rule decorator and have
outputs be dynamically configured based on information in the record.
* Added documentation
- Ran `tests/scripts/pylint.sh`
- Ran `tests/scripts/unit_tests.sh`
- Added additional tests to cover the new code
- Ran `tests/scripts/test_the_docs.sh` and verified visually the new documentation changes
> [core] Added dynamic_outputs to Rule

- conf/outputs.json
- docs/source/outputs.rst
- streamalert/alert_processor/outputs/aws.py
- terraform/modules/tf_alert_processor_iam/main.tf
- tests/unit/streamalert/alert_processor/outputs/test_aws.py
- tests/unit/streamalert/alert_processor/outputs/test_output_base.py
related to: #1080
resolves: #1080
Adding support for aws-ses, this is a desired output and one i think others would like.
* Added aws-ses to docs
* Implemented the `SESOutput` Class
* Added tests
* Added additional permissions to the `alert_processor`
* ran `tests/scripts/test_the_docs.sh` and verified additional info was ther
* ran `tests/scripts/pylint.sh` to verify code score and remediated any issues
* ran `tests/scripts/unit_tests.sh` to verify tests worked
* Tried to deploy the `terraform` for release 3-0-0 (this work is based off that branch) and ran into some issues which i am highlighting on `slack` and `github`
> [outputs] aws-ses

- conf/normalized_types.json
Signed-off-by: jack1902 <39212456+jack1902@users.noreply.github.com>
related to:
resolves:
Added normalized types, mainly using the `sourceAccount` within a `dynamic_output` function 
* Added `normalized_types` for trendmicro
- ran `tests/scripts/unit_tests.sh`
> [core] Added trendmicro normalized_types

- Vagrantfile
- vagrant/cli/streamalert/install.sh
- vagrant/cli/streamalert/sshd_config
related to:
resolves:
Using vagrant on a windows machine, i have AWS creds setup through assumed_roles so have to pass `AWS_*` variables through as they only last for a short period of time
* Added `awscli` to `apt-get install` - This fixes the missing `awscli` when connecting to the machine
* Updated the Vagrant file to pass variables through when runninng `vagrant ssh` this includes all the `AWS_*` variables. This required an update of the `sshd_config`
- `vagrant provision && vagrant up && vagrant ssh` then on the box i ran `aws s3 ls | grep streamalert` to see a list of s3 buckets on the machine
> Vagrant AWS cli and env vars

- streamalert/rules_engine/rules_engine.py
- tests/unit/streamalert/rules_engine/test_rules_engine.py
to: @Ryxias
related to: #1124
resolves: #1124
`publishers` and `outputs` weren't being correctly configured
* outputs are generated and then passed into `_configure_publishers` instead of being used on the `rule`
* Updated unit_tests to reflect this
- ran `tests/scripts/pylint.sh`
- ran `tests/scripts/unit_tests.sh` - Fixed errors that occurred due to the change
> [core] Fixed bug with dynamic_outputs and publishers

- tests/scripts/unit_tests.sh
related to:
resolves:
`./tests/scripts/unit_tests.sh` fails on my machine as `AWS_SESSION_TOKEN` is configured and `AWS_DEFAULT_REGION` is different to what the tests are expecting.
* configured `AWS_DEFAULT_REGION` to ensure tests pass which include `moto` resources
* configured `AWS_SESSION_TOKEN` to ensure `boto` isn't picking up my actual token
- Ran `./tests/scripts/unit_tests.sh`
> [testing] Setting other AWS variables during testing

- conf/schemas/duo.json
- streamalert/apps/_apps/duo.py
- tests/integration/rules/duo/duo_anonymous_ip_failure.json
- tests/integration/rules/duo/duo_fraud.json
- tests/unit/streamalert/apps/test_apps/test_duo.py
to: @chunyong-lin / @blakemotl 
DUO added a new key to authentication logs that is breaking classification.
* Adding `alias` field to schema
Please don't suggest adding this as an optional key. I am purposely not adding it as one because that isn't really a thing with APIs that are feeding us data. The intent of "optionals" lets different endpoints have different versions of sensors to allow for backwards/forwards compatibility.
Updates to unit tests and rule tests.
> [schemas] adding alias field to duo auth logs schema

- streamalert/classifier/clients/firehose.py
- streamalert_cli/terraform/classifier.py
If you don't provide an explicit value for `use_prefix`, the default values do not match between the Classifier Terraform and the Python firehose client.
> Fix bug with default value for firehose use_prefix

- streamalert/scheduled_queries/command/application.py
- streamalert/scheduled_queries/config/lambda_conf.py
- streamalert/scheduled_queries/config/services.py
- streamalert/scheduled_queries/handlers/athena.py
- streamalert/scheduled_queries/query_packs/manager.py
- streamalert/scheduled_queries/state/state_manager.py
- tests/unit/streamalert/scheduled_queries/query_packs/test_manager.py
- tests/unit/streamalert/scheduled_queries/state/test_state_manager.py
to: @ryandeivert @blakemotl @chunyong-lin 
Was following up PR #1128 with some refactoring
* The `ServiceContainer` is a controversial point which is rather hard to refactor out of StreamQuery at this time. I decided to "hide it" with a layer of [David Wheeler's dreaded *indirection*](https://en.wikipedia.org/wiki/Indirection). Guess his aphorism holds true. This new layer is the [`ApplicationServices` class](https://github.com/airbnb/streamalert/pull/1130/files#diff-c7c50c03b935b677633e8db443006aaeR40-R67), which is intended to hide the Service Container and its usage through the services.py file
* I greatly expanded the doc blocks available in the Lambda function handler. I think this was important to make it easier to figure out "how" StreamQuery …
> Refactors StreamQuery a little to "hide" the ServiceContainer

- docs/source/dynamic-outputs.rst
- docs/source/rules.rst
related to:
resolves:
Keeping the documentation format consistent with work carried out by @ryandeivert 
* Changed the style to match https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings
* References are now placed at the bottom for dynamic_outputs. This allows changes to file names etc to be made and updated in ONE place. all the places `'outputs'_` is used, it will use the reference at the bottom of doc. This is inline with the style-guide
* Fixed bug where an erroneous `_` should have been a `-`
Built the documentation and verified visually the changes
> [docs] Updating the documentation for dynamic_outputs

- streamalert/alert_processor/outputs/teams.py
related to:
resolves:
Docstring was incomplete and formatting wasn't consistent
* Corrected docstring
* ran `./tests/scripts/pylint.sh` 
* ran `./tests/scripts/unit_tests.sh`
> [docs] Fixing docstring within method

- streamalert_cli/helpers.py
- streamalert_cli/outputs/handler.py
- streamalert_cli/outputs/helpers.py
- streamalert_cli/utils.py
to: @0xdabbad00 @chunyong-lin @ryandeivert 
related to: #1118 #940
resolves: #1118 #940
Wanted the ability to do the following when configuring `outputs` via the CLI:
- set a single output
- set multiple outputs via a file
- get an outputs configuration
- update previously configured url (e.g. add an additional email to `aws-ses`)
Added the following subcommands to `./manage.py outputs`:
- `set` - Set one output, using user_input (pass `--update` to overwrite
existing outputs)
- `get` - Get configured outputs for a service (includes creds) optionally pass `--descriptors` to only pull certain descriptor secrets for the service
- `set-from-file` - Set numerous outputs via a json file. Can set multiple services and descriptors (pass `--update` to overwrite …
> [cli] Added additional commands to outputs

- streamalert/shared/config.py
- streamalert_cli/athena/handler.py
- streamalert_cli/terraform/rule_promotion.py
- terraform/modules/tf_rule_promotion_iam/main.tf
- terraform/modules/tf_rule_promotion_iam/variables.tf
- tests/unit/helpers/config.py
- tests/unit/streamalert_cli/terraform/test_rule_promotion.py
cc: @jack1902
resolves: #1158 
See #1158 
* Adding fix to check if `enabled` is true in the firehose config.
* Removing unnecessary perms for data bucket access by rule promotion function. This function only queries alerts, so this is not needed.
> fixing bug related to athena data bucket not existing

- streamalert_cli/terraform/handlers.py
related to:
resolves: #1159
Previously, the init command had a '-b' flag. This only initialized a local backend but the description on the flag stated 'useful for refreshing a pre-existing deployment'. This flag now actually reflects
this
* added additional function calls to '-b' flag to initialize the remote backend
This generates the `main.tf.json` file containing the `remote` backend instead of the previously `local` backend and downloads the relevant provider plugin versions
Ran the following in order to verify success (pre-existing deployment):
- `./manage.py clean` - Remove ALL terraform configuration files
- `./manage.py init -b` - Initialize the `remote` backend and download the relevant provider plugins and their …
> [cli] fix backend initialization

- streamalert/alert_processor/outputs/teams.py
- tests/unit/streamalert/alert_processor/outputs/test_teams.py
to: @ryandeivert  @Ryxias 
related to:
resolves: #1167 
Wanted the ability to pass buttons to the teams card
* pass `@teams.buttons` as a list of tuples containing the `button_text` and `button_link` in order to add buttons to the card
* Added unit_tests
* Added units tests for this and ran `./tests/scripts/unit_tests.sh`
* Ran it in my environment to produce the below link on a card (text: `console link` url: `LINK TO AWS CONSOLE`)
> [core] Added button ability to teams output

- docs/source/getting-started.rst
- streamalert/apps/_apps/README.rst
I noticed the usage of the `venv` module for python3 was incorrectly using the `virtualenv` name.
* Changing `virtualenv` --> `venv`
> [docs] fixing venv module usage typo

- conf/schemas/duo.json
- tests/integration/rules/duo/duo_anonymous_ip_failure.json
- tests/integration/rules/duo/duo_fraud.json
Duo auth logs schema has changed.
* Add isotimestamp field to duo auth schema
* Updated tests
Tests passing locally
> Added isotimestamp to duo auth schema

- conf/schemas/osquery.json
- tests/integration/rules/osquery/osquery_snapshot.json
to:
related to:
resolves:
The following makes `log_type` an optional top-level key as this is only added by the [TLS logger](https://github.com/osquery/osquery/blob/d373d042606acda3cb46d6424cfe09be6939b554/plugins/logger/tls_logger.cpp#L100) This fixes classification for Filebeat and other non-TLS sources such as Kolide Fleet.  
Add `log_type` an optional top-level key to the OSquery Schema.
> [Schema] OSquery optional TLK

- docs/source/publishers.rst
- docs/source/testing.rst
- rules/community/cloudwatch_events/cloudtrail_critical_api_calls.json
- rules/community/cloudwatch_events/cloudtrail_critical_api_calls.py
- streamalert_cli/test/event.py
- streamalert_cli/test/event_file.py
- streamalert_cli/test/handler.py
- streamalert_cli/test/results.py
resolves: #1149 
**NOTE: I'm merging this into `origin/ryandeivert-refactor-integration-tests`**
The first time I did Alert Publishers I didn't really think through how to do testing well. Taking another pass at this, allowing individuals to write jsonpath-based conditionals.
There is now a new field in integration test JSON files: `publisher_tests`. It takes the following format:
```
"publisher_tests": {
"[OUTPUT_DESCRIPTOR]": [
[
"[PATH]",
"[CONDITIONAL]",
[VALUE]
],
...
},
"[OUTPUT_DESCRIPTOR_2]": [ ... ]
}
```
* `OUTPUT_DESCRIPTOR`: Should be an output that the alert publishes to, e.g. `slack:sample-channel`
* `PATH`: A jmespath-compatible search path.
* `CONDITIONAL`: Currently supports `is` for equality …
> Redesigns Publisher Testing

- rules/community/cloudtrail/cloudtrail_aws_config.py
- rules/community/guardduty/guard_duty_all.py
- rules/matchers/matchers.py
- tests/integration/rules/cloudtrail/cloudtrail_aws_config.json
related to:
resolves:
Added Rules to trigger alerts on AWS Config NON_COMPLIANT and when Config Remediation takes place
* Added rule to Alert on AWS Config `NON_COMPLIANT`
* Added rule to Alert on AWS Config Remediation (this is extremely useful to notify people they got auto-remediated so they don't go crazy when things just suddenly change on them)
* Added the `.json` file to run `./manage test rules` Rules engine passes :)
* Ran `./tests/scripts/pylint.sh` Fixed errors
* Ran `./tests/scripts/unit_tests.sh`
> [rules] Added AWS Config Compliance and Remediation Rules

- streamalert/shared/config.py
- streamalert_cli/test/results.py
- tests/unit/conf/lambda.json
- tests/unit/conf/logs.json
- tests/unit/helpers/config.py
- tests/unit/streamalert/shared/test_config.py
- tests/unit/streamalert_cli/athena/test_handler.py
- tests/unit/streamalert_cli/athena/test_helpers.py
to: @ryandeivert @Ryxias @blakemotl 
related to:
resolves: #1186 
See the issue #1186 for more details.
* Replace all `.` (dot) in the log names in `conf/schemas/*.json` or `conf/logs.json` with `_` (underscore). The change is made to `Config` class where all the conf files are loaded.
* Also update rule test method to replace `.` with `_` when inspect `log` source in the testing events. Eventually there are two carbonblack testing events with `log` set to `carbonblack:ingress.event.procstart` and `carbonblack:ingress_event_procstart`.
* Add unit tests to reproduce the issue and test the code change.
* `python manage.py athena create-table  --bucket nobody2020030420-streamalert-data  --table-name carbonblack_alert_status_updated` works in staging …
> Sanitize log names

- docs/source/config-global.rst
- streamalert/classifier/clients/firehose.py
- streamalert_cli/terraform/firehose.py
- terraform/modules/tf_classifier/firehose.tf
- terraform/modules/tf_kinesis_firehose_delivery_stream/main.tf
- tests/unit/streamalert/classifier/clients/test_firehose.py
related to: #1115 #1188 
resolves: #1190 
See issue #1190 
* Update firehose stream name in `classifier` and pass the new stream name to `tf_kinesis_firehose_delivery_stream` module during terraform generate time. The firehose stream name is based on schema name.
* This change will generate a new stream name if it's longer than 64 characters. In another words, most of the firehose stream name will remain the same.
* For the stream name longer than 64 characters, the first 58 characters remains unchanged and the rest characters will hash to 8 characters by `hashlib.md5()`. `hashlib.md5()` returns 32 characters (128-bit) and we will only take the first 8 characters. There is low chance is too reach the stream name limit, so I don't worry the hash …
> [core] Hash firehose stream name if it is too long

- conf/global.json
This default option actually breaks deploys because it provides the name of an existing logging bucket that is invalid.
Notably, this is already documented here: https://www.streamalert.io/en/release-3-0-0/config-global.html#s3-access-logging
> Removes a default option that is breaking deploys

- streamalert/classifier/clients/firehose.py
- streamalert_cli/athena/handler.py
- streamalert_cli/athena/helpers.py
- streamalert_cli/terraform/firehose.py
- tests/unit/streamalert/classifier/clients/test_firehose.py
- tests/unit/streamalert_cli/athena/test_handler.py
- tests/unit/streamalert_cli/athena/test_helpers.py
related to: 
resolves: #1186
Hope this is the last bug I need to fix for this month 🤞 
`create_table` (used to create table via athena api calls) and `generate_data_table_schema ` (used to create table via terraform) methods will throw error when the log name contains underscore, e.g. `cloudwatch:test_match_types`, although it doesn't error out when the log name contains dots, e.g. `test:log.name.with.dots`, thanks for recent fix #1197 
I realize that `FirehoseClient.load_enabled_log_sources()` returns a dictionary about enabled logs where the key is sanitized log name and the value is the original log name defined either in `conf/schemas/*.json` or `conf/logs.json`. So we can use original log name and we don't need to do `table.replace('_', ':', 1)` …
> Cylin fix create table via athena tf

- terraform/modules/tf_rule_promotion_iam/variables.tf
related to:
resolves:
Minor fix that the type of `alerts_bucket` in `tf_rule_promotion_iam` module should be a `string`.
Ran `terraform validate` internally and it was passed.
> [tf] Change alerts_bucket type to string in tf_rule_promotion_iam module

- streamalert_cli/manage_lambda/package.py
The config json files were also being ignored at package time, breaking deployments.
* Only ignoring json files within the `rules` directory
> fixing bug with ignoring json files

- conf/schemas/carbonblack.json
- docs/source/historical-search.rst
- streamalert/classifier/clients/firehose.py
- streamalert/shared/utils.py
- streamalert_cli/_infrastructure/modules/tf_globals/alerts_firehose/main.tf
- streamalert_cli/athena/helpers.py
- tests/unit/streamalert/classifier/clients/test_firehose.py
related to:
resolves:
Fixed couple bugs discovered during the deployment of parquet feature internally. Also update carbonblack schemas.
* Convert all `alert_severity` and `timestamp` to `string` for all carbonblack schemas. Also add few new keys.
* Address a bug that get correct custom s3 bucket name where stores alerts.
* Address some non-sense in the doc I changed in previous PRs.
* Address a bug when hash the long Firehose stream name.
> [fix] Fix some bugs during internal deployment of parquet

- docs/source/getting-started.rst
- docs/source/historical-search.rst
- streamalert_cli/manage_lambda/package.py
- streamalert_cli/terraform/generate.py
- streamalert_cli/terraform/handlers.py
- tests/unit/streamalert_cli/terraform/test_handlers.py
related to:
resolves:
Deploy a fresh copy of `release-3-1-0` branch to staging environment, for, fun 🤷‍♀ and found couple minor bugs.
* `python manage.py list-targets` command is broken due to recent change of terraform files path.
* Add use test cases to test the code change.
* Add a space when print out `WARNING` messing to remind user to update `file_format` setting.
* Add a `Note` in `getting_started` doc to remind user to update `file_format` setting.
* Fresh checkout `release-3-1-0` branch
* ` python manage.py configure aws_account_id 111111111111`
* `python manage.py configure prefix cylinrelease31`
* `python manage.py init`
* A `ConfigError warming to set "file_format" to "parquet" in "athena_partition_refresh_config"` raised.
* Update …
> Make list targets work again

- streamalert_cli/athena/handler.py
- streamalert_cli/terraform/handlers.py
related to: #1163
resolves:
In #1163, we had additional check on if `firehose` module (for logs) enable or not before creating the `alerts` table. By default, the `firehose` module is disabled and  `alerts` table won't be created during the init time. The `alerts` table is not depend on `firehose` module (for logs). The fix is easy, move the "firehose_data_bucket" check after "alerts" table creation. 
* Move the "firehose_data_bucket" check after "alerts" table creation.
* Change logging severity to `warning` if `firehose` module is disabled in `conf/global.json`.
* Correct a typo in the logging message.
Tested in staging and the `alerts` table is created as expected when `firehose` module remaining disable.
> Missing alerts table creation during init

- streamalert_cli/manage_lambda/package.py
- streamalert_cli/terraform/handlers.py
related to: #1210
Similar to #1210, previous changes broke the `clean` subcommand.
* Fixing path to terraform files for cleaning
* Removing now-unused constants
> fixing clean subcommand, remove unused constants

- conf/global.json
- docs/source/config-global.rst
- streamalert/scheduled_queries/config/services.py
- streamalert/scheduled_queries/query_packs/configuration.py
- tests/unit/conf/global.json
- tests/unit/streamalert/scheduled_queries/query_packs/test_configuration.py
It's now configurable under the node `scheduled_query_locations` in the `global.json` file
> Make scheduled_queries/ directory configurable from global.json

- docs/source/apps.rst
- docs/source/config-clusters.rst
- docs/source/datasources.rst
- docs/source/getting-started.rst
- docs/source/historical-search.rst
- docs/source/rules.rst
We had a report of some broken links in r3. I combed through the docs and fixed all the ones I could identify.
* Link fixes in docs.
* Touch ups to grammar, other small fixes.
> [docs] fixing links in docs, other touch ups

- streamalert_cli/_infrastructure/modules/tf_scheduled_queries/cloudwatch_schedule.tf
- streamalert_cli/_infrastructure/modules/tf_scheduled_queries/iam_roles.tf
- streamalert_cli/_infrastructure/modules/tf_scheduled_queries/step_function.tf
- streamalert_cli/_infrastructure/modules/tf_scheduled_queries/versions.tf
The IAM roles used by the scheduled queries service were not properly using the `/streamalert/` path prefix
* Updating role path prefix.
* Adding tags to resources that support them.
* Removing unnecessary `versions.tf` file.
> [bug] adding scheduled queries iam role path prefix

- streamalert/__init__.py
- streamalert/shared/config.py
- streamalert_cli/terraform/athena.py
- streamalert_cli/terraform/scheduled_queries.py
- tests/unit/conf/scheduled_queries.json
- tests/unit/streamalert_cli/terraform/test_scheduled_queries.py
Reason for the change
* Fixes a bug in `scheduled_queries` terraform module generation related to s3 buckets as map vs list.
* Fixes bug in naming convention of athena results bucket (hypens vs periods as delimiter)
* DRY out some code in athena generation code.
Adding unit tests for schedule queries terraform module generation.
> official release of v3.1.2

- streamalert_cli/manage_lambda/package.py
> Adds missing netaddr lib to rule promo

- conf/outputs.json
- docs/source/outputs.rst
- streamalert/alert_processor/outputs/aws.py
- tests/unit/streamalert/alert_processor/outputs/test_aws.py
- tests/unit/streamalert/alert_processor/outputs/test_output_base.py
to: @ryandeivert @blakemotl @chunyong-lin 
We needed to be able to invoke Lambda across AWS accounts. The problem is the existing Lambda output seems to be.. wrong. It doesn't derive configs from the right place.
Instead of breaking reverse compatibility, I just added a v2 that is easier to set up and is more consistent with existing implementations. This v2 also has the ability to make `sts:AssumeRole` calls, in order to make Lambda invocations across accounts. However, it _assumes_ that you already set up the IAM Policies correctly.
Tested on stage; built a test lambda and was able to invoke it.
> Implements a v2 Lambda Output with AssumeRole

- streamalert/shared/config.py
- streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_setup/outputs.tf
- streamalert_cli/terraform/athena.py
- streamalert_cli/terraform/scheduled_queries.py
- tests/unit/streamalert_cli/terraform/test_athena.py
- tests/unit/streamalert_cli/terraform/test_scheduled_queries.py
A race condition could cause errors like:
```
Error: Error putting S3 notification configuration: NoSuchBucket: The specified bucket does not exist
status code: 404, request id: 5A5ACCB6EB4055B8, host id: vIlTAABEslxBZXQXmF5QRhFi6z4kQ0wW2YUeJdMLKjGpJn4u5irjwctlzAPPDIY1RKsktnKyh5s=
on modules/tf_athena/main.tf line 100, in resource "aws_s3_bucket_notification" "bucket_notification":
100: resource "aws_s3_bucket_notification" "bucket_notification" {
...
```
* Using references to terraform resources/outputs for bucket names to enforce the creation of the resources before we try to use their "value".
Updates to unit tests.
> adding terraform references for some buckets

- conf/lambda.json
- streamalert/artifact_extractor/artifact_extractor.py
- streamalert/shared/config.py
- streamalert/shared/firehose.py
- streamalert_cli/_infrastructure/modules/tf_artifact_extractor/iam.tf
- streamalert_cli/_infrastructure/modules/tf_artifact_extractor/main.tf
- streamalert_cli/_infrastructure/modules/tf_artifact_extractor/variables.tf
- streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_delivery_stream/main.tf
- streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_delivery_stream/variables.tf
- streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_setup/iam.tf
- streamalert_cli/_infrastructure/modules/tf_kinesis_firehose_setup/variables.tf
- streamalert_cli/athena/helpers.py
- streamalert_cli/manage_lambda/deploy.py
- streamalert_cli/terraform/artifact_extractor.py
- streamalert_cli/terraform/firehose.py
- streamalert_cli/terraform/generate.py
- tests/unit/streamalert/shared/test_config.py
- tests/unit/streamalert/shared/test_firehose.py
- tests/unit/streamalert_cli/athena/test_helpers.py
- tests/unit/streamalert_cli/terraform/test_artifact_extractor.py
related to: #1230 
resolves:
This PR is to add terraform resources for Normalization v2 including
* Create a new dedicated Firehose to deliver artifacts to s3 bucket if Artifact Extractor enabled
* Create an Athena table for artifacts if Artifact Extractor enabled
* Attach proper permissions to invoke Artifact Extractor lambda function for Firehoses if it is enabled
* Enable `processing_configuration` on the firehose where enables normalization configuration in its schema configuration field
* Add Artifact Extractor lambda terraform code and proper permissions.
* Added unit test cases to cover the code change
* `python manage.py build` works as expected in staging for following cases
1. With default conf, Artifact Extractor disabled, no resource …
> Normalization reboot - Add terraform resources

- publishers/sample/sample_demisto.py
- rules/sample/sample_demisto.json
- rules/sample/sample_demisto.py
- streamalert/alert_processor/outputs/demisto.py
- tests/unit/streamalert/alert_processor/outputs/test_demisto.py
to: @blakemotl @ryandeivert @chunyong-lin 
Adds ability for Demisto to specify playbook + sample rule, publisher, and test.
Kudos to @blakemotl for owning most of the testing here and discovering this playbook field. I just copy pasta'd his code.
> Demisto Playbooks

- publishers/community/generic.py
- streamalert/artifact_extractor/artifact_extractor.py
- streamalert/shared/normalize.py
- tests/unit/streamalert/artifact_extractor/helpers.py
- tests/unit/streamalert/artifact_extractor/test_artifact_extractor.py
- tests/unit/streamalert/artifact_extractor/test_main.py
- tests/unit/streamalert/rules_engine/test_threat_intel.py
- tests/unit/streamalert/shared/test_normalizer.py
- tests/unit/streamalert_cli/athena/test_helpers.py
- tests/unit/streamalert_cli/terraform/test_artifact_extractor.py
related to:  #1238 
resolves:
This PR is tiny and it is to add a new key `streamalert_record_id` to artifacts as well as original records (in `streamalert_normalization` field). This new keywill be helpful tracing back to the original record when searching in "artifacts" table.
For example, we will be able to use table join search
```
SELECT artifacts.*,
events.detail
FROM 
(SELECT streamalert_record_id AS record_id,
type,
value
FROM "PREFIX_streamalert"."artifacts"
WHERE dt='2020-04-30-01'
AND value='Root') AS artifacts
LEFT JOIN 
(SELECT CAST(json_extract(streamalert_normalization,
'$.streamalert_record_id') AS varchar) AS record_id, detail
FROM "PREFIX_streamalert"."cloudwatch_events"
WHERE dt='2020-04-30-01') AS events
ON artifacts.record_id = …
```
> Add record id to artifacts and record

- docs/source/scheduled-queries.rst
- streamalert/scheduled_queries/query_packs/configuration.py
- streamalert/scheduled_queries/query_packs/manager.py
- streamalert/scheduled_queries/query_packs/parameters.py
- streamalert_cli/_infrastructure/modules/tf_scheduled_queries/outputs.tf
- streamalert_cli/terraform/generate.py
- tests/unit/streamalert/scheduled_queries/query_packs/test_manager.py
to: @chunyong-lin @ryandeivert @blakemotl 
Add support for dynamic parameters on scheduled queries. This adds functionality for user-defined parameters, so users have more than just the pre-defined params.
Additionally, adds supports for LookupTables on scheduled queries. This opens UNLIMITED POSSIBILITIES!
Need to rebuild the LookupTables policies by redeploying scheduled queries:
```
./manage.py build -t scheduled_queries
```
```
./manage.py build -t lookup_tables_iam_dynamodb
```
Tested on prod 🤣
> Supports dynamic parameters

- docs/source/normalization.rst
- streamalert/artifact_extractor/artifact_extractor.py
- streamalert/shared/normalize.py
- streamalert_cli/terraform/generate.py
- tests/unit/streamalert/shared/test_normalizer.py
- tests/unit/streamalert_cli/terraform/test_generate.py
related to: #1178, #1230, #1238, #1237, #1242
resolves:
This PR is to add the optional block `condition` to normalization configure. With this support, we will have more flexibility to normalize only a subset of data. The normalizer will be skipped if the `condition` block presented and the condition is not met.
See [the updated doc](https://github.com/airbnb/streamalert/blob/fca035ed278d39ed2a98d037b9326c568d376f1e/docs/source/normalization.rst#configuration) for the usage of the `condition` block.
* Upgrade terraform aws provider to `2.48.0` to avoid the bug [Unable to remove aws_kinesis_firehose_delivery_stream S3 processors](https://github.com/terraform-providers/terraform-provider-aws/issues/11305)
* Add `condition` block support
* Update the docs …
> Normalization reboot - Add condition support to normalizer

- docs/source/normalization.rst
- streamalert/artifact_extractor/artifact_extractor.py
- streamalert/shared/firehose.py
- streamalert/shared/metrics.py
- tests/unit/streamalert/artifact_extractor/test_artifact_extractor.py
- tests/unit/streamalert/artifact_extractor/test_main.py
- tests/unit/streamalert/shared/test_firehose.py
related to:
resolves:
Add three custom metrics for `Artifact Extractor`
1. `ArtifactExtractor-ExtractedArtifacts`: Log the number of artifacts extracted from the records
2. `ArtifactExtractor-FirehoseFailedRecords`: Log the number of records (artifacts) failed sent to Firehose
3. `ArtifactExtractor-FirehoseRecordsSent`: Log the number of records (artifacts) sent to Firehose
These three custom metrics are useful for tracking the metrics of artifacts by adding them to a CloudWatch dashboard, as well as helpful to set alarms if necessary.
* Allow to pass `function_name` to custom metrics
* Add three custom metrics for `Artifact Extractor`
* Update unit test cases
* Update docs
> Add three custom metrics

- streamalert/apps/_apps/aliyun.py
related to:
resolves:
Looks Aliyun actiontrail api had change to require to `set_EndTime` in the request since yesterday. See a log stream for more error message
```
2020-05-18 07:11:43
START RequestId: bbbbbbbb-dddd-4444-bbbb-999999999999 Version: 34
[INFO]	2020-05-18 14:11:44,028.28Z	bbbbbbbb-dddd-4444-bbbb-999999999999	[aliyun_actiontrail] Starting app
[INFO]	2020-05-18 14:11:44,028.28Z	bbbbbbbb-dddd-4444-bbbb-999999999999	App executing as a successive invocation: False
[INFO]	2020-05-18 14:11:44,029.29Z	bbbbbbbb-dddd-4444-bbbb-999999999999	Starting last timestamp set to: 2020-05-18T14:02:35Z
[ERROR]	2020-05-18 14:11:44,798.798Z	bbbbbbbb-dddd-4444-bbbb-999999999999	ServerException occurred. Host:actiontrail.cn-hangzhou.aliyuncs.com SDK-Version:2.13.5 …
```
> [apps][aliyun] Set EndTime in the request

- streamalert_cli/test/handler.py
to: @chunyong-lin / @blakemotl 
There is a confusing description for a command line flag related to test files. 
* Updating description and removing metavar to make it more obvious that this should be full paths, not file names.
n/a
> updating cli description for supplying test files

- streamalert_cli/config.py
- streamalert_cli/manage_lambda/package.py
- tests/unit/streamalert_cli/manage_lambda/test_package.py
The current `conf` directory is hard coded into the packaging logic. This should not be the case.
* Updating packaging logic to zip up the user-specified config directory (which has a default value of `conf`)
Adding unit test to check for copying to custom destination.
> support for packaging user specified conf directory

- .github/workflows/ci.yml
Coveralls tries to run on PRs from forks, but [fails](https://github.com/airbnb/streamalert/pull/1255/checks?check_run_id=760183550) because forks do not have the token to submit to our coveralls.
* Not running coveralls if repo token is not set.
CI
> omitting coveralls runs for PRs from forks

- docs/source/getting-started.rst
Reason for the change
The current Getting Started instructions don't mention that you need to add the `set` command. As it stands, this is the error I received when setting up Streamalert:
```
(.env) jordan@mac:~/src/aws/streamalert/streamalert$ python manage.py output aws-sns
usage: manage.py output [-h]
{set,set-from-file,generate-skeleton,get,list} ...
manage.py output: error: invalid choice: 'aws-sns' (choose from 'set', 'set-from-file', 'generate-skeleton', 'get', 'list')
```
* Added subcommand to the `python manage.py output` instructions.
Received an error when running the command as prescribed in the documentation. Things seem to work when I added the subcommand.
> Add missing subcommand when setting example SNS output in the "Getting Started" section

- conf/global.json
- docs/source/config-global.rst
- manage.py
- streamalert_cli/config.py
- streamalert_cli/helpers.py
- streamalert_cli/kinesis/handler.py
- streamalert_cli/manage_lambda/deploy.py
- streamalert_cli/manage_lambda/package.py
- streamalert_cli/runner.py
- streamalert_cli/terraform/generate.py
- streamalert_cli/terraform/handlers.py
- streamalert_cli/terraform/helpers.py
- streamalert_cli/utils.py
- tests/unit/conf/global.json
- tests/unit/helpers/config.py
- tests/unit/streamalert_cli/manage_lambda/test_package.py
- tests/unit/streamalert_cli/terraform/test_handlers.py
- tests/unit/streamalert_cli/test_cli_config.py
Users may have additional resources they'd like to create in terraform and track in the streamalert deployment state. We should support this concept.
- adding cli arg (--terraform-file) to supply additional terraform config files. the flag can be used multiple times to supply more than one file (similar to the `terraform --target=... --target=....` logic)
- removing old tf cleanup code since temp path will be used for terraform configuration
- Since runs should now be idempotent, a new temp file will be used every time the CLI is invoked
- adding cliconfig support for temp tf directory
- updates to tf_runner and run_command for temp tf path
- packaging change for tf temp path
- adding logic for copying files to tf temp path
- adding `terraform_files` …
> CLI support for extra user supplied terraform files

- docs/source/config-clusters.rst
- streamalert_cli/_infrastructure/modules/tf_cloudwatch_events/cross_account/README.md
- streamalert_cli/_infrastructure/modules/tf_cloudwatch_events/cross_account/main.tf
- streamalert_cli/_infrastructure/modules/tf_cloudwatch_events/cross_account/variables.tf
- streamalert_cli/_infrastructure/modules/tf_cloudwatch_events/main.tf
- streamalert_cli/terraform/cloudwatch_events.py
- tests/unit/streamalert_cli/terraform/test_generate.py
* Adding new submodule to the `tf_cloudwatch_events` module that allows for proper configuration/support of cross-account CloudWatch Events (via event bus). This includes support for both individual AWS accounts _and_ AWS organizations.
* Added unit test for terraform generation code.
* Applied module in staging account.
> proper cloudwatch events permissions for cross account access

- streamalert_cli/_infrastructure/modules/tf_globals/lambda_layers/README.rst
- vagrant/cli/python-virtualenvwrapper/install.sh
Using `python3 -m venv venv` in vagrant fails with:
```bash
$ python3.7 -m venv venv 
Error: Command '['/home/vagrant/venv/bin/python3.7', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
* Installing venv dep in vagrant
> install venv in vagrant

- streamalert_cli/terraform/generate.py
A previous change omitted copying zips with terraform files, but this breaks the lambda layers.
* Adding back copying of zips
Deployed
> fix copying of terraform to include zips for lambda layers

- docs/source/config-clusters.rst
- streamalert_cli/terraform/cloudtrail.py
- streamalert_cli/terraform/flow_logs.py
- tests/unit/streamalert_cli/terraform/test_generate.py
The cloudtrail module's settings are a bit messy, and can be confusing.
* Updates to config structure for cloudtrail module to lump s3 settings together.
* Doc updates for the above change.
Updates to unit tests
> cloudtrail module config tweak

- streamalert/classifier/payload/s3.py
- tests/unit/streamalert/classifier/payload/test_payload_s3.py
This can happen
```
File "/var/task/streamalert/classifier/payload/s3.py", line 184, in _read_file
client.download_fileobj(key, download)
File "/var/task/boto3/s3/inject.py", line 720, in bucket_download_fileobj
Callback=Callback, Config=Config)
File "/var/task/boto3/s3/inject.py", line 678, in download_fileobj
return future.result()
File "/var/task/s3transfer/futures.py", line 106, in result
return self._coordinator.result()
File "/var/task/s3transfer/futures.py", line 265, in result
raise self._exception
File "/var/task/s3transfer/tasks.py", line 255, in _main
self._submit(transfer_future=transfer_future, **kwargs)
File "/var/task/s3transfer/download.py", line 343, in _submit …
```
> raising exceptions when error occurs while downloading from s3

- streamalert/classifier/payload/s3.py
- tests/unit/streamalert/classifier/payload/test_payload_s3.py
cc: @0xdabbad00 
resolves: #1006 
See #1006
* Logging warning for s3 file with size == 0 and skipping
Update to unit test
> addressing issue with 0 byte files in s3

- docs/source/config-clusters.rst
- streamalert_cli/_infrastructure/modules/tf_cloudtrail/main.tf
- streamalert_cli/_infrastructure/modules/tf_cloudtrail/variables.tf
- streamalert_cli/terraform/cloudtrail.py
Since we support cross-account putobject for s3 data from cloudtrail, we should also allow external accounts to publish to an SNS topic _not_ within the producer account.
* Adding support to allow the same accounts that are enabled for cross account s3 access to publish to the cloudtrail sns topic managed by streamalert.
> allow external accounts to publish to cloudtrail's sns topic

- streamalert_cli/_infrastructure/modules/tf_cloudtrail/main.tf
AWS documentation is great sometime but sucks others.
* Trying something else
Applied in stage
> fixing a bug related to cross account sns I think but who really knows

- streamalert_cli/test/event_file.py
- streamalert_cli/test/handler.py
- streamalert_cli/test/results.py
- tests/unit/streamalert_cli/test/helpers.py
- tests/unit/streamalert_cli/test/test_handler.py
cc: @andreacardaropoli
resolves: #1282 
See #1282
* Adding extra logic to check for improperly configured test events <> cluster data source mappings.
Adding some unit tests for the `TestRunner` to check for proper exception raising.
> adding fix for #1282 to better handle misconfigured test events

- docs/source/outputs.rst
- streamalert/alert_processor/outputs/jira_v2.py
- tests/unit/conf/outputs.json
- tests/unit/streamalert/alert_processor/outputs/test_jira_v2.py
- tests/unit/streamalert/alert_processor/outputs/test_output_base.py
to:
related to:
resolves:
Jira with their SASS offering and later product versions have deprecated the use of basic username + password authentication and instead, they require an API key to be used. 
The following takes the existing `jira` output and adds does the relevant b64 encoding + removes the cookie path. 
* Summary of changes
* ...
Steps for how this change was tested and verified.
- Added Output to StreamAlert instance and carried out test_rules / live to see a jira issue + comment created.
> [OUTPUT] Jira Cloud SASS (jira-v2) 

- streamalert_cli/_infrastructure/_include.tf
to: @ryandeivert @Ryxias @chunyong-lin 
cc:
related to: https://github.com/airbnb/streamalert/issues/1318
resolves: https://github.com/airbnb/streamalert/issues/1318
closes: https://github.com/airbnb/streamalert/issues/1318
AWS has added some additional state checking into the lambda deployment lifecycle, however, the current TF provider version doesn't know how to handle this.
https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/
Users can do a temporary state opt-out via adding `aws:states:opt-out` in the description until the 1st of October...
The smallest change is to update the TF AWS provider to use a new version of the AWS SDK that can handle this. 
* Summary of changes
* ...
> [ISSUE-1318] Deployment Fails with "ResourceConflictException" in Lambda

- conf/schemas/cloudtrail.json
- rules/classifier/cloudtrail/cloudtrail_insights.json
related to:
resolves:
The following adds `cloudtrail:insight` as it's own dedicated log type , more information on this log type can be found at https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-insight-details.html 
This log type can be overloaded into Events but it is distinct enough to warrant it's own log type.
* Add `cloudtrail:insights` 
* Add Test case from documentation https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference.html
Existing unit tests.
> Add new cloud trail insights schema

- streamalert_cli/_infrastructure/_include.tf
Duplicate of https://github.com/airbnb/streamalert/pull/1319 targeting master for a 3.5.1 bug fix. 
to: @ryandeivert @Ryxias @chunyong-lin 
cc:
related to: https://github.com/airbnb/streamalert/issues/1318
resolves: https://github.com/airbnb/streamalert/issues/1318
closes: https://github.com/airbnb/streamalert/issues/1318
AWS has added some additional state checking into the lambda deployment lifecycle, however, the current TF provider version doesn't know how to handle this.
https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/
Users can do a temporary state opt-out via adding `aws:states:opt-out` in the description until the 1st of October...
The smallest change is to update the TF AWS provider to use a new version of the AWS SDK that can …
> ISSUE-1318 Update AWS Terraform Provider

- streamalert/shared/firehose.py
to: @Ryxias @ryandeivert @chunyong-lin 
related to: #1110 
resolves: #1110 
When creating Athena tables for firehose data, Athena helper classes converting special chars in log schema keys by replacing them with ‘_’
However, this sanitization was not performed for items before they're sent to sqs etc resulting in empty records for some keys such as `@timestamp` as used by Osquery & Github 
Athena table column name.. but classifier sending logs to firehose just as ‘@timestamp’ without sanitizing ..
Re-add the data sanitization logic as per earlier stream alert instances, this looks to have been removed due to a number of refactors
Deployed test cluster and confirmed before + after that once this change was deployed , newly classified records where stored …
> ISSUE-1110 Fix Key sanitisation for Athena Storage.
